### ISSUE TITLE
Simultaneous Connections mix State Subscriptions incorrectly correlating with Connections

### ISSUE THREAD

**Issue by NinjaSudo** [infinitered/reactotron#1002]
Discovered while connected to two simulators (Android, iOS) that the State Subscriptions get mixed up when subscribed.

The symptom seen is that when both simulators are running a version of the app, but logged into different users and therefore must have different states; the state subscription updates with the incorrect states correlated with their connections. Don't know what happens if you have more than two connections.

I took screenshots, but realized they might contain client sensitive information. Scrubbing and will see about created an isolated reproduction.

**Comment by yulolimum** [comment]
![image](https://user-images.githubusercontent.com/1775841/57950085-15a66080-789b-11e9-943e-1b29c9d8532a.png)

I ran into this today. Same situation were I'm seeing Android's state in the Ios tab. Couldn't quite figure out the pattern that causes this to happen.

**Comment by rmevans9** [comment]
The way we show the state information can be a bit... odd. I will put it on the list of things to see if we can get better at. Thanks for the report!

**Comment by gsklee** [comment]
This is a true major issue and I will need to get this fixed before I could introduce Reactotron into my team's daily workflow (we're doing some spikes on Reactotron right now).

@rmevans9 if you could help pointing me to the likely source of the issue, I can help creating a fix.

**Comment by rmevans9** [comment]
@gsklee @yulolimum @NinjaSudo Next time one of you guys encounter this issue could you stop for a sec, go to the device you have selected (in @yulolimum example this would be the iOS device) and do something to cause the store to update. I would like to know if causing that store update makes the state window show the right information?
