### ISSUE TITLE
Example ignoreUrls!

### ISSUE THREAD

**Issue by ducpt2** [infinitered/reactotron#1003]
I need some help please, do all research and nothing work.
How to use ignoreUrls to ignore some anoy API response, example:
I have some logs like this: http://localhost:8081/assets/assets/ic_language.svg?platform=ios&hash=6403ceac002f4389684c9e0086a330c0.

How can i avoid it in future? Thanks

**Comment by ducpt2** [comment]
I figure it out:
Reactotron.configure({ host: scriptHostname })
  .useReactNative({
    asyncStorage: false,
    networking: {
      ignoreUrls: /localhost/
    }
  })
  .connect({});

**Comment by hugows** [comment]
`ignoreUrls: /(symbolicated|localhost:8081|generate_204)/,`

**Comment by Balthazar33** [comment]
> `ignoreUrls: /(symbolicated|localhost:8081|generate_204)/,`

@hugows 
What does this do?
