### ISSUE TITLE
[reactotron-js] Uncaught TypeError: createStore is not a function

### ISSUE THREAD

**Issue by e-nouri** [infinitered/reactotron#1009]
I am trying setup Reactotron  in my web app, it seems that the redux plugin in the js version is not working properly, i may be mistaken, but i made sure that the config was called, I inspected the Reactortron object to check if it has the features added by the plugins, i found the sagas features correctly mounted but not the redux one, which is the createStore.

My setup is almost the same as my react-native project, but for the web i am requiring "reactotron-react-js" this is what my code looks like for the configuration (which is the first file called because it mounts the reactotron on the console.log):

`
import Config from './debug'
import Immutable from 'seamless-immutable'
import sagaPlugin from 'reactotron-redux-saga'
import Reactotron, { trackGlobalErrors } from 'reactotron-react-js'
import { reactotronRedux } from 'reactotron-redux'

console.log("useReactotron config")

if (Config.useReactotron) {

  // https://github.com/infinitered/reactotron for more options!
  const reactotron = Reactotron
    .configure({ name: 'Webapp' })
    .use(reactotronRedux({ onRestore: Immutable }))
    .use(sagaPlugin())
    .use(trackGlobalErrors())
    .connect()

  // Let's clear Reactotron on every time we load the app
  reactotron.clear()

  // on every file.  This is just DEV mode, so no big deal.
  console.tron = reactotron
}
`

**Comment by rmevans9** [comment]
Hello!

Can you please show me you're store configuration? Also which version of `reactotron-redux` are you using?

**Comment by e-nouri** [comment]
@rmevans9 that was very quick! thank you for being very reactive mate!
reactotron-redux version: 3.0.0 (i downgraded from the 3.0.3).

My store configuration looks like this:
`
import { createStore, applyMiddleware, compose } from 'redux'
import Config from '../config/debug'
import createSagaMiddleware from 'redux-saga'
import Rehydration from '../services/rehydration'
import ReduxPersist from '../config/reduxpersist'

import { routerMiddleware, connectRouter } from 'connected-react-router'
import { createBrowserHistory } from 'history'


export const history = createBrowserHistory();

// creates the store
export default (rootReducer, rootSaga) => {


  const middleware = []
  const enhancers = []
  

  const sagaMonitor = Config.useReactotron ? console.tron.createSagaMonitor() : null
  const sagaMiddleware = createSagaMiddleware({ sagaMonitor })
  middleware.push(sagaMiddleware)
  middleware.push(routerMiddleware(history))

  enhancers.push(applyMiddleware(...middleware))


  console.log(Config.useReactotron)
  console.log(console.tron)
  console.log(console.tron.createStore)

  // if Reactotron is enabled (default for __DEV__), we'll create the store through Reactotron
  const createAppropriateStore = Config.useReactotron ? console.tron.createStore : createStore
  const store = createAppropriateStore(
    connectRouter(history)(rootReducer),
    compose(...enhancers))

  // configure persistStore and check reducer version number
  if (ReduxPersist.active) {
    Rehydration.updateReducers(store)
  }

  // kick off root saga
  let sagasManager = sagaMiddleware.run(rootSaga)

  return {
    store,
    sagasManager,
    sagaMiddleware
  }
}

`

**Comment by rmevans9** [comment]
Ah - so the 3.x version of `reactotron-redux` actually had a breaking change. That change was that the `createStore` method is no more. Instead you will need to add a reactotron enhancer.

Check here for an example of how to make that happen:
https://github.com/infinitered/reactotron/blob/master/docs/plugin-redux.md#configuring

**Comment by e-nouri** [comment]
You are the man! Now everything working flawlessly, thank you

**Comment by rmevans9** [comment]
Perfect. Closing this issue then 👍
