### ISSUE TITLE
Reactotron freezes with a white screen when "Add Backup"

### ISSUE THREAD

**Issue by hansdesmedt** [infinitered/reactotron#1020]
Steps to reproduce:

- add some data to 1 reducer
- subscribe to that state in reactotron
- go to snapshots -> add backup

Result: white screen, frozen

**Comment by rmevans9** [comment]
I just pushed up a fix for this. Should land tonight at some point once CI catches up! Sorry about that.

**Comment by rmevans9** [comment]
The fix for this is out!

**Comment by hansdesmedt** [comment]
Thanks!
