### ISSUE TITLE
cant see buttons for timeline-action

### ISSUE THREAD

**Issue by achtan** [infinitered/reactotron#1022]
after update to `Version 2.13.2 (2.13.2.434)` i cant see buttons for timeline-action

<img width="926" alt="Screenshot 2019-05-02 at 11 13 21" src="https://user-images.githubusercontent.com/1048212/57066063-7e9ead80-6ccb-11e9-90a5-67fb5097703d.png">

**Comment by rmevans9** [comment]
A fix for this is building now

**Comment by rmevans9** [comment]
This is resolved
