### ISSUE TITLE
no connection on android 9

### ISSUE THREAD

**Issue by yangbo5207** [infinitered/reactotron#1028]
Reactotron version: 2.14.1
android system: android 9

i do this.

<img width="682" alt="屏幕快照 2019-05-06 下午2 28 57" src="https://user-images.githubusercontent.com/13758605/57209505-4ec51200-700b-11e9-82ae-76819df6ba78.png">

and config like this.

```js
Reactotron
  .configure({ host: '192.168.0.123' })
  // @ts-ignore
  .useReactNative()
  .connect();
```

But still can't connect.

After the test, all other android phone and iPhone can connect, but android 9.

**Comment by rmevans9** [comment]
Try to change your host to local host or remove it please. When you do a reverse that means that pointing at localhost on that port will pipe back to your machine

**Comment by yangbo5207** [comment]
@rmevans9 thanks.
