### ISSUE TITLE
error: d.apply is not a function when using the redux plugin

### ISSUE THREAD

**Issue by austinthetaco** [infinitered/reactotron#1031]
![image](https://user-images.githubusercontent.com/7856196/57381580-1256fa80-7160-11e9-88bb-9f4eb63261bb.png)

and here is the createStore:
```
export default offline(customConfig)(createStore)(
  reducers,
  compose(applyMiddleware(
    apiRequestMiddleware,
    connectivityMiddleware,
    Reactotron.createEnhancer(),
    thunk
  ))
);
```

I'm not sure what's wrong with the implementation.

**Comment by austinthetaco** [comment]
I put inside the applyMiddleware when i shouldn't have.

**Comment by jm2242** [comment]
This was helpful!
