### ISSUE TITLE
Custom Shortcut Clear Timeline

### ISSUE THREAD

**Issue by myself379** [infinitered/reactotron#1037]
Hi, my apologies if I were rude in any way, but is it possible to have Clear Timeline on different shortcut other than Ctrl + Backspace? I'm on Windows and I often use Ctrl + Backspace to clear by word whenever I wanted to change something quick couple with Ctrl + f to find specific keywords.

Previous Ctrl + k to Clear Timeline was fine as it doesn't clash with my Ctrl + Backspace.

**Comment by rmevans9** [comment]
I don't think this would be a problem. This actually makes me think it might be worth spending time shifting keybinds to the config file (which admittedly, I gotta fix the ability to open that file on Windows...) which would mean that you could have it as anything you want. I might work through this over the next week.

**Comment by myself379** [comment]
cool! @rmevans9, thanks! Appreciated it very much!

**Comment by markrickert** [comment]
Recently we made `CMD+K` the keyboard shortcut to clear the timeline, just like many terminal applications. Thanks for using Reactotron!
