### ISSUE TITLE
Prevent the window from being dragged when it's a mouse click on the topbar & sidebar

### ISSUE THREAD

**Issue by gsklee** [infinitered/reactotron#1042]
Right now (on Mac if that matters) if you try to click on some button on the topbar as well as the sidebar, oftentimes you'll inevitably drag the window at little bit unintentionally. We should look into at least preventing this unwanted behavior from happening on the sidebar; preferably also find a way to fix this for the topbar, though that might involve some UI works to redesign the topbar.

**Comment by rmevans9** [comment]
I agree. That has bothered me for a while but it has never been a priority. I think it should be a priority. Do you have thoughts on how we could improve this if we have to go down the redesign route?

**Comment by gsklee** [comment]
@rmevans9 That's actually a very big question. If we're willing to go down the redesign route, perhaps first and foremost we'll need to know what's on the roadmap for the app in the next 1-2 years, so that the efforts won't be misaligned and will be something that takes in the whole picture.

**Comment by rmevans9** [comment]
@gsklee I think I should have been more specific. I am not looking for a complete redesign of the entire app (at least for now 😀). I was thinking more for the header to give us a "draggable" area to give the icons a bit of breathing room so we don't drag the window around just because we wanted to click an icon.

**Comment by gsklee** [comment]
I am using the app in fullscreen mode right now so that kinda nullified this issue for me, for now at least.

I am more in favor of a total UI overhaul if I am to get involved on the UI stuff; there are other things we should be looking into, for example only showing some tabs if certain plugins have been plugged in.

@rmevans9 Feel free to close this one and maybe create an overarching UI improvement tracking ticket 😄

**Comment by rmevans9** [comment]
Interestingly enough showing/hiding the tabs based upon what is actually in use is already on my todo list :-). I will go ahead and close this and likely open a ticket with some thoughts on overall changes to the UI/UX I want to make and we can discuss there.
