### ISSUE TITLE
Unable to resolve module `reactotron-core-client` from `/Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/node_modules/reactotron-redux/dist/index.js`: Module does not exist in the module map

### ISSUE THREAD

**Issue by ldco2016** [infinitered/reactotron#1072]
Hi guys,

I am running a React Native application version 0.53 with `"reactotron-react-native": "3.5.0",
    "reactotron-redux": "3.1.0",` and when running Jenkins build I got this error:

```
Unable to resolve module `reactotron-core-client` from `/Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/node_modules/reactotron-redux/dist/index.js`: Module does not exist in the module map
```

as the reason for build failure.

Any suggestions for fixing this other than `rm -rf node_modules && npm install`?

**Comment by rmevans9** [comment]
I suspect I know what this is occurring. I will do some investigations into what I can do about it tonight.

**Comment by lukebars** [comment]
Hey @rmevans9, any news on this? The error is still occurring.

**Comment by lukebars** [comment]
Hey,  @rmevans9 , any ideas about this one? This started randomly occurring to me for the past month. 

Sometimes clean module reinstall helps, sometimes it does not :/

**Comment by markrickert** [comment]
Unless @rmevans9 has any other ideas, i'm going to close this for now. Lots has changed in the codebase so reopen if necessary.
