### ISSUE TITLE
Preferences on File menu opening visual studio on windows

### ISSUE THREAD

**Issue by carlospence** [infinitered/reactotron#1086]
Click on the preference on the file menu opens Visual Studio 2015 on reactotron v2.15, the latest version as @the time of writing this issue.

**Comment by rmevans9** [comment]
Yes, it will open with whatever is set at the operating system level to open JSON files. You can change that setting in the OS. I don’t want to get into the business of having to figure out a way to open different apps depending on what apps are installed so I just let the OS handle.

**Comment by carlospence** [comment]
Yes, I have noticed it depends on the app that is set to open a json file.
