### ISSUE TITLE
react-native cli commands from Reactotron UI

### ISSUE THREAD

**Issue by crobinson42** [infinitered/reactotron#1106]
This is a feature request - It would be super awesome to run the available react-native cli commands from the Reactotron UI!

Useful commands are things like reloading the app, triggering the rn dev menu, clearing the app's storage (might be a native module), etc..

Thoughts?

**Comment by rmevans9** [comment]
![Screen Shot 2019-06-19 at 2 05 47 PM](https://user-images.githubusercontent.com/14151327/59789140-5aa72380-929b-11e9-9b3d-5dab10e41902.png)

In the top right there you have reload and open dev menu already :-)
