### ISSUE TITLE
reactotron cant find the device to connect

### ISSUE THREAD

**Issue by yuritoledo** [infinitered/reactotron#1109]
I've follow the docs, but Reactotron simple dont work.

I'm using to connect on react-native. 
I'm using Manjaro (there is any plus config on linux?)

How to "debug" to find the problem?

Thank you

**Comment by yuritoledo** [comment]
Solved adding `host: '192.168.0.8'` on configure.

**Comment by fabriziobertoglio1987** [comment]
does not work for me. I set the host to my machine wifi address but does not connect on Ubuntu 20.04.
