### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'e.effect.payload')

### ISSUE THREAD

**Issue by diegolmello** [infinitered/reactotron#1119]
Hi, folks!
Enabling saga monitor raises this issue:
![image](https://user-images.githubusercontent.com/804994/62560207-efb5aa00-b852-11e9-911a-47408607ab85.png)

The code pointed out by the error is:
![image](https://user-images.githubusercontent.com/804994/62560521-9601af80-b853-11e9-9458-d1d405df1122.png)

Everything seems to work fine though.

Let me know if I can help debugging.
Cheers! 👊

**Comment by rdgomt** [comment]
Same here.

**Comment by Dakota-Peel** [comment]
https://github.com/infinitered/reactotron-redux-saga/pull/19

**Comment by rmevans9** [comment]
Fixed in https://github.com/infinitered/reactotron-redux-saga/releases/tag/v4.2.3
