### ISSUE TITLE
Error running tests on React Native

### ISSUE THREAD

**Issue by NelsonPRSousa** [infinitered/reactotron#1125]
Reproduce:

* Create a simple project with react-native init (RN 0.60)
* Set up Reactotron (exactly as described [here](https://github.com/infinitered/reactotron/blob/master/docs/quick-start-react-native.md))
* Run _yarn test_
* Tests fail:

Test suite failed to run

    ReferenceError: WebSocket is not defined

      5 |     Reactotron.configure({ name: 'Wanderlust App' })
      6 |         .useReactNative({})
    > 7 |         .connect();
        |          ^
      8 | }
      9 |

      at createSocket (node_modules/reactotron-react-native/dist/index.js:1:14125)
      at a.value (node_modules/reactotron-core-client/dist/index.js:1:9009)
      at Object.connect (src/config/ReactotronConfig.ts:7:10)
      at Object.<anonymous> (App.tsx:29:1)
      
      console.error node_modules/fbjs/lib/warning.js:30

You can see the files:
ReactotronConfig.ts file [here](https://gist.github.com/NelsonPRSousa/2081b738194a86e2c521f23ba4df4f6e)
App.ts file [here](https://gist.github.com/NelsonPRSousa/ca76a895eb5f6159c3ff27617765cb9e)
App-tests.ts file [here](https://gist.github.com/NelsonPRSousa/378b72388f61633a408f562ff3b10bfc)

**Comment by NelsonPRSousa** [comment]
@rmevans9 I believe you fixed this a while back... Are you aware of this?

**Comment by NelsonPRSousa** [comment]
Thanks

**Comment by mthuong** [comment]
@NelsonPRSousa Do you have the sample `WebSocket` mock implementation?

**Comment by NelsonPRSousa** [comment]
No @mthuong, we are no longer using reactotron

**Comment by mehmetnyarar** [comment]
@mthuong 

__mocks__/globalMock.js:

```
jest.mock('global', () => ({
  ...global,
  WebSocket: function WebSocket() {},
}));
```

and configure your jest

````
"setupFilesAfterEnv": [
  "<rootDir>/__mocks__/globalMock.js"
]
```

**Comment by blwinters** [comment]
@mehmetnyarar Set me on the right track, but I got the error: `Cannot find module 'global' from '__mocks__/globalMock.js'`. So instead I added `global.WebSocket = () => {}` to `globalMock.js`.

**Comment by MuhammadMuzammilQadri** [comment]
@blwinters The link you referred to, doesn't contain the complete mock implementation for reactotron either. I tried to add the remaining mock functions but then in redux library code it started showing weird errors, like `b.apply is not a function`

**Comment by blwinters** [comment]
@MuhammadMuzammilQadri I'm guessing this is because some part of your code is calling functions on Reactotron that mine isn't, so the required mock is different. This is all I have that's touching Reactotron, and the tests are working fine with the mock. Perhaps the key is that my mock doesn't actually define `createEnhancer`, so Reactotron is not passed into `configureStore` during testing.

```
// store.ts

import Reactotron from '../../reactotron'

const enhancers: StoreEnhancer[] = []
if (Reactotron.createEnhancer) {
  enhancers.push(Reactotron.createEnhancer())
}

// enhancers are passed into configureStore
```

My mock file:
```
// __mocks__/reactotron-react-native.js

const reactotron = {
  configure: () => reactotron,
  useReactNative: () => reactotron,
  use: () => reactotron,
  connect: () => reactotron,
  setAsyncStorageHandler: () => reactotron,
}

module.exports = reactotron
```

**Comment by vladyslav-honchenko** [comment]
for redux/toolkit my mock
```
// __mocks__/reactotron-react-native.js
const reactotron = {
  configure: () => reactotron,
  useReactNative: () => reactotron,
  use: () => reactotron,
  connect: () => reactotron,
  setAsyncStorageHandler: () => reactotron,
  networking: () => reactotron,
  createEnhancer: () => (next) => (reducer, initialState, enhancer) => {
    const store = next(reducer, initialState, enhancer);
    return store;
  },
};

module.exports = reactotron;
```
