### ISSUE TITLE
Change command collapsed icon to ChevronLeft

### ISSUE THREAD

**Issue by RichiCoder1** [infinitered/reactotron#1130]
This is a very small bit of UX feedback, bit it'd be nice if this guy:
![image](https://user-images.githubusercontent.com/2391878/63299810-4633d700-c29c-11e9-81f9-ce53c68d41f3.png)

Was pointing left instead of right to make it clear this is an expander, not a navigation or context swap.

I'd absolutely be willing to make a PR if ya'll will take my small feedback!

**Comment by rmevans9** [comment]
Seems reasonable to me. I’d accept that

**Comment by RichiCoder1** [comment]
Done as of https://github.com/infinitered/reactotron/pull/1131
