### ISSUE TITLE
Reactotron app is not opening on macOS Catalina

### ISSUE THREAD

**Issue by classified** [infinitered/reactotron#1140]
Hello there,

is there any way i can run Reactotron app on Catalina Beta?. i've attached a image here.

are there any steps which i need to follow to make it work?

<img width="420" alt="Screenshot 2019-08-26 at 10 50 42 AM" src="https://user-images.githubusercontent.com/1496524/63666924-7d037300-c7ef-11e9-9308-e086eaac5cd9.png">

**Comment by classified** [comment]
Okay. so after so many tries i installed Reactotron using Homebrew. It's working fine with Homebrew installation. weird

**Comment by alexandrepalagem** [comment]
@classified working great, thanks!

Install using Homebrew:
```
brew cask install reactotron
```

**Comment by classified** [comment]
So as confirmation by another user also, i think this is the solution right now so closing this issue for now. you can open the issue if need any refinement or improvements.

**Comment by rafalolszewski94** [comment]
I think it shouldn't be closed since issue still persists when installing via release zip (even on official release of Catalina).

**Comment by Dkdaniz** [comment]
> @classified working great, thanks!
> 
> Install using Homebrew:
> 
> ```
> brew cask install reactotron
> ```

Thanks!!

**Comment by PrabodhaNirmani** [comment]
> @classified working great, thanks!
> 
> Install using Homebrew:
> 
> ```
> brew cask install reactotron
> ```

Thanks

**Comment by engineerbaraazakariya** [comment]
I tried first to download it from brew, but the only reason I downloaded it from git release page is because the main page of the git said so, I think the main page should be updated so nobody will need to download the app twice and nobody face same problem.

**Comment by faridsaud** [comment]
If you are having this issue, just could also follow https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

**Comment by k-sav** [comment]
`brew install --cask reactotron` worked for me

**Comment by joshuacue** [comment]
it is now `brew install --cask reactotron`

**Comment by vinay93** [comment]
> `brew install --cask reactotron` worked for me

This worked for me!

**Comment by Abhishek765Flyfin** [comment]
> @classified working great, thanks!
> 
> Install using Homebrew:
> 
> ```
> brew cask install reactotron
> ```

Thanks , this Worked for me

**Comment by anggraito** [comment]
> `brew install --cask reactotron` worked for me

worked for me in monterey. thanks
