### ISSUE TITLE
AsyncStorage not logging actions

### ISSUE THREAD

**Issue by mnemanja** [infinitered/reactotron#1157]
Hi guys and thanks a bunch for this application. It really helps in developing and debugging React-native apps! 

I've set up the Reactotron and I see network and error logs, but no `asyncStorage`.

This is my Reactotron config:

```ts
import Reactotron, { networking, openInEditor, trackGlobalErrors, asyncStorage } from 'reactotron-react-native';
import AsyncStorage from '@react-native-community/async-storage';

Reactotron.setAsyncStorageHandler(AsyncStorage) // AsyncStorage would either come from `react-native` or `@react-native-community/async-storage` depending on where you get it from
  .configure() // controls connection & communication settings
  .useReactNative() // add all built-in react native plugins
  .use(networking())
  .use(openInEditor())
  .use(trackGlobalErrors())
  .use(asyncStorage())
  .connect(); // let's connect!
```

For AsyncStorage I'm using the community version `@react-native-community/async-storage`,

```ts
AsyncStorage.setItem('storage-key', JSON.stringify({some: 'data'}));
```

**Comment by rmevans9** [comment]
Can you try and remove the “use(asyncStorage)” line? Use react native wires that up

**Comment by mnemanja** [comment]
Can't say what changed, but it's working now.

**Comment by Ajmal0197** [comment]
My solution perfectly working:

`
import Reactotron from 'reactotron-react-native';
import sagaPlugin from 'reactotron-redux-saga';
import { reactotronRedux } from 'reactotron-redux';
import AsyncStorage from '@react-native-async-storage/async-storage';

Reactotron.configure({ name: 'app_name' })
  .setAsyncStorageHandler(AsyncStorage)
  .useReactNative()
  .use(sagaPlugin())
  .use(reactotronRedux()) //  <- here i am!
  .connect();

//  patch console.log to send log to reactotron
const yeOldeConsoleLog = console.log;
console.log = (...args) => {
  yeOldeConsoleLog(...args);
  Reactotron.display({
    name: 'CONSOLE.LOG',
    value: args,
    preview: args.length > 0 && typeof args[0] === 'string' ? args[0] : null,
  });
};

export default Reactotron;
`
