### ISSUE TITLE
Request: Add "copy to clipboard" button on http request headers, body and response

### ISSUE THREAD

**Issue by tokict** [infinitered/reactotron#1165]
I have very often needed an option to copy the contents of response or my request body and send it to other devs for replication. 
Could you add a button that would just do json stringify and copy it to the clipboard when that is applicable? 

Or even do an "export request" feature?

**Comment by rmevans9** [comment]
There are already a few copy features there. One of which is the response body as json. You can also export the entire thing as markdown. Does that satisfy your requirements?

**Comment by tokict** [comment]
Wow, the fact I managed not to see that is impressive
