### ISSUE TITLE
problem with AsyncStorage  reactotron.asyncStorageHandler.getItem is not a function.

### ISSUE THREAD

**Issue by sengard** [infinitered/reactotron#1166]
hi 
I have problem with AsyncStorage  

ReactotronConfig.js
```javascript
 import Reactotron from 'reactotron-react-native'
 import AsyncStorage from "react-native";

 Reactotron
    .configure() // controls connection & communication settings
    .setAsyncStorageHandler(AsyncStorage)
    .useReactNative() // add all built-in react native plugins
    .connect(); // let's connect!
```
app.js
```javascript
if(__DEV__) {
  import("./config/ReactotronConfig")
}
```

expo 35
```json
"devDependencies": {
    "reactotron-react-native": "^4.0.2"
  },
```

and I get 
```
reactotron.asyncStorageHandler.getItem is not a function. (In 'reactotron.asyncStorageHandler.getItem(REACTOTRON_ASYNC_CLIENT_ID)', 'reactotron.asyncStorageHandler.getItem' is undefined)
```

well witout setAsyncStorageHandler it's works fine but Reactotron keeps adding connections when I reload device

![Screenshot from 2019-12-06 10-56-21](https://user-images.githubusercontent.com/12879142/70306115-10007000-1817-11ea-94dd-4d27550b834f.png)

Thanks

**Comment by rmevans9** [comment]
You must import AsyncStorage like this `import { AsyncStorage } from 'react-native'`

**Comment by sengard** [comment]
yep thanks my bad (

**Comment by saurabhkanswal** [comment]
AsyncStorage is no longer available in react-native.
you can now import AsyncStorage from @react-native-community/async-storage
