### ISSUE TITLE
Create android instance after reload

### ISSUE THREAD

**Issue by hungdev** [infinitered/reactotron#1205]
Although flipper appears, I still feel reactotron is better, and the interface is easier. Thank Infinitered Dev team.
But i get the bug.
it automatically creates a new instance after reloading, and I have to choose the last instance to see the log

Enviroment:
```
"reactotron-react-native": "^5.0.0"
"react": "16.13.1",
"react-native": "0.63.2",
```

![image](https://user-images.githubusercontent.com/12009276/93433543-1fa5fc80-f8f1-11ea-9378-9af9388f3da8.png)

**Comment by valinaga** [comment]
add this:
`import AsyncStorage from '@react-native-community/async-storage'`
and then append this to `configure(...)`:
`.setAsyncStorageHandler(AsyncStorage)`

**Comment by hungdev** [comment]
> add this:
> `import AsyncStorage from '@react-native-community/async-storage'`
> and then append this to `configure(...)`:
> `.setAsyncStorageHandler(AsyncStorage)`

it worked. thank you <3
