### ISSUE TITLE
Missing type `createEnhancer` when using with typescript

### ISSUE THREAD

**Issue by raulmax319** [infinitered/reactotron#1222]
When using redux with reactotron i get the following problem message when using with typescript.
 ``Property 'createEnhancer' does not exist on type 'Reactotron<ReactotronReactNative> & ReactotronReactNative'.ts(2339)``

Here what my code looks like:

``createStore.ts``
```ts
import { createStore, applyMiddleware, Store, compose } from 'redux';
import thunk from 'redux-thunk';

import { ReactotronInstance as Reactotron } from '~/services/reactotron';
import rootReducer from './rootReducer';

const enhancer = __DEV__
  ? compose(Reactotron.createEnhancer(), applyMiddleware(thunk))
  : applyMiddleware(thunk);

export const store: Store = createStore(rootReducer, enhancer);
```

``reactotron.ts``
```ts
import Tron from 'reactotron-react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {
  ReactotronConfig,
  DEFAULT_REACTOTRON_CONFIG,
} from './reactotronConfig';
import { RootNavigation } from '~/navigator';
import { clear } from '~/utils/storage';

declare global {
  interface Console {
    tron: typeof Tron;
  }
}

let ReactotronInstance: typeof Tron;
const config: ReactotronConfig = DEFAULT_REACTOTRON_CONFIG;

if (__DEV__) {
  const Reactotron = require('reactotron-react-native').default;

  const { reactotronRedux } = require('reactotron-redux');

  ReactotronInstance = Reactotron.setAsyncStorageHandler(AsyncStorage)
    .configure({
      name: config.name || require('../../../package.json').name,
    })
    .useReactNative({
      asyncStorage: config.useAsyncStorage ? undefined : false,
    })
    .use(reactotronRedux())
    .connect();
}

ReactotronInstance.clear();

console.tron = ReactotronInstance;

export { ReactotronInstance };

```

**Comment by NgocLe1001** [comment]
<img width="667" alt="image" src="https://user-images.githubusercontent.com/57764602/158048834-d29fb569-0ca0-4eab-8b1e-8a7c77124a3e.png">
I catch this error? Any solution please. thanh you

**Comment by thadk** [comment]
Similar but not identical resolved issue of using with Redux Tookit https://stackoverflow.com/questions/73358881/how-we-configure-reactotron-with-reduxjs-tookkit

With Redux Toolkit + typescript, in store.ts, I successfully used:
```
export const store = configureStore({
    reducer: {
        ffurf: ffurfReducer,
        auth: authReducer,
    },
    enhancers: [
        Reactotron.createEnhancer!(),
    ],
})
```

**Comment by vdr-mm-quan** [comment]
<img width="679" alt="Screenshot 2023-08-07 at 11 29 13" src="https://github.com/infinitered/reactotron/assets/133188379/0b296996-2e46-4495-8243-63e9e02a2f75">
@thadk Hi, thanks for your answer, I'm facing another issue with jest test. Is anyone facing the same issue? 
Thank you guys!

**Comment by MarcosSarges** [comment]
> <img alt="Screenshot 2023-08-07 at 11 29 13" width="679" src="https://user-images.githubusercontent.com/133188379/258699855-0b296996-2e46-4495-8243-63e9e02a2f75.png">
> @thadk Hi, thanks for your answer, I'm facing another issue with jest test. Is anyone facing the same issue? Thank you guys!



woker me 

```js

const enhancers = Reactotron?.createEnhancer
  ? composeEnhancers(applyMiddleware(...middlewares), Reactotron.createEnhancer())
  : composeEnhancers(applyMiddleware(...middlewares));

const store = createStore(persistedReducer, enhancers);

```

**Comment by phuocantd** [comment]
try `[(Reactotron as any).createEnhancer()]` it work for me

**Comment by umairm1alik** [comment]
Wokring for me
enhancers: getDefaultEnhancers =>
    getDefaultEnhancers().concat(Reactotron.createEnhancer()),
