### ISSUE TITLE
does m1 apple silicon supports this softwre?

### ISSUE THREAD

**Issue by rajeshivn** [infinitered/reactotron#1233]
If you have a general question, please ask it in the #reactotron channel of the
[Infinite Red Community slack](https://community.infinite.red/).

When reporting a bug, please include steps to reproduce the issue.

**Comment by rajeshivn** [comment]
I am waiting for reply

**Comment by Albert-Gao** [comment]
No, it is not, since Electron introduced M1 support from v11, and this tool uses a legacy version, so it is not.

**Comment by flexbox** [comment]
Hey @rajeshivn 

If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨
