### ISSUE TITLE
No longer maintained? In the past year, one commit was uploaded.

### ISSUE THREAD

**Issue by dongdyang** [infinitered/reactotron#1235]
If you have a general question, please ask it in the #reactotron channel of the
[Infinite Red Community slack](https://community.infinite.red/).

When reporting a bug, please include steps to reproduce the issue.

**Comment by traviswimer** [comment]
It seems the community slack no longer exists either.

It's odd that the Ignite docs recommend Reactotron, but it does appear to be maintained. I'd be interested in knowing if Infinite Red is still using it themselves.

**Comment by frankcalise** [comment]
New version released and dev is picking up!
