### ISSUE TITLE
Add Zustand support

### ISSUE THREAD

**Issue by TheEhsanSarshar** [infinitered/reactotron#1243]
Zustand is a state management library.
it's compatible with Redux dev tools and it could be possible to integrate it with Reactotron easily.

please give me some hints and I will work on this

**Comment by AugustoAleGon** [comment]
+1

**Comment by netojose** [comment]
+1

**Comment by lk11601** [comment]
+1 - will give $50 AUD incentive to anyone if added within 2 weeks

**Comment by t0ma5h** [comment]
++++

**Comment by aylonmuramatsu** [comment]
Hello friends!
recently I had the same need, so I decided to develop a plugin for zustand.
It's very simple, but I believe it can help you as it helped me :)

https://github.com/aylonmuramatsu/reactotron-zustand-plugin

Note: sorry my english :(

**Comment by joalisonpereira** [comment]
I took the liberty of putting @aylonmuramatsu  code in an npm package.

https://www.npmjs.com/package/reactotron-plugin-zustand
