### ISSUE TITLE
M1 apple silicon support?

### ISSUE THREAD

**Issue by vantuan88291** [infinitered/reactotron#1246]
Did reactotron support M1? I cannot open reactotron in m1 mac

**Comment by maniac-tech** [comment]
> hi vantuan88291, I have a mac air m1 and in version 2.17.1 i was able to open it. I hope it helps you.

@hiagopsilva is it functioning for you?

I'm unable to connect my Real device to Reactotron

**Comment by hiagopsilva** [comment]
how is your reactotron setting?

**Comment by maniac-tech** [comment]
> how is your reactotron setting?

Anything specific you want to know @hiagopsilva ?

**Comment by huyopen** [comment]
same issue on me and I solved it by upgrade my macOS. 
hope this can work for you too.

**Comment by FadiAboMsalam** [comment]
@theonetheycallneo  which version worked on urs i tried the [Reactotron-3.0.0-beta.9.dmg](https://github.com/infinitered/reactotron/releases/download/v3.0.0-beta.9/Reactotron-3.0.0-beta.9.dmg) and it didn't work on android only !

**Comment by theonetheycallneo** [comment]
@FadiAboMsalam Yes the dmg works on my m1 for android and iOS apps.  However the mac.zip did not.

**Comment by FadiAboMsalam** [comment]
@theonetheycallneo yes it worked with me after also updating the dev dependency to latest version and doing **adb reverse tcp:9090 tcp:9090**

**Comment by moxorama** [comment]
I've installed the last one - it's still Intel (running via Rosetta)

**Comment by Anthony1993123** [comment]
Is there any plan to build a arm64 version for M1 Mac?
I found it super slow running on a M1 chip via Rosetta compare to running it on a intel chip machine.

**Comment by frankcalise** [comment]
M1 support is available. You can use the latest set of alpha releases without any issue. 
https://github.com/infinitered/reactotron/releases/tag/reactotron-app%403.0.0-alpha.21 

Also 2.17.1 should have been fine also.

**Comment by vantuan88291** [comment]
> M1 support is available. You can use the latest set of alpha releases without any issue. https://github.com/infinitered/reactotron/releases/tag/reactotron-app%403.0.0-alpha.21
> 
> Also 2.17.1 should have been fine also.

still intel when i install it, not for m1

**Comment by frankcalise** [comment]
There are now -arm64 specific builds that can be found under the release tag!
