### ISSUE TITLE
Reactotron App not working with : chip - Mac M1 Pro, Mac OS - Monterey

### ISSUE THREAD

**Issue by swapnilpathare** [infinitered/reactotron#1247]
Hello there,

PFA image for error message.
i installed app using this command : **brew install --cask reactotron**
also i tried to direct download the app and run still same.

is there any way i can run Reactotron app on Mac OS - Monterey with M1 Pro chip?
are there any steps which i need to follow to make it work?

<img width="259" alt="Screenshot 2022-04-20 at 12 12 29 PM" src="https://user-images.githubusercontent.com/24829679/164167360-28b7f66b-8d5b-4e33-9576-45909e0e4a89.png">

**Comment by maniac-tech** [comment]
Have you tried allowing installation of apps bypassing the above security message?

In my case I was able to install it, but it is not connecting to the device.

**Comment by maniac-tech** [comment]
> Have you tried allowing installation of apps bypassing the above security message?
> 
> In my case I was able to install it, but it is not connecting to the device.

Checkout `If you see a warning message and can’t install an app` [here](https://support.apple.com/en-us/HT202491)

**Comment by swapnilpathare** [comment]
@maniac-tech,  thanks!
it works for me, after doing this change.
thanks, closing this issue.
