### ISSUE TITLE
mac version can't be opened

### ISSUE THREAD

**Issue by maariyadiminsky** [infinitered/reactotron#1255]
### Issue
<img width="402" alt="Screen Shot 2022-07-12 at 10 30 04 AM" src="https://user-images.githubusercontent.com/87329498/178545099-5f4a960a-3c8d-407e-a549-a923313b9dc0.png">

### Steps
1. Install [Reactotron-2.17.1-mac.zip](https://github.com/infinitered/reactotron/releases/download/v2.17.1/Reactotron-2.17.1-mac.zip).
2. Unzip and try to open.

### Notes
Also tried right clicking and clicking 'open', doesn't work either.

**Comment by maariyadiminsky** [comment]
This fixed it for me but it might be a good idea to update the docs on why item to download at the very least for mac users: https://github.com/infinitered/reactotron/issues/1203#issuecomment-691487211

**Comment by jamonholmgren** [comment]
@maariyadiminsky Thanks for the info! Would you be able to submit a PR to update the readme?
