### ISSUE TITLE
Error using reactotron + VITE

### ISSUE THREAD

**Issue by K4ME** [infinitered/reactotron#1259]
I have a project create using Create React App (CRA) and reactotron, now I'm migrating the project to Vite (https://vitejs.dev) and I'm getting this error bellow: 

![error reactotron](https://user-images.githubusercontent.com/33429566/192368945-536a79f7-be36-4102-821e-f0a020452c44.png)

I found a similar issue (https://github.com/vitejs/vite/discussions/5912) and the correct answer says to contact you guys so you can check about this outdated dependency. 

Anyone can help me on this?

**Comment by K4ME** [comment]
I removed the package from the project.

**Comment by cesardeazevedo** [comment]
Fixed by adding this to vite.config.ts

```
...
    define: {
      global: {},
    }
...
```
