### ISSUE TITLE
Can't able to see the Error in Reactotron's time line

### ISSUE THREAD

**Issue by Rajeshkumar-sivaprakasam** [infinitered/reactotron#1260]
I have connected my react application to Reactotron app. and i did some mistakes myself only . But those are not even showing there in my Reactotron's timeline window.. For reference see the image below.

![image](https://user-images.githubusercontent.com/43309655/200183684-1e69cf34-7915-4f58-8d02-a8263726c787.png)

**Comment by rizwanatta** [comment]
can you show your reactotronConfig file ?

**Comment by rizwanatta** [comment]
@midrizi check mine above it works fine and has no issues with it!

**Comment by nolife08021** [comment]
Hi, i not able to see the error from Reatotron too.
"reactotron-react-native": "^5.0.3"

```

Reactotron.setAsyncStorageHandler(AsyncStorage) // AsyncStorage would either come from `react-native` or `@react-native-community/async-storage` depending on where you get it from
  .configure() // controls connection & communication settings
  .useReactNative() // add all built-in react native plugins
  .use(trackGlobalErrors()) // <--- here we go!
  .connect(); // let's connect!
```

**Comment by joshuayoes** [comment]
Fixed in https://github.com/infinitered/reactotron/pull/1292
