### ISSUE TITLE
ReferenceError: WebSocket is not defined

### ISSUE THREAD

**Issue by til2000** [infinitered/reactotron#1277]
# Steps / App / System description:
- reactotron-app_3.0.0-alpha.20_amd64.deb
- Redux App, running on non-standard port (3300), not using WS

    ```
    package.json:
        ...
        "redux": "^4.2.0",
        "reactotron-react-js": "^3.3.8",
        "reactotron-redux": "^3.1.3",
        ...
    ```

- ReactotronConfig
    ```
    import Reactotron from 'reactotron-react-js'
    import { reactotronRedux } from 'reactotron-redux'
    
    const reactotron = Reactotron
      .configure() // we can use plugins here -- more on this later
      .use(reactotronRedux())
      .connect() // let's connect!
    
    export default reactotron
    ```

I'm not using WebSocket in my app, if that's of any concern.
it works when just saving the changes while the app is running in dev mode ( `next` ), but as soon as the app gets refreshed the error occurs:

# Error

```
Server Error

ReferenceError: WebSocket is not defined
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source

ReactotronConfig.js (9:3) @ eval

   7 | .configure() // we can use plugins here -- more on this later
   8 | .use(reactotronRedux())
>  9 | .connect() // let's connect!
     | ^
  10 | 
  11 | export default reactotron
```

**Comment by joshuayoes** [comment]
This should be resolved now in the beta:
https://github.com/infinitered/reactotron/releases/tag/reactotron-app%403.0.0-beta.18

I have been testing the latest Reactotron with Ignite and I'm not having that issue anymore: https://github.com/infinitered/ignite
