### ISSUE TITLE
Storybook tab does not work in reactotron-app@3.0.0-alpha.20

### ISSUE THREAD

**Issue by joshuayoes** [infinitered/reactotron#1279]
# Issue
React Native -> Storybook storybook link does not work. Something about the tab navigation on this link does not navigate to a new tab

https://user-images.githubusercontent.com/37849890/225112824-583e21f2-9519-4dc8-8a69-bb3115887cd3.mov

# Recreate
1. Checkout `reactotron-app@3.0.0-alpha.20`
2. `yarn`
3. `yarn start`
4. Click "React Native" tab
5. Click "Storybook" tab

**Comment by carlinisaacson** [comment]
Also happening on state tab

https://user-images.githubusercontent.com/1761434/225402349-9421e231-a7c4-42f8-8a8e-0b379017769d.mov

**Comment by joshuayoes** [comment]
This is now fixed as of [reactotron-app@3.0.0-beta.12](https://github.com/infinitered/reactotron/releases/tag/reactotron-app%403.0.0-beta.12)
