### ISSUE TITLE
Reactotron Cli

### ISSUE THREAD

**Issue by icywolfy** [infinitered/reactotron#1285]
Any idea what would be the level of effort to create a CLI version of reactotron? 
Using a desktop app is really inconvenient as it both breaks workflow and ease of use of my keyboard only setup. (no mouse)

Using reactotron involves remoting into a separate computer vs having it readily available through the terminal connection where everything is being developed and run.
Reactotron is not a great experience for keyboard-only users.

**Comment by joshuayoes** [comment]
This would be very helpful, but at this point, we are still focused on having a tight experience with the desktop app. If this is something you are interested in helping develop, that would be appreciated.
