### ISSUE TITLE
After updating to beta versions, types for `onCustomCommand` handlers no longer work as expected

### ISSUE THREAD

**Issue by markrickert** [infinitered/reactotron#1299]
I have this custom command:

```js
Reactotron.onCustomCommand({
  command: 'navigateTo',
  handler: (args: { route: string }) => {
    const { route } = args;
    if (route) {
      Reactotron.log!(`Navigating to: ${route}`);
      navigationRef.current?.navigate(route as any);
    } else {
      Reactotron.log!('Could not navigate. No route provided.');
    }
  },
  title: 'Navigate To Screen',
  description: 'Navigates to a screen by name.',
  args: [
    {
      name: 'route',
      type: ArgType.String,
    },
  ],
});
```

After upgrading to beta versions, I'm getting a typescript error on the `handler` arg: 

> Type '(args: {    route: string;}) => void' is not assignable to type '(args?: { [x: string]: ArgType; } | undefined) => void'.
>  Types of parameters 'args' and 'args' are incompatible.
>    Type '{ [x: string]: ArgType; } | undefined' is not assignable to type '{ route: string; }'.
>      Type 'undefined' is not assignable to type '{ route: string; }'.

@joshuayoes Helped me figure out how to get the types to work properly like this:

```js
Reactotron.onCustomCommand<[{ name: 'route'; type: ArgType.String }]>({
  command: 'navigateTo',
  handler: (args) => {
    const { route } = args ?? {};
    if (route) {
      Reactotron.log!(`Navigating to: ${route}`);
      navigationRef.current?.navigate(route as any);
    } else {
      Reactotron.log!('Could not navigate. No route provided.');
    }
  },
  title: 'Navigate To Screen',
  description: 'Navigates to a screen by name.',
  args: [
    {
      name: 'route',
      type: ArgType.String,
    },
  ],
});
```

This happened after upgrading the following versions:

* `reactotron-core-client` 2.8.10 to 2.8.11-beta.7
* `reactotron-mst` 3.1.4 to 3.1.5-beta.7
* `reactotron-react-native` 5.0.3 to 5.0.4-beta.7

**Comment by joshuayoes** [comment]
@markrickert this should be resolved now as of these releases:
[release(reactotron-core-client): 2.8.11-beta.10 [skip ci]](https://github.com/infinitered/reactotron/pull/1252/commits/8c4fdb0ac07cd6057689418697bd01cd6b0db253)
[release(reactotron-react-native): 5.0.4-beta.11 [skip ci]](https://github.com/infinitered/reactotron/pull/1252/commits/b8b7f4fce982299eb59ef94bda7417e01faf01c6)
[release(reactotron-react-js): 3.3.9-beta.10 [skip ci]](https://github.com/infinitered/reactotron/pull/1252/commits/6559e24ddf55ee207568f9a0040c3cc15c8744aa)
[release(reactotron-redux): 3.1.4-beta.10 [skip ci]](https://github.com/infinitered/reactotron/pull/1252/commits/8c342aab4e2a505a2ab9741132f24c52d28768b4)
[release(reactotron-mst): 3.1.5-beta.10 [skip ci]](https://github.com/infinitered/reactotron/pull/1252/commits/3e9f1e8a9fd6f046cbab0e92154dedcab9505ca0)
