### ISSUE TITLE
Unable to connect ot Reactotron from an Expo React native application

### ISSUE THREAD

**Issue by maniac-tech** [infinitered/reactotron#1301]
If you have a general question, please ask it in the #reactotron channel of the
[Infinite Red Community slack](https://community.infinite.red/).

Steps:
Followed the steps mentioned in the Readme, but couldt connect to the Reactotron application.

Reactotron version: 2.17.1

**Comment by joshuayoes** [comment]
See this thread https://github.com/infinitered/reactotron/issues/1107#issuecomment-520672073

**Comment by MateuszRostkowski** [comment]
@maniac-tech Please check my comment here: https://github.com/infinitered/reactotron/issues/1305#issuecomment-1732038422

**Comment by joshuayoes** [comment]
Closing this as a duplicate of https://github.com/infinitered/reactotron/issues/1107
