### ISSUE TITLE
Remove flipper code from reactotron-react-native

### ISSUE THREAD

**Issue by joshuayoes** [infinitered/reactotron#1333]
We currently depend on react-native-flipper https://github.com/infinitered/reactotron/blob/b6c32b6975a3df4617eabc693cf8007a5326c1b4/lib/reactotron-react-native/package.json#L53

We have a separate entry point in the package that references this
https://github.com/infinitered/reactotron/blob/master/lib%2Freactotron-react-native%2Fsrc%2Fflipper-connection-manager.ts

However this code really shouldn't be in this package.

We have deprecated support for flipper, so we should remove this code to help slim down some of the package size.

**Comment by alessioemireni** [comment]
any updates?

**Comment by jamonholmgren** [comment]
This is planned, just haven't gotten to it yet. I think @morganick might take it on.
