### ISSUE TITLE
react-query devtool for react-native ?

### ISSUE THREAD

**Issue by chanphiromsok** [infinitered/reactotron#1336]
- react-query is already has Devtool for web but unfortunately mobile is not exist
- can anyone provide me create plugin for reactron ?

**Comment by mazenchami** [comment]
@chanphiromsok thanks for bringing this up. we currently have a plugin for `reactotron` and `react-query` called ``. Take a look at [PR#106](https://github.com/infinitered/ChainReactApp2023/pull/106) from our Chain React 2023 app!

I'll go ahead and close this issue but please re-open if it doesn't fit what you're looking for.
