### ISSUE TITLE
Feature: Jokes in the timeline

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/reactotron#1359]
When we have a blank timeline, it's a opportunity to add some jokes. Let's get 10+ debugging jokes and add a random one to the screen when the timeline is empty.

![CleanShot 2023-12-14 at 15 47 10@2x](https://github.com/infinitered/reactotron/assets/1479215/2acc3ea2-b194-46e1-805f-221c8290c10b)

We should also add a link to the Quick Start guide while we're at it.

https://docs.infinite.red/reactotron/quick-start/react-native/

**Comment by markrickert** [comment]
@jamonholmgren Is this still necessary now that the home screen isn't the timeline screen? 

Related: https://github.com/infinitered/reactotron/pull/1393

**Comment by jamonholmgren** [comment]
I think if the timeline is empty it would still be fun, but this isn't critical
