### ISSUE TITLE
404 in README

### ISSUE THREAD

**Issue by jcubic** [infinitered/reactotron#1371]
The links in `How to setup Reactotron in our app` point to 404 pages

**Comment by verhovensky** [comment]
Same for me, the link
https://github.com/infinitered/reactotron/blob/master/docs/plugin-docs/quick-start-react-native.md#installing-reactotronapp

**Comment by frankcalise** [comment]
Are these bookmarked? Or could you provide the link in which these links are on that doc page?

Docs have been reworked to https://docs.infinite.red

Is this what you're looking for @verhovensky https://docs.infinite.red/reactotron/quick-start/react-native/#installing-reactotronapp?

**Comment by jcubic** [comment]
I'm talking about GitHub readme. Maybe this will clarify:

![Peek 2023-12-17 23-06](https://github.com/infinitered/reactotron/assets/280241/e52eab6f-a33a-4819-b922-ebeafdcd6737)

**Comment by frankcalise** [comment]
@jcubic Thanks I see the issue

**Comment by verhovensky** [comment]
@frankcalise
Yes, this is the link I was looking for, thank you!
