### ISSUE TITLE
iOS Release Build app crash on real device

### ISSUE THREAD

**Issue by Ajmal0197** [infinitered/reactotron#1398]
`Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Error: invalid host, js engine: hermes', reason: 'Unhandled JS Exception: Error: invalid host, js engine: hermes`

App crashing in ios release mode.
Refer for detail:
https://github.com/facebook/hermes/issues/1228

**Comment by GSFZamai** [comment]
Same here. In my case only on iOS Release Mode

**Comment by rodrigorethink** [comment]
The problem started to happen in version 5.0.4 of reactotron-react-native. Using version 5.0.3 the crash does not occur.
Comparing the versions, it can be seen that the getHost routine in the file /reactotron-react-native/src/reactotron-react-native.ts uses a simplified version, which works for Expo applications, but in iOS builds in release mode this new version uses the URI of the embedded bundle.

Example:
using the code NativeModules?.SourceCode?.getConstants().scriptURL in release mode you get something like file:///private/var/containers/Bundle/Application/38A07257-A8E8-4565-BBE6-6B874A82A47B/app_name.app /main.jsbundle
The new getHost routine will extract "private" and will try to use it as a host, which generates the "invalid host" exception

**Comment by GSFZamai** [comment]
> Hi @rodrigorethink Iam using reacctotron version 5.0.3 only but still its getting crashed!!

I've downgraded the version and worked for me.
Did you try to remove node_modules and install all again?

**Comment by lachu97** [comment]
Hi @GSFZamai Yes, i have tried it but still in the production the same thing happens...

**Comment by rodrigorethink** [comment]
> Hi @GSFZamai Yes, i have tried it but still in the production the same thing happens...

I had to remove node_modules, clear metro and XCode cache to work locally after downgrade

**Comment by GSFZamai** [comment]
> Hi @GSFZamai Yes, i have tried it but still in the production the same thing happens...

You can try the steps done by @rodrigorethink.

Can also try delete ~/Library/Developer/Xcode/DerivedData.
It Might be some cached build.

Verify your yarn.lock to ensure thet the version installed is really 5.0.3
![image](https://github.com/infinitered/reactotron/assets/47357785/1954aa27-441c-4ba4-a5ed-4cf0e9cf4bce)

**Comment by luanlcampos** [comment]
In my case, I also had to downgrade `reactotron-redux` to version 3.1.3.

**Comment by lachu97** [comment]
Any possible solution, this issue happens only in production mode @GSFZamai

**Comment by GSFZamai** [comment]
> reactotron-redux

Did you try to downgrade reactotron-redux to 3.1.3? That lib also started to crash yesterday after a new release.

If none of the above resolves, one workaround is that you can remove the reactotron config when you need to build for release on iOS.

**Comment by lachu97** [comment]
Hi @GSFZamai I tried removing the entire reactotron code and it works fine in production..
is there any stable version for both the reactotron redux and reactotron  reactnative packages ?

**Comment by mikaelsn** [comment]
Downgrading `reactotron-react-native` to 5.0.3 and removing `host` from the configuration worked for us.

**Comment by TrustDec** [comment]
Change `reactotron-react-native` in package.json to 5.0.3, instead of ^5.0.3, otherwise the actual version of `reactotron-react-native` in node_modules is 5.0.4

**Comment by CaioQuirinoMedeiros** [comment]
Downgrade `reactotron-react-native` to 5.0.3 worked for me too. I cleared node_modules and installed pods again.
I use `host` configuration and didn't have to remove it.
I don't have `reactotron-redux`

**Comment by joshuayoes** [comment]
Reactotron should **not** be loaded in production. Read more about why here.
https://docs.infinite.red/reactotron/tips/#running-in-production

Consider adding [eslint-plugin-reactotron](https://github.com/infinitered/reactotron/tree/master/lib/eslint-plugin-reactotron) to your project to help ensure that any reactotron calls are getting hidden behind a `__DEV__` flag. 

Trouble shooting checklist:
- ensure Reactotron is only loaded behind `__DEV__` flag
- use `require('ReactotronConfig.ts')` instead of `import('ReactotronConfig')` because `import` is hoisted outside of `__DEV__` blocks.

**Comment by filipef101** [comment]
Pretty sure there's an issue, I only have one file that imports reactotron and related packages, with a function that setups reactotron. 

  ```
if (__DEV__) {
    const initTron = require('@utils/initTron');
    initTron();
  }
```

Still get the crash

**Comment by darimuhittinhey** [comment]
Why the issue closed ?

**Comment by johnhamlin** [comment]
After some tinkering and researching other projects, I finally figured out a configuration that's working for me using Redux Toolkit v2:

```TS
// ReactotronConfig.ts
import Reactotron from 'reactotron-react-native';
import { reactotronRedux } from 'reactotron-redux';

const reactotron = Reactotron.configure({ name: '[NAME OF YOUR APP]' })
  .useReactNative()
  .use(reactotronRedux())
  .connect(); 

export default reactotron; 
```

```TS
// store.ts
import { configureStore, EnhancedStore } from '@reduxjs/toolkit';
import { setupListeners } from '@reduxjs/toolkit/query';

export const store = configureStore({
  reducer: {
    [YOUR REDUCERS]
  },
  middleware: getDefaultMiddleware =>
    getDefaultMiddleware().concat([YOUR MIDDLEWARE IF YOU HAVE ANY]),
  // Note: Enhancers have to go after middleware
  **enhancers: getDefaultEnhancers =>
    __DEV__
      ? getDefaultEnhancers().concat(
          require('../ReactotronConfig').default.createEnhancer()
        )
      : getDefaultEnhancers(),**
});

setupListeners(store.dispatch);

export type RootState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;
```

I hope that works for you too! I updated my tsconfig compilerOptions to include `"module": "Node16", "moduleResolution": "Node16", "esModuleInterop": true`, but couldn't get Reactotron to come insto store.ts with a type other than `any`.

**Comment by Ajmal0197** [comment]
✅ 
Closing this issue since below things are working properly, just follow below and then delete nodemodules,lock files, pods etc and reinstall again:

1. Libraries version:
```
    "reactotron-react-native": "5.0.3",
    "reactotron-redux": "3.1.3",
```

2. ReactotronConfig.js
```
import Reactotron, { networking } from 'reactotron-react-native';
import { reactotronRedux } from 'reactotron-redux';
import AsyncStorage from '@react-native-async-storage/async-storage';

Reactotron.configure({ name: 'app_name' })
  .setAsyncStorageHandler(AsyncStorage)
  .useReactNative()
  .use(reactotronRedux()) //  <- here i am!
  .use(networking())
  .connect();

// patch console.log to send log to reactotron
const yeOldeConsoleLog = console.log;
console.log = (...args) => {
  yeOldeConsoleLog(...args);
  Reactotron.display({
    name: 'CONSOLE.LOG',
    value: args,
    preview: args.length > 0 && typeof args[0] === 'string' ? args[0] : null,
  });
};

export default Reactotron;
```

3. store.js
```
import AsyncStorage from '@react-native-async-storage/async-storage';
import { combineReducers, configureStore } from '@reduxjs/toolkit';
import { persistReducer, FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER } from 'redux-persist';
import userSlice from './slices/userSlice';
import nonPersistedSlice from './slices/nonPersistedSlice';

const persistConfig = {
  key: 'root',
  version: 1,
  storage: AsyncStorage,
  blacklist: ['nonPersistedSlice'], // these reduce will not persist data
  whitelist: ['userSlice'], // these reduce will persist data
};
const reducer = combineReducers({
  userSlice,
  nonPersistedSlice,
});
const persistedReducer = persistReducer(persistConfig, reducer);

const getEnhancers = (getDefaultEnhancers) => {
  if (process.env.NODE_ENV === 'development') {
    const reactotron = require('../helpers/ReactotronConfig').default;
    return getDefaultEnhancers().concat(reactotron.createEnhancer());
  }
  return getDefaultEnhancers();
};

const store = configureStore({
  reducer: persistedReducer,
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware({
      serializableCheck: {
        ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER], //
      },
    }),
  enhancers: getEnhancers,
});

export default store;
```

**Comment by pokey** [comment]
I'm a bit confused why this issue is closed if the current workaround is to downgrade reactotron. I'm still seeing this on reactotron-react-native 5.0.5, but downgrading to 5.0.3 fixed it. Is the issue that I'm inadvertently running reactotron on production, and that just accidentally worked until 5.0.4?

**Comment by joshuayoes** [comment]
@pokey the real issue is caused by running Reactotron in production, upgrading to 5.0.5 seemed highlight this issue for some users.

I put together a checklist here for how to ensure that Reactotron is not getting loaded in your app and a helpful linting rule to prevent it in the future: https://github.com/infinitered/reactotron/issues/1398#issuecomment-1899058678

**Comment by phatmovista** [comment]
This is what work for us with the latest version `5.1.3`:

```
import createSagaMiddleware from 'redux-saga';
import { persistStore } from 'redux-persist';
import { configureStore } from '@reduxjs/toolkit';

import rootReducer from './reducers';
import rootSaga from './sagas';

const shouldLoadDebugger = (__DEV__ && !process.env.JEST_WORKER_ID);
const reactotronInstance = shouldLoadDebugger ? require('../reactotron.config').default : null;

// Configure saga and root (combined) reducer, along with Reactotron
const sagaMiddleware = createSagaMiddleware(shouldLoadDebugger ? { sagaMonitor: reactotronInstance.createSagaMonitor() } : {});
const store = configureStore({
    reducer: rootReducer,
    middleware: (getDefaultMiddleware) => getDefaultMiddleware({ serializableCheck: false }).concat([sagaMiddleware]),
    enhancers: shouldLoadDebugger ? [reactotronInstance.createEnhancer()] : [],
});

const persistor = persistStore(store, null);

sagaMiddleware.run(rootSaga);

if (__DEV__ && module.hot) {
    module.hot.accept('./src/reducers', () => store.replaceReducer(rootReducer));
}

export { store, persistor };
```

**Comment by uesleisuptitz** [comment]
> The problem started to happen in version 5.0.4 of reactotron-react-native. Using version 5.0.3 the crash does not occur. Comparing the versions, it can be seen that the getHost routine in the file /reactotron-react-native/src/reactotron-react-native.ts uses a simplified version, which works for Expo applications, but in iOS builds in release mode this new version uses the URI of the embedded bundle.
> 
> Example: using the code NativeModules?.SourceCode?.getConstants().scriptURL in release mode you get something like file:///private/var/containers/Bundle/Application/38A07257-A8E8-4565-BBE6-6B874A82A47B/app_name.app /main.jsbundle The new getHost routine will extract "private" and will try to use it as a host, which generates the "invalid host" exception

YESSSS, 5.0.3 works! THANKS MAN!!!

**Comment by alexsegura** [comment]
Using `require()` is the way. 

I updated the code snippet in the docs. See #1468

**Comment by valkeshpatel** [comment]
@Ajmal0197 

Your solution works. Thank you for saving my day

**Comment by Echelpoel** [comment]
> After some tinkering and researching other projects, I finally figured out a configuration that's working for me using Redux Toolkit v2:
> 
> ```ts
> // ReactotronConfig.ts
> import Reactotron from 'reactotron-react-native';
> import { reactotronRedux } from 'reactotron-redux';
> 
> const reactotron = Reactotron.configure({ name: '[NAME OF YOUR APP]' })
>   .useReactNative()
>   .use(reactotronRedux())
>   .connect(); 
> 
> export default reactotron; 
> ```
> 
> ```ts
> // store.ts
> import { configureStore, EnhancedStore } from '@reduxjs/toolkit';
> import { setupListeners } from '@reduxjs/toolkit/query';
> 
> export const store = configureStore({
>   reducer: {
>     [YOUR REDUCERS]
>   },
>   middleware: getDefaultMiddleware =>
>     getDefaultMiddleware().concat([YOUR MIDDLEWARE IF YOU HAVE ANY]),
>   // Note: Enhancers have to go after middleware
>   enhancers: getDefaultEnhancers =>
>     __DEV__
>       ? getDefaultEnhancers().concat(
>           require('../ReactotronConfig').default.createEnhancer()
>         )
>       : getDefaultEnhancers(),
> });
> 
> setupListeners(store.dispatch);
> 
> export type RootState = ReturnType<typeof store.getState>;
> export type AppDispatch = typeof store.dispatch;
> ```
> 
> I hope that works for you too! I updated my tsconfig compilerOptions to include `"module": "Node16", "moduleResolution": "Node16", "esModuleInterop": true`, but couldn't get Reactotron to come insto store.ts with a type other than `any`.

This works too, and should be changed in the docs imo

**Comment by abhishekjoshi-growthaxl** [comment]
import reactotron configuration in dev mode only like this, worked for me 

```
let reactotronEnhancer = undefined;

if (__DEV__) {
  // Only import and use Reactotron in development
  const reactotron = require('./reactotronConfig').default;
  reactotronEnhancer = reactotron.createEnhancer();
}
```
