### ISSUE TITLE
Reset Root Store

### ISSUE THREAD

**Issue by ElonVolo** [infinitered/reactotron#1402]
I'm using Reactotron 3.1.4 with React Native after a hiatus of a some number of months and when I try to click on the "Reset Root Store" button in the "Custom Commands" area and nothing happens (the button doesn't highlight on press nor is the mobx-state-tree store reset). Likewise, if I go the "State" tab and click on the trashcan icon, essentially the same thing happens.

Is this feature to delete/reset the root store data currently broken?

**Comment by kevinvangelder** [comment]
The Reset Root Store function in reality simply resets AsyncStorage, so you must reload the app to see the effects.
