### ISSUE TITLE
From version reactotron-react-native 5.0.5

### ISSUE THREAD

**Issue by Iuriy-Budnikov** [infinitered/reactotron#1451]
### Describe the bug

I'm getting an error when I run tests via jest in react native. I used an empty react native project with the latest react native.

```
SyntaxError: Cannot use import statement outside a module
```

<img width="1036" alt="Screenshot 2024-03-06 at 06 13 59" src="https://github.com/infinitered/reactotron/assets/3968373/971b8e1c-2bdc-444e-b44a-210a401ee968">

### Reactotron version

5.1.3

**Comment by phatmovista** [comment]
I just installed the new version now and having the same issue as well

**Comment by jonqwerty** [comment]
I have the same issue with  "reactotron-react-native": "^5.1.7".

**Comment by frankcalise** [comment]
Please update to latest and also consult this PR if you're still struggling with Ignite, testing library and reactotron.

This combination works and is documented here: https://github.com/infinitered/ignite/pull/2740
