### ISSUE TITLE
Reactotron is empty when i click the timeline page

### ISSUE THREAD

**Issue by manhhoang02** [infinitered/reactotron#1463]
### Describe the bug

https://github.com/infinitered/reactotron/assets/91677571/cb9c38f9-b0b3-45fc-b458-f32383a64755

ReactotronConfig
![image](https://github.com/infinitered/reactotron/assets/91677571/7ca2f64d-f7cd-43b5-a3ef-9087836b6869)

Please anyone is able to help me with this. Thanks

"react": "18.2.0",
"react-native": "0.71.2",
"@react-native-async-storage/async-storage": "^1.17.11",
"reactotron-react-native": "^5.1.4"

### Reactotron version

3.7.0

**Comment by MCKmecik** [comment]
I was having the same problem on version 3.7.0.
After downgrade to app 2.8.1 problem disappeared.
