### ISSUE TITLE
ImmutableJS Support

### ISSUE THREAD

**Issue by andrewvy** [infinitered/reactotron#18]
This is AMAZING. 😁 

Perhaps we have an `Reactotron.addImmutableReduxStore(store)` alternative of https://github.com/skellock/reactotron/blob/master/client/reactotron/client.js#L84 and I think that should be it? I didn't look entirely too deep yet.

I'll see if I can cobble something together if this is something you want to support. Or I can run a forked version if including ImmutableJS is too much. :)

**Comment by skellock** [comment]
Thank you.  You mean http://facebook.github.io/immutable-js/ ya?

I've tried it with `seamless-immutable`, but not Immutable.js.  Do you see an error when you run it?

**Comment by andrewvy** [comment]
No errors, as paths passed into your `RS` methods will return `null`.

ImmutableJS data structures can only be accessed via `.get` and `.getIn`. I also realize you can possible not need to include the library by checking for those methods and using them instead. :)

**Comment by skellock** [comment]
Ahhhhhhhhh... Totally get what you're saying now.

Thank you.  Ya that should be no problem at all.

**Comment by skellock** [comment]
This is in place now.
