### ISSUE TITLE
Can't get working with redux + RN-router-flux

### ISSUE THREAD

**Issue by ssomnoremac** [infinitered/reactotron#214]
Trying to get reactotron working with RN / react-native-router-flux / Redux 
but only the router events are logged correctly -- all other actions are logged as undefined. Here is what I came up with to set up the app - which works fine.

```
Reactotron.configure().connect()

const reactotronEnhancer = createReactotronEnhancer(Reactotron)
const RouterWithRedux = connect()(Router);
const middleware = [thunk];
const store = compose(reactotronEnhancer, applyMiddleware(...middleware))(createStore)(reducer);

...

 <Provider store={store}>
     <RouterWithRedux>
         <Scene ...
```

**Comment by skellock** [comment]
Heyo.

Hmm... To be honest I haven't seen that way of create a store before.  

Usually what you do is `compose` your enhancers and then call `createStore()` with the result.

https://github.com/reactotron/reactotron/blob/master/packages/demo-react-js/src/Redux/Store.js#L42

Lemme know if that's what you're thinking.  Apologies if I'm misunderstanding what you're asking.

**Comment by skellock** [comment]
Feel free to re-open if you're still stuck.  RNRF is working with Reactotron nicely these days.  Even better in 1.9 tomorrow.
