### ISSUE TITLE
Unable to log object functions

### ISSUE THREAD

**Issue by GantMan** [infinitered/reactotron#219]
```
let a = {b: ()=>'c'}
console.tron.log(a)
```

won't show b

**Comment by skellock** [comment]
The function doesn't serialize.

What would you like it to show?

**Comment by zibs** [comment]
I think displaying anything would be useful - even if it is just logging the presence of the function. I know I've been bit a few times tron-logging objects with functions that don't show up in the logs, causing me to go on a hunt as to why/where they are. I know in Xcode it comes out as `key: [Function]` or what have you. So often when I can't find the function, I'll log the object in Xcode and I can definitively see that the function was there all along. This has me sometimes logging to both Xcode and reactotron, which isn't ideal. 

ps, loving reactotron. It has made developing & debugging react-native a total joy for me.

**Comment by skellock** [comment]
Make sense. I think I've seen that before too ya (now that you mention it).  I think `booleans` are jumping the wire either.

Here's the command that sends it across the wire:

https://github.com/reactotron/reactotron/blob/master/packages/reactotron-core-client/src/index.js#L127

I wonder if perhaps `socket.io` supports serialization options?  I'll follow up on that.

**Comment by rmevans9** [comment]
@skellock any luck finding something on socket.io side? I think the next best option is manually sanitizing the objects as they get passed through but I feel like depending on how large the objects are that could be fairly heavy processing each message.

**Comment by rmevans9** [comment]
Another option might be to do a JSON.stringify on the object before shipping it to Socket IO. Something like this might work:

```
JSON.stringify({ test: function () { } }, function (k, v) { if (typeof v === 'function') { return '[Function]'; } else { return v } });
```

This outputs a stringified json object that replaces functions with "[Function]". Then you would be able to just parse the JSON on the other end.

**Comment by skellock** [comment]
I haven't looked yet, but ya i was considering serializing before socket.io.  sending a plain ol string through is totally fine for socket io.

I was actually toying with the idea of removing Socket.IO altogether.  There's been lots of issues I've had to work around.  And it's the biggest obstacle to me crossing the language barrier too.

**Comment by rmevans9** [comment]
What would you use instead to pipe data out of the app?

**Comment by skellock** [comment]
straight up web sockets.  socket.io is a small protocol on top of that.  which i use zero of the features.  i basically need:   web socket + a string.   That will allow me to play around in Elm and other places.  haha.

**Comment by rmevans9** [comment]
That could simplify things. how long do you think it would take to do that?

**Comment by skellock** [comment]
Not long.  A couple of hours.  The main problem is backwards compatibility.  I was putting this off until version 2, but it would be possible to retrofit two different socket client/servers side-by-side.  Just not ideal.

In the case of a "JSON-preprocessor" though, we could come up with something that in the [send function of the reactotron-client](https://github.com/reactotron/reactotron/blob/master/packages/reactotron-core-client/src/index.js#L127).

This is the 1 and only spot where we encode outbound communication to the Reactotron App.

```js
  send (type, shoddyPayload = {}, important = false) {
    // ... a magical land where we crawl the object tree and look for a better way to represent data
    const payload = sanitize(shoddyPayload)
    this.socket && this.socket.emit('command', { type, payload, important: !!important })
  }
```

Then we have our sanitizer:

```js
import { clone } from 'ramda'

// sanitizer.js
export default (payload = {}) {
  // transform
  const sanity = clone(payload)

  // and return
  return sanity
}
```

**Comment by skellock** [comment]
This is in place now.  2.0 will replace socket.io.
