### ISSUE TITLE
Command line champions

### ISSUE THREAD

**Issue by skellock** [infinitered/reactotron#229]
I'm considering leaving the terminal app behind for the next version (2.x).

I just wanted to get a sense on how people felt about this.

I hate to see it go because this is how Reactotron started.  Also there's a hip factor to the command line.

My problem here is:  In almost every way, the desktop app is a better experience.  It allows you to drill down, toggle things like a tree, copy large things to the clipboard.  And it has lots of hot keys.

There's already some drift in functionality between the console and desktop, and I hadn't heard any complaints so far.

Just trying to figure out a bit of a roadmap here.

👍  = i actively use the desktop app
👎  = i actively use the console app

Comments appreciated as well!

**Comment by GantMan** [comment]
leave the terminal behind.  As cool as it was, you blew past it.  It's `/gif a whole new world`

![awnw](https://68.media.tumblr.com/19e053c1491fcf0b275b9bd39d175f0c/tumblr_neemq1BxD01r9mp00o1_1280.gif)

**Comment by rmevans9** [comment]
I vote let it go away. Especially if you get a binary out there for the app on windows and linux.

**Comment by juddey** [comment]
I started with the terminal app and found that quite difficult to use so in the end just used the adb console to get what I want..

Then the graphical app came out and....

![image](https://cloud.githubusercontent.com/assets/7445602/20280960/737b9f52-ab13-11e6-8f1b-9cabbcc9db93.png)

I haven't left home without it.

**Comment by skellock** [comment]
2.0 will not have the CLI any longer.  Thx!
