### ISSUE TITLE
Auto-update

### ISSUE THREAD

**Issue by rmevans9** [infinitered/reactotron#273]
https://github.com/electron/electron/blob/master/docs/api/auto-updater.md

It would require some infrastructure to host the server (unless there is one out there that will host for free since this is an open source project). I think this could be beneficial as I always find myself questioning if I updated the app with new releases and also its a little bit tedious to manually update it.

**Comment by zalmoxisus** [comment]
You can autoupdate it right from github releases with [`electron-gh-releases`](https://github.com/jenslind/electron-gh-releases). [Here's a n example](https://github.com/zalmoxisus/social-expert/blob/master/src/electron/index.js#L130-L195) of how I implemented it.

**Comment by skellock** [comment]
@zalmoxisus that looks really straight forward, ty!  ill give it go this week.

**Comment by Raathigesh** [comment]
I was recently trying out auto-updates for an app and the built-in auto updater of electron needs a update server. But then finally switched to [electron-updater](https://www.npmjs.com/package/electron-updater) which manages releases through github (also supprorts other mechanisms) and does not require an update server. Just wanted to put the thought here if you guys are looking into implementing the updater.

**Comment by skellock** [comment]
Closing as we're migrating away from electron. 🖖
