### ISSUE TITLE
not possible to copy API call url to the clipboard

### ISSUE THREAD

**Issue by romanlv** [infinitered/reactotron#275]
It will be very useful to be able to copy url for API calls, so I can debug it in the postman.
Just making url text selectable should solve the problem.

There is a feature to copy request/response body but not the url.

**Comment by skellock** [comment]
Nope.  But that's a great suggestion.  Let's get that in.

**Comment by skellock** [comment]
Fixed in 1.9.  Shipping tomorrow.

**Comment by Abandonedengineer** [comment]
I'm currently using Version 3.0.0-beta.9 (3.0.0-beta.9.1040) but I don't see any option to copy url we have the option to convert to cURL but not the api url.
