### ISSUE TITLE
Read source-maps to display exceptions more userfriendly

### ISSUE THREAD

**Issue by reicheltp** [infinitered/reactotron#276]
Currently, if I log an error reactotron just display the plain error object with reference to the error line in source code. Unfortunately, the source is packed and this info is useless for the developer. 

![image](https://cloud.githubusercontent.com/assets/4380869/20578209/7313c33c-b1c6-11e6-91de-70717cdc69bf.png)

It would be super awesome if reactotron loads the corresponding source-maps and displays the real error line. Reactotron could also show the corresponding code-snippet, but this is maybe too much.

**Comment by skellock** [comment]
This case should be supported.  Looks like you're doing React Native Android there.

Checkout https://github.com/reactotron/reactotron/blob/master/docs/plugin-track-global-errors.md

There's a error tracking plugin you'll need to setup in your `ReactotronConfig.js` that should capture this.

What you'll have to do is let that error bubble up unhandled in order for React Native's error handling & sourcemap resolving to kick in.

Having said... it'd be awesome to call their sourcemap resolver on demand!  Like if you're in the catch block and you want to continue normal flow.

**Comment by rmevans9** [comment]
@skellock RE: Call their sourcemap resolve on demand - that is a large part of the code in #278 so we could possibly abstract that logic out a bit and make use of it in more places then just the saga logging.

**Comment by skellock** [comment]
This is all in place now.  :1st_place_medal:
