### ISSUE TITLE
Ability to show normal console.log() statements in Reactotron?

### ISSUE THREAD

**Issue by joncursi** [infinitered/reactotron#298]
This is a feature request for developer convenience.

Is it possible to have Reactotron show `console.log()` statements in the event feed (I'm talking normal `console.log()` statements, without having to first import Reactotron in the file, and then do a special `Reactotron.log()` or `Reactotron.warn()`)? I often want to just quickly log something to a console to figure out what's going on with my data, but I have to import Reactotron first, and then delete that import statement when I'm done, which is more typing and deleting than it's worth to figure out something fast. So I've been opting to continue using the normal Chrome Dev Tools console.

This would be especially useful for React Native folks, because right now we are pretty much tied to the "Debug JS Remotely" option to spit out code snippets to the Chrome Dev Tools console, which is slow, always has to run in the foreground, and overall just a pain in the butt.

If this is possible, I could safely say that I would no longer need the "Debug JS Remotely" option at all in React Native and Reactotron would effectively become my new debug station.

**Comment by rmevans9** [comment]
I am not sure we will be able to catch console.log messages without a little bit of leg work from the dev. A quick and dirty way to do it would be to just do:

`console.log = Reactotron.log`

@skellock any thoughts on making it a bit more transparent to the developer?

**Comment by skellock** [comment]
It's a great request.

Here's my only reservation.

When I created `Reactotron.log()` i made the mistake of not making the API the exact same as `console.log`.

So instead of `console.log(thing, anotherThing, allTheThings)`, [our API](https://github.com/reactotron/reactotron/blob/master/packages/reactotron-core-client/src/plugins/logger.js#L7) is `Reactotron.log(thing, importantFlag)`.

:(

I was planning on changing this interface in `@2.0` (in addition to correct a bunch of my other mistakes).

For now, though, you can do this in your `ReactotronConfig.js`:

```js
// swizzle the old one
const yeOldeConsoleLog = console.log

// make a new one
console.log  = (...args) => {
  // always call the old one, because React Native does magic swizzling too
  yeOldeConsoleLog(...args)

  // send this off to Reactotron.
  Reactotron.display({ 
    name: 'CONSOLE.LOG',
    value: args,
    preview: args.length === 0 && typeof args[0] === 'string' ? args[0] : null
  })
}
```

^^^ Warning: I haven't tried that.  It may actually format your hard drive.  Lemme know if that works for you though!

**Comment by skellock** [comment]
Going to close this up.  An optional plugin would be welcomed though!

**Comment by ferrannp** [comment]
Yup, I have something similar that works ok (I tested it):

```js
const hijackConsole = (browserConsole) => {
  console.log = (...args) => {
    if (isDebuggingInChrome) {
      browserConsole(...args);
    }
    Reactotron.display({
      name: 'CONSOLE.LOG',
      value: args,
      preview: args.length > 1 ? JSON.stringify(args) : args[0]
    })
  };
};

hijackConsole(console.log);
```

**Comment by skellock** [comment]
@ferrannp : curious how you're detecting `isDebuggingInChrome`?

**Comment by ferrannp** [comment]
@skellock I took it from F8 app: https://github.com/fbsamples/f8app/blob/master/js/store/configureStore.js#L37

**Comment by john1jan** [comment]
// Totally hacky, but this allows you to not both importing reactotron-react-native
  // on every file.  This is just DEV mode, so no big deal.
  **console.tron = Reactotron**

**Comment by Ahad-Wasim** [comment]
I got it to work as well. My implementation is listed below:

`
  const nativeLog = console.log;
  console.log = (...args) => {
    // Reactotron.log.apply(null, args);
    Reactotron.display({
      name: 'CONSOLE.LOG',
      important: true,
      value: args,
      preview: args.length > 1 ? JSON.stringify(args) : args[0]
    });
    return nativeLog.apply(null, args);
`

**Comment by sourabhv** [comment]
I prefer @john1jan 's way of doing it

```javascript
console.tron = (...args) => {
  console.log(...args);
  Reactotron.display({
    name: 'TRON',
    value: args,
    preview: args.length > 1 ? JSON.stringify(args) : args[0],
  });
};
```
