### ISSUE TITLE
More Issues With React Native Router Flux

### ISSUE THREAD

**Issue by skellock** [infinitered/reactotron#306]
We seem to be having some issue with React Native Router Flux once it's plugged into redux.

More details here.

https://github.com/infinitered/ignite/issues/537

I'll try to reproduce this.

**Comment by skellock** [comment]
Also, it's possible to ignore these message inside `reactotron-redux`, but I'd love to support `react-native-router-flux` as I've used it on few projects.  Maybe it's time to make a plugin specifically for it?

**Comment by Aleksion** [comment]
I'm facing the same issue. However, adding the following array doesn't seem to do anything:

```
const exceptions = [
    'REACT_NATIVE_ROUTER_FLUX_BACK',
    'REACT_NATIVE_ROUTER_FLUX_BACK_ACTION',
    'REACT_NATIVE_ROUTER_FLUX_FOCUS',
    'REACT_NATIVE_ROUTER_FLUX_JUMP',
    'REACT_NATIVE_ROUTER_FLUX_POP_AND_REPLACE',
    'REACT_NATIVE_ROUTER_FLUX_POP_TO',
    'REACT_NATIVE_ROUTER_FLUX_PUSH',
    'REACT_NATIVE_ROUTER_FLUX_REFRESH',
    'REACT_NATIVE_ROUTER_FLUX_REPLACE',
    'REACT_NATIVE_ROUTER_FLUX_RESET',   
]
```

Per the comment on the issue on ignite, it was said to be added at: 
`reactotronRedux({except: exceptions})`

in `Reactotron.configure().use(reactotronRedux({except: exceptions})).connect()`

But after looking through the Reactotron code it seems it "should" be added in the enhancer: 

`createReactotronEnhancer(reactotron, { except: exceptions })`

Nevertheless. The actions still show up in the timeline, and the error still occurs no matter in which of the two places I add it.

Am I doing it wrong?

**Comment by skellock** [comment]
The former should be correct.  You add it as an option to `reactotronRedux`.

And so the actions still go through?  And the text matches exactly?  Could you post a screen shot of the action as it appears in Reactotron?

Something fishy is up.  Your first code looks correct.

**Comment by skellock** [comment]
1.9 will put to rest a long standing bug with RNRF.  Yay!
