### ISSUE TITLE
Crash on app launch

### ISSUE THREAD

**Issue by ajonno** [infinitered/reactotron#308]
Just installed to our in dev RN project. Getting a crash error on startup seems to be related to socket.io? Screen shot below

```
    "react": "^15.4.1",
    "react-native": "^0.38.1",
....
```

![image](https://cloud.githubusercontent.com/assets/3005269/21202918/8a7588e6-c2a4-11e6-940f-c4cd038eee32.png)

**Comment by skellock** [comment]
Poopy pants.

What version of Reactotron are you using?

**Comment by ajonno** [comment]
haha, like your style! its Version 1.6.0 (1.6.0)

**Comment by skellock** [comment]
1.6.1 is the latest version available for your `package.json` libraries.  I recommend upgrading there.

Are you able to paste your `ReactotronConfig.js` file?  Also, are you using `react-native-router-flux` by any chance?

**Comment by skellock** [comment]
Also, if you scroll to the bottom of that stack trace... do you see anything Reactotron related?  It'll probably be *just* be for you see Socket.IO.

Do you see anything show up at all inside your Reactotron App?   Like "Connected" and such?

**Comment by ajonno** [comment]
checking now..

**Comment by ajonno** [comment]
hmm ive deleted OSX app, clicked on "Download OS X App" again, finished install fine. then open the app and it shows as V 1.6.0.

**Comment by skellock** [comment]
yep.  that app should be 1.6.  But the parts that plug into your `package.json`... what versions do you have for that?

**Comment by ajonno** [comment]
oh sorry my bad. ok so to answer your previous q's:
1. reactotron-redux :  im actually using React Native so have installed "reactotron-react-native": "^1.6.0" into the dev dependencies

2. I've just pasted the file contents into App.js for the time being. For clarity here is my App.js
```
import {
  NavigationContext,
  NavigationProvider,
  StackNavigation,
} from '@exponent/ex-navigation';

import React, { Component } from 'react';
import {
  StyleSheet,
} from 'react-native';
//import codePush from 'react-native-code-push';
import { Provider } from 'react-redux';

import Store from './src/state/Store';
import Router from './src/routing/Router';

import Reactotron from 'reactotron-react-native'
Reactotron
  .configure() // we can use plugins here -- more on this later
  .connect() // let's connect!

const navigationContext = new NavigationContext({
   router: Router,
   store: Store
});

export default class XXXXXX extends Component {
.....
```

3.  react-native-router-flux --  i am not using this, however I am using exponent/ex-navigation (in a "vanilla" React Native app)
```
import {
  NavigationContext,
  NavigationProvider,
  StackNavigation,
} from '@exponent/ex-navigation';
```

**Comment by ajonno** [comment]
lastly, I've also got reactotron-cli installed ; 1.6.0

**Comment by ajonno** [comment]
> "Also, if you scroll to the bottom of that stack trace... do you see anything Reactotron related? It'll probably be just be for you see Socket.IO.
> 
> Do you see anything show up at all inside your Reactotron App? Like "Connected" and suc"
> 

I cant see anything Reactotron related. The error screen is all related to socket.io 

If I do a clean React Native app build (react-native init xxxx) and the install/require Reactotron it works fine. There must be some dependency that's getting in the way in this dev app.

```
 "dependencies": {
    "@exponent/ex-navigation": "^2.1.0",
    "apsl-react-native-button": "^3.0.2",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "email-validator": "^1.0.7",
    "react": "^15.4.1",
    "react-addons-shallow-compare": "15.3.2",
    "react-native": "^0.38.1",
    "react-native-code-push": "^1.15.0-beta",
    "react-native-fbsdk": "^0.4.0",
    "react-native-firestack": "2.3.2",
    "react-native-keyboard-aware-scroll-view": "^0.2.4",
    "react-native-linear-gradient": "^1.5.15",
    "react-native-lock": "^0.4.0",
    "react-native-modal-dropdown": "^0.4.0",
    "react-native-oauth": "^2.0.1",
    "react-native-popup-dialog": "^0.3.14",
    "react-native-tab-view": "0.0.40",
    "react-redux": "^4.4.6",
    "redux": "^3.6.0",
    "redux-thunk": "^2.1.0"
  },
  "devDependencies": {
    "eslint-config-rallycoding": "^3.1.0",
    "reactotron-react-native": "^1.6.0"
  }
```

**Comment by skellock** [comment]
Ah.  This is Exponent.  I've not tried this platform yet.  As far as I know, it thought it should be compatible.

They do lock some stuff down though.  Like the ability to talk to HTTP.  By default that's what Reactotron uses to communicate from your device or sim back to your computer that's running your app.

What you have there is really the simplest it can be.  If that's not working, I'd say, it's not supported.

I'll look closer into Exponent support.  

Sorry for the problems.

**Comment by ajonno** [comment]
ok no worries i understand. if u have time might be a good box to tick so others using Exponent RN components can use Reactotron.

**Comment by rmevans9** [comment]
@skellock @ajonno this is actually ex-navigation specifically right? Not actually the full exponent setup? If so, I use ex-navigation with Reactotron without issue.

Looking at the socket.io code it looks like it is failing because the namespaces variable which is passed in on some sort of `enable` function is not null but also not a string (maybe an object? or a function?) I would be interested if you could remote debug the app that is failing with Reactotron, go into the node_modules and put a breakpoint on the line in socket.io.js (under the socket.io-client npm package) within the enable function (line 609 in my install but may be slightly different depending on versions. Once done - what is namespaces? That might give a better hind at what is going on. Also what is your callstack like there?

It would be fantastic if we could repro this in a simple app to dig into it a bit more.

**Comment by ajonno** [comment]
yes correct im not using Exponent framework, just ex-navigation.

ok sure sounds like a good idea. ill have to park this till EOD now but i will definitely do it, and post back here. im based in sydney fyi.  appreciate your help with this.

**Comment by rmevans9** [comment]
I look forward to it!

**Comment by skellock** [comment]
Feel free to re-open this if you are stuck.  Side note... Exponent works great!  Tried it last night.
