### ISSUE TITLE
Identify multiple clients in app

### ISSUE THREAD

**Issue by Aleksion** [infinitered/reactotron#322]
While it's possible to identify clients by name on Connection, I can't figure out (if it's even possible) to identify it on individual action dispatches. I'm developing a react-native app simultaneously on Android and IOS, but following which subscription belongs to which client etc. is fairly hard currently.

Am I missing something?

**Comment by skellock** [comment]
This isn't supported at the moment.

On the server side of things, we'd have to establish the concept of a session.

Then we'd have to segment the UI some how too.  Multiple windows?  Tabs?

It'd be a big change, but certainly possible to do.  It's something that I kicked myself after realizing it was too late.  😸 

So, all commands get dispatched to all clients.  As you can attest to, this makes little-to-no-sense.

Sorry!

**Comment by Aleksion** [comment]
Ha ha, Well at least I can stop looking for it then :)
I hope you get to come back to this one day

Thanks!

**Comment by skellock** [comment]
I'd like to.  This would be the key to multi-device scripting & remote control.  Scripting is something I've been wanting to add for a while.

**Comment by skellock** [comment]
I'll put this on the roadmap.. but won't be happening for the 2.x release.
