### ISSUE TITLE
JSON scrubbing is causing performance issues

### ISSUE THREAD

**Issue by samcorcos** [infinitered/reactotron#324]
When receiving a large JSON object from a network request (128kb) with nested values, the event loop is hung for about 15 seconds.

<img width="722" alt="screen shot 2017-01-22 at 12 24 40 pm" src="https://cloud.githubusercontent.com/assets/2626231/22185615/e0186766-e09d-11e6-911f-c832d6b012f6.png">

When Reactotron is disabled, the performance issues go away. I also found that when I set `safeRecursion` to `false`, it also worked fine:

```js
Reactotron
  .configure({ safeRecursion: false, })
  .use(reactotronRedux())
  .connect()
```

Fortunately, my project does not have an [open socket](https://github.com/infinitered/reactotron/blob/afa90903862a10b13743f21282ba47c9c2364f44/packages/reactotron-core-client/src/index.js#L135), so serialization isn't a problem.

Just thought I'd post this issue here in case someone else is having the same issue... It took me a long time to figure out what was going on.

**Comment by skellock** [comment]
Thanks for reporting in.  Appreciate it!  Are you on React Native?

Is it a lot of properties?  A lot of nesting?  I'd love to find a fast serialization method and put this to rest.

**Comment by samcorcos** [comment]
@skellock Yes, using React Native.

[Here's the data](https://gist.github.com/samcorcos/ffec3e595ebc0af77757691aaac48293)

It seems like Reactotron has trouble dealing with it in the logs and in the state subscription.

**Comment by skellock** [comment]
That's great man, thank you for sharing this.  That scrubbing function evaluates every single property and figures out of they are circular references in addition giving friendly names to functions.  I'll look at optimizing.

**Comment by hilkeheremans** [comment]
Same here on RN. Thanks for digging into this @samcorcos.

**Comment by skellock** [comment]
1.9 will have some improvements in the serialization.  In 2.0, I've removed `socket.io` entirely which means, i don't have to do a serialize/deserialize/serialize dance.  No cloning happens either, so they're no huge allocations.

Thanks guys.  Glad to put this one to rest.
