### ISSUE TITLE
Disable in release build React-Native

### ISSUE THREAD

**Issue by Amurmurmur** [infinitered/reactotron#326]
Currently doing the following to try to disable it in the release builds:

Here is my creatStore:
```
import { createStore, applyMiddleware, compose, combineReducers } from 'redux'
import reduxThunkMiddleware from 'redux-thunk'
import reducers from '@reducers/'
import createReactotronEnhancer from '@lib/Reactotron'

const enhancer = compose(
  applyMiddleware(
    reduxThunkMiddleware,
  ),
  createReactotronEnhancer()
)

export default function configureStore(initialState) {
  const store = createStore(
    reducers,
    initialState,
    enhancer
  );
  return store
}
```

Here is my Reactotron config:
```
import Reactotron from 'reactotron-react-native'
import createReactotronTrackingEnhancer from 'reactotron-redux'
import apisaucePlugin from 'reactotron-apisauce'

Reactotron
.configure()
.use(apisaucePlugin())
.connect({
  enabled: __DEV__,
})

export default function createReactotronEnhancer(){
    return createReactotronTrackingEnhancer(Reactotron);
}
```

However the app still connects to reactotron even in release build of react-native app.

I would be very thankful if somebody can clear this up for me and give an advice on how to not enable reactotron in release builds.

Thank you in advance 👍

**Comment by skellock** [comment]
You can separate the `.connect()` call onto a new line and wrap an if statement around it.

`if (__DEV__) Reactotron.connect()`

**Comment by grundmanise** [comment]
@skellock Thanks for such a usefull app! I've installed `reactotron` as a `--dev` dependency (and use it with redux). Should I still wrap my `reactotron` code in `if (__DEV__)` ? Then wouldn't it be better to just wrap the whole config?

```
if (__DEV_) {
Reactotron
.configure()
.use(apisaucePlugin())
.connect();
}
```

**Comment by skellock** [comment]
@grundmanise Let's bring this conversation over here:  https://github.com/infinitered/reactotron/issues/433  Thanks!
