### ISSUE TITLE
Getting a shrug emoji for GET response ?!

### ISSUE THREAD

**Issue by Eyesonly88** [infinitered/reactotron#327]
Hi 👋 . I upgraded my project to use React Native 0.40 (which also upgraded React to `15.4.2`). After that, all api requests using `apisauce` are giving me a shrug emoji :man_shrugging: :rofl: 👎 
Note that all the requests i'm making are HTTPS and I have added the necessary key in my plist like this:
```
<key>NSAppTransportSecurity</key>
    <dict>
      <key>NSAllowsArbitraryLoads</key>
      <true/>
      <key>NSExceptionDomains</key>
      <dict>
        <key>localhost</key>
        <dict>
          <key>NSExceptionAllowsInsecureHTTPLoads</key>
          <true/>
        </dict>
      </dict>
    </dict>
```
Shrug error:

![image](https://cloud.githubusercontent.com/assets/767013/22459856/215701c2-e807-11e6-90aa-e610f4acf004.png)

Doing the same api request in a browser works fine (returns expected JSON).
Any help would be appreciated as I'm stuck with no info/stack trace on where the problem is 😢

**Comment by skellock** [comment]
You won't need to make an NSAppTransportSecurity entry for HTTPS, so it's not that.

The shrug means null.  If the URL is fine in the browser, then have a look at your request headers.  Is there something missing in your app that is in your browser?

**Comment by jamonholmgren** [comment]
@skellock We might consider just outputting `null`. I was actually quite confused by the shrug when I first used Reactotron too. Not as fun, but... ¯\_(ツ)_/¯

**Comment by skellock** [comment]
Ha! Yes, sadly I agree. Feel free to open another ticket.

**Comment by Eyesonly88** [comment]
I'm still trying to figure out the problem 😭. 
Yes, provide as much debugging info as possible please 👍 
I love your tool because it makes it easier to debug in most cases while also being easy to use.

**Comment by GantMan** [comment]
you can have shrug when you pry it from my cold dead JavaScript infested hands.

**Comment by GantMan** [comment]
RE: @Eyesonly88 - are you testing for a failed API with a catch block?

**Comment by skellock** [comment]
@Eyesonly88 Are you able to test this same API call in Postman?  Does it work there?  You're not getting a status code at all in a response, but yet it's taking 859 ms... Is the server yours?  Can you see anything in the log files?

**Comment by skellock** [comment]
Mr Shruggy is going away.  I'm now passing `~~~ undefined ~~~` for undefined on the client.  I'll sweep through and remove that character.

RIP.
