### ISSUE TITLE
RN - Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by Lxxyx** [infinitered/reactotron#337]
![image](https://cloud.githubusercontent.com/assets/13161470/22853059/76d05dd8-f086-11e6-8bb7-25e5cf49c46f.png)

RN Version: 0.41.2
Reactotron: 0.17.0
OS: MacOS 10.12.3 (16D32)

Bug: I use [react-native-router-flux](https://github.com/aksonov/react-native-router-flux) as my App router. And When click return. App has crashed and give me an error.

![image](https://cloud.githubusercontent.com/assets/13161470/22853071/e29024e0-f086-11e6-901e-f9bfe2ff2931.png)

**Comment by Lxxyx** [comment]
Use https://github.com/infinitered/ignite/issues/537 Method fix my problem.

**Comment by skellock** [comment]
Fixed in 1.9 shipping tomorrow.
