### ISSUE TITLE
Ability to select/copy event timeline entries

### ISSUE THREAD

**Issue by davidjb** [infinitered/reactotron#339]
It would be great to be able to select and/or copy to the clipboard log entries in the event timeline.  Aside from being helpful in general, being able to log a value/structure/etc with Reactotron and copy out the data for inspection (eg into another editor or program) would be extremely helpful.

Using Reactotron 1.7.0 on Mac.

**Comment by skellock** [comment]
Agreed.

What are you thinking?  Export as JSON?

**Comment by davidjb** [comment]
Open to suggestion -- I thought something like a 'copy to clipboard' icon next to each entry + ability to select part of an entry's text would be most convenient + flexible.  

I'd be happy just to copy an individual entry's content as text -- I'm logging different file formats as text strings (as well as objects in JSON) like this:

![screen shot 2017-02-24 at 23 43 44](https://cloud.githubusercontent.com/assets/1002811/23305570/2e9533b2-faeb-11e6-9be5-11cb4d66c1b3.png)

**Comment by skellock** [comment]
What?  Just type it back out!  😜 

Ya, not being able to select text is pain in the butt.  I'll queue that one up.

Thx man.

**Comment by davidjb** [comment]
Heh, yep, I considered OCR'ing for a bit too.  Thanks for the super-quick response, Reactotron is awesome.

**Comment by skellock** [comment]
This is shipping now in 1.8.
