### ISSUE TITLE
React Native Windows SocketException

### ISSUE THREAD

**Issue by kevinvangelder** [infinitered/reactotron#343]
> I'd like to share, that continuously throwing "SocketException" is connected with Reactotron. When it's not running BlueJeans cannot connect and throws exceptions. Running Reactotron or running Release build removes the exception.

The exception is thrown in the background and does not interfere with our application, but seeing them in the logs caused some concern that there might be something wrong with our app.

**Comment by skellock** [comment]
I guess this is socket.io going crazy trying to reconnect?

Is it a JS stack trace do you know?

**Comment by kevinvangelder** [comment]
It's showing up in the Visual Studio output so I think it's a native exception (possibly something with how we've implemented the WebSocket module). I would guess you are probably correct that it's trying to reconnect.

**Comment by skellock** [comment]
Heyo.  You can now turn reconnects off if you like.  Hope that solves the problem.  Lemme know if it was something else.

This will be going out in 1.9 which will be tomorrow.
