### ISSUE TITLE
Apisauce Monitor doesn't play well with Blobs

### ISSUE THREAD

**Issue by andreiconstantinescu** [infinitered/reactotron#344]
So... the problem is this.

I have a proxy server which fetches some content (10 images) and sends them to the FE as buffers in an array. When the FE gets teh response, it create the Blobs to render them on the page and it takes around 5-6s for the page to load completely. 
If I pull out the apisauce monitor, everything works as expected, as soon as the request gets a response on the FE it creates the Blobs and renders the images in ~1s.

Any idea how to fix this?

Thanks.

**Comment by skellock** [comment]
Sounds like we will have to skip the output if the response type is image/*.

Should be possible to do.

**Comment by skellock** [comment]
Thx dude.  Sorry about that.  We're skipping images now.  It's now [configurable with a regex](https://github.com/infinitered/reactotron/blob/master/packages/reactotron-apisauce/src/index.js#L14) in the `apisauce` plugin if you need to target custom `content-type`s.

**Comment by skellock** [comment]
Shipping shortly.

**Comment by andreiconstantinescu** [comment]
Awesome news! Thank you @skellock for fixing this! :)
