### ISSUE TITLE
Unable to build on windows

### ISSUE THREAD

**Issue by dotnetprofessional** [infinitered/reactotron#347]
I tried to build from source and am getting the following errors. I've tried from GitBash shell as well as a command line. It results in the same issue:

Lerna v2.0.0-beta.37
Bootstrapping 12 packages
Preinstalling packages
Installing external dependencies
Symlinking packages and binaries
Postinstalling packages
Prepublishing packages
Successfully bootstrapped 12 packages.

> @ build D:\dev\git.Public\reactotron
> lerna run build --scope 'reactotron-core-*' --scope 'reactotron-redux*' --scop                                                       e 'reactotron-apisauce' --scope 'reactotron-react-native' --scope 'reactotron-re                                                       act-js' --scope 'reactotron-cli'

Lerna v2.0.0-beta.37
Scoping to packages that match ''reactotron-core-*','reactotron-redux*','reactot                                                       ron-apisauce','reactotron-react-native','reactotron-react-js','reactotron-cli''
Errored while collecting packages and package graph
Error: No packages found that match ''reactotron-core-*','reactotron-redux*','re                                                       actotron-apisauce','reactotron-react-native','reactotron-react-js','reactotron-c                                                       li''
    at Function._filterPackages (D:\dev\git.public\reactotron\node_modules\lerna                                                       \lib\PackageUtilities.js:195:15)
    at Function.filterPackages (D:\dev\git.public\reactotron\node_modules\lerna\                                                       lib\PackageUtilities.js:166:37)
    at RunCommand.runPreparations (D:\dev\git.public\reactotron\node_modules\ler                                                       na\lib\Command.js:170:60)
    at RunCommand.run (D:\dev\git.public\reactotron\node_modules\lerna\lib\Comma                                                       nd.js:97:12)
    at Object.<anonymous> (D:\dev\git.public\reactotron\node_modules\lerna\bin\l                                                       erna.js:70:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8                                                       6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! @ build: `lerna run build --scope 'reactotron-core-*' --scope 'reactotr                                                       on-redux*' --scope 'reactotron-apisauce' --scope 'reactotron-react-native' --sco                                                       pe 'reactotron-react-js' --scope 'reactotron-cli'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script 'lerna run build --scope 'reactotron-core-                                                       *' --scope 'reactotron-redux*' --scope 'reactotron-apisauce' --scope 'reactotron                                                       -react-native' --scope 'reactotron-react-js' --scope 'reactotron-cli''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lerna run build --scope 'reactotron-core-*' --scope 'reactotron-red                                                       ux*' --scope 'reactotron-apisauce' --scope 'reactotron-react-native' --scope 're                                                       actotron-react-js' --scope 'reactotron-cli'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\dev\git.Public\reactotron\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8                                                       6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "welcome"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! @ welcome: `npm run clean && npm run bootstrap && npm run build && npm                                                        run copy-internal-deps && npm run lint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ welcome script 'npm run clean && npm run bootstrap && n                                                       pm run build && npm run copy-internal-deps && npm run lint'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && npm run bootstrap && npm run build && npm run copy                                                       -internal-deps && npm run lint
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\dev\git.Public\reactotron\npm-debug.log

**Comment by skellock** [comment]
I've had some trouble building on Windows.   Try running them one at a time.  I'm wondering which one is causing grief.

It almost looks like there's some weird spaces in there causing problems?  that might be just copy & pasting from a console though.

**Comment by dotnetprofessional** [comment]
OK so I discovered that the apostrophe's are causing an issue ie
it should be 
```
"build": "lerna run build --scope reactotron-core-* --scope reactotron-redux* --scope reactotron-apisauce --scope reactotron-react-native --scope reactotron-react-js --scope reactotron-cli",

```

However I now get the following error:

```
> reactotron-react-native@1.7.0 build D:\dev\git.public\reactotron\packages\reactotron-react-native
> rollup -c


NpmUtilities.execInDir        ("run build", [], "D:\\dev\\git.public\\reactotron\\packages\\reactotron-cli")
Error: Command failed: npm run build
Warning: Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval
src\commands\state\stateDispatchPrompt.js (13:6)
11:     // try not to blow up the frame
12:     try {
13:       eval('action = ' + value); // eslint-disable-line
          ^
14:     } catch (e) {}

'mv' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! reactotron-cli@1.7.0 build: `rollup -c && mv dist/index.js dist/index.js.tmp && echo '#!/usr/bin/env node
npm ERR! ' > ./dist/index.js && cat dist/index.js.tmp >> ./dist/index.js && chmod +x ./dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactotron-cli@1.7.0 build script 'rollup -c && mv dist/index.js dist/index.js.tmp && echo '#!/usr/bin/env node
npm ERR! ' > ./dist/index.js && cat dist/index.js.tmp >> ./dist/index.js && chmod +x ./dist/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the reactotron-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rollup -c && mv dist/index.js dist/index.js.tmp && echo '#!/usr/bin/env node
npm ERR! ' > ./dist/index.js && cat dist/index.js.tmp >> ./dist/index.js && chmod +x ./dist/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs reactotron-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls reactotron-cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\dev\git.public\reactotron\packages\reactotron-cli\npm-debug.log

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

> reactotron-cli@1.7.0 build D:\dev\git.public\reactotron\packages\reactotron-cli
> rollup -c && mv dist/index.js dist/index.js.tmp && echo '#!/usr/bin/env node
' > ./dist/index.js && cat dist/index.js.tmp >> ./dist/index.js && chmod +x ./dist/index.js


NpmUtilities.runScriptInDir   ("build", [], "D:\\dev\\git.public\\reactotron\\packages\\reactotron-cli")
Error: Command failed: npm run build
Warning: Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval
src\commands\state\stateDispatchPrompt.js (13:6)
11:     // try not to blow up the frame
12:     try {
13:       eval('action = ' + value); // eslint-disable-line
          ^
14:     } catch (e) {}

'mv' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! reactotron-cli@1.7.0 build: `rollup -c && mv dist/index.js dist/index.js.tmp && echo '#!/usr/bin/env node
npm ERR! ' > ./dist/index.js && cat dist/index.js.tmp >> ./dist/index.js && chmod +x ./dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactotron-cli@1.7.0 build script 'rollup -c && mv dist/index.js dist/index.js.tmp && echo '#!/usr/bin/env node
npm ERR! ' > ./dist/index.js && cat dist/index.js.tmp >> ./dist/index.js && chmod +x ./dist/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the reactotron-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rollup -c && mv dist/index.js dist/index.js.tmp && echo '#!/usr/bin/env node
npm ERR! ' > ./dist/index.js && cat dist/index.js.tmp >> ./dist/index.js && chmod +x ./dist/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs reactotron-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls reactotron-cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\dev\git.public\reactotron\packages\reactotron-cli\npm-debug.log

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

> reactotron-cli@1.7.0 build D:\dev\git.public\reactotron\packages\reactotron-cli
> rollup -c && mv dist/index.js dist/index.js.tmp && echo '#!/usr/bin/env node
' > ./dist/index.js && cat dist/index.js.tmp >> ./dist/index.js && chmod +x ./dist/index.js```

**Comment by skellock** [comment]
TBH I don't think i'm going to support building on Windows.  I just don't use it day to day.  I'm not familiar with all the tricks one has to do to install the right stuff. 

I'm able to make windows builds from the mac.

I would welcome a PR if anyone figures it out.
