### ISSUE TITLE
Unable to access margins at overlay screen

### ISSUE THREAD

**Issue by pahanini** [infinitered/reactotron#357]
At 13,3-inch (2560 x 1600) unable to access to margins at overlay screen (scroll is not working)

<img width="596" alt="screen shot 2017-03-10 at 13 32 35 copy" src="https://cloud.githubusercontent.com/assets/898663/23788070/c61cbc5e-0596-11e7-9ed2-a9ed7e58ebb2.png">

**Comment by skellock** [comment]
Thx for the report.  Will be pushing this out tomorrow.
