### ISSUE TITLE
Feature Request: display code surrounding loc in index.ios.bundle to show the root cause

### ISSUE THREAD

**Issue by Eyesonly88** [infinitered/reactotron#381]
Let me start by saying, I _love_ using Reactotron 😍  💯 .

Sometimes we get errors when upgrading RN or when using 3rd party libraries and those errors are quite vague such as this one:

![image](https://cloud.githubusercontent.com/assets/767013/24068245/b47c49ca-0bee-11e7-88f4-00faf6bda7b5.png)

The cause for the error above was my own code throwing a `Error` object but as you can see the code shown doesn't actually show the root cause.

The only way to find the problem is to do a GET request to load the generated bundle `http://localhost:8081/index.ios.bundle` and going to that line `48250` reveals my stupid code throwing an `Error` 👎 😭 .

Reactotron already knows this information since that's what RN is reporting. So my feature request is to actually load the dynamically generated bundle and display that line number with surrounding code instead of just displaying what RN is showing.

What do you think 👍  or 👎 ?

**Comment by rmevans9** [comment]
I agree - I think reactotron can do a better job symbolcating RN errors. I am going to take a cruise around what this might look like.

**Comment by rmevans9** [comment]
Looking into this a bit - it ends up with that stack trace only if you have remote debugging on - in which case it actually shows the error twice in Reactotron. Once with a "good" stacktrace and once with this one. Can you confirm if you:

1. Had remote debugging on
2. Have more then one error reported when this crash occurs?

**Comment by Eyesonly88** [comment]
Thanks for digging into this.

1. Nope, I don't think I had debugging on.
2. My code was throwing a `new Error(msg)`. There were no other errors.

Hmm, in my case, Reactotron didn't show error twice 😕 (only got the bad one).

Have you tried reproducing with throwing an error `new Error(msg)` in your code?

**Comment by skellock** [comment]
Sorry, I missed this issue.

I seem to remember (no source, perhaps it was only a dream??) someone saying something about a handler you could hook globally for promise rejections.  In your example here, there isn't one.  Maybe we could write a plugin to install one?

Or maybe I'm smoking crack?

I feel like this should be doable.  (not the crack part).

**Comment by Eyesonly88** [comment]
@skellock ye that would be cool too. 

Point me in the right direction and I'm keen to contribute. 

I ❤️  Reactotron 😍  🎧

**Comment by skellock** [comment]
Looks like http://2ality.com/2016/04/unhandled-rejections.html could work?  I haven't tried it.

If you do give it a shot lemme know if you need some help wrapping it up in a plugin.

**Comment by skellock** [comment]
#646
