### ISSUE TITLE
[react-native] API responses don't show when 'Debug JS Remotely' is on

### ISSUE THREAD

**Issue by prithsharma** [infinitered/reactotron#385]
Is this expected according to the information present [here](https://github.com/infinitered/reactotron/blob/master/docs/troubleshooting.md#turn-off-remote-js-debugging)?
The troubleshooting docs mention this as a problem with RN Android but I am seeing it in iOS.

**Comment by skellock** [comment]
I don't often turn Debug JS Remotely on.  You're saying it doesn't work on iOS either?   I used to work on both many moons ago.  I wonder if it's an easy fix?

**Comment by prithsharma** [comment]
I am saying I saw this behavior on iOS(the doc link that I shared gives a heads up similar to this but only for Android). 
I really like redux-logger and using chrome breakpoints, so was looking for a way to run both together.

**Comment by skellock** [comment]
I'd love for these to work together too.

**Comment by rmevans9** [comment]
I just tested this on the latest stable and it appears that API requests do come in even when remote debugging. I am going to close this as it appears this might have been fixed somewhere along the way. If you continue to see the issue please feel free to reopen
