### ISSUE TITLE
createStore is not a function (redux)

### ISSUE THREAD

**Issue by danieljvdm** [infinitered/reactotron#389]
I'm trying the following code:

```
const store = Reactotron.createStore(reducers, compose(applyMiddleware(ReduxPromise, thunk, createLogger())))

import Reactotron from 'reactotron-react-js'

const store = Reactotron.createStore(reducers, compose(applyMiddleware(ReduxPromise, thunk, createLogger())))

export default class App extends Component {
  render() {
    return (
      <Provider store={store}>
        <Router history={browserHistory} routes={routes} />
      </Provider>
    )
  }
}
```

And I get this error: `Uncaught TypeError: _reactotronReactJs2.default.createStore is not a function`

The weird thing is that Reactrotron seems to log my initial redux actions

**Comment by danieljvdm** [comment]
Solved by https://github.com/infinitered/reactotron/issues/289

**Comment by juanpasolano** [comment]
Im having the same issue with 

    "react": "15.5.4",
    "reactotron-react-js": "1.11.1",
    "reactotron-redux": "1.11.1"

**Comment by damien-mcmahon** [comment]
I was having the same issue, if you're using ReactNative, make sure your `ReactotronConfig.js` looks like this:
```
Reactotron.
  .configure()
  .useReactNative()
  .use(reactotronRedux())
  .connect()
```

The docs for the `ReactotronRedux` plugin show config for a standard React app.
