### ISSUE TITLE
Docs for using the CLI?

### ISSUE THREAD

**Issue by bstro** [infinitered/reactotron#390]
I'd like to use the CLI but can't find any documentation or instructions for installing and using it.

**Comment by bstro** [comment]
ah, the command to run it is `reactotron`, but i was trying `reactotron-cli` :)

**Comment by skellock** [comment]
Ya, we'll be deprecating the CLI at version 2.0.  Not enough interest and we're able to visualize things much better in the desktop app.

Which of course makes me sad when people show up asking about it.  😆

**Comment by bstro** [comment]
That's too bad, the CLI is very useful when working from VSCode or other editors with an integrated terminal.

The app is nice too tho :)
