### ISSUE TITLE
Redux Test with Reactotron Enabled ?

### ISSUE THREAD

**Issue by ashik94vc** [infinitered/reactotron#397]
Hey, I tried to write test cases for redux actions where the store is created using reactotron's `createStore()` method. This throws this error: 
`TypeError: _reactotronReactNative2.default.createStore is not a function`. Is there any workaround to solve this, without reverting to default `createStore()` method ?

**Comment by skellock** [comment]
Can you show me the full error and the code causing it?

**Comment by skellock** [comment]
Hard to know what's going on here. If `createStore` isn't a function on `Reactotron`, it sounds like the `ReactotronConfig.js` is not being run?  More details about your project would help.

**Comment by ashik94vc** [comment]
Yeah, the app runs fine. The error only occurs when I try to run test case. The test case is nothing but an unit test to test the redux action.

**Comment by skellock** [comment]
Perhaps there are some `__DEV__` guards around and `global.__DEV__` isn't set to true?  Do you have a test setup script that runs?

**Comment by ashik94vc** [comment]
This is how I am configuring my reactotron. 

```jsx
import Reactotron,{ trackGlobalErrors } from 'reactotron-react-native';
import { reactotronRedux } from 'reactotron-redux';
import apisaucePlugin from 'reactotron-apisauce';

Reactotron
  .configure({host: '192.168.1.168'})
  .use(reactotronRedux())
  .use(apisaucePlugin())
  .use(trackGlobalErrors())
  .connect();

console.tron = Reactotron;
```
This is my test script
```jsx
import * as actions from '../index';
describe('actions',() => {
    it('should validate credentials',()=>{
        const domain = "http://www.example.com/";
        const username = "alice";
        const email = "alice@example.com";
        const token = "mock_token";
        const expectedAction = {
            type: actions.VALIDATE_CREDENTIALS,
            domain,
            username,
            email,
            token
        };
        expect(actions.validateCredentials(domain,username,email,token)).toEqual(expectedAction)
    })
});
```

This passes when I create a store in redux like this: `createStore(reducer, applyMiddleware(thunk));` but fails when I create a store like this : `Reactotron.createStore(reducer, applyMiddleware(thunk))`

**Comment by skellock** [comment]
Gotcha, seems like you should be mocking Reactotron.  It won't be able to run in your testing environment because that runs in Node.js and not your simulator.  Reactotron relies on React Native and that environment is not available in test land.

Your test seems to be testing an action creator directly, which is great.  Where are you loading a redux store that's causing that test to fail?

**Comment by ashik94vc** [comment]
Oh!! My bad, The test suit calls the store from my store config file. Is there anyway to stop this ?

**Comment by skellock** [comment]
I'm not sure what your tests look like other than the script you added above.

I'd recommend trying to find that test or test setup script that loads it, and remove the line that calls the store.

For unit testing you want to shrink the surface area as much as possible.  In the case of your test above, that seems perfect.  You're testing your action creator.  You won't need Reactotron, React Native, or even redux loaded to make that happen.

**Comment by ashik94vc** [comment]
I don't have any other startup scripts. This is the only test script for the action creator I wrote. I can make the test pass by creating the store vanilla style. Also, the store is called in my API Wrapper which I have imported in action creators too. I am just looking for another way to run tests without modifying the code as removing the reference to store in my code could cause trivial issues.

**Comment by skellock** [comment]
Ahh.. i think things are a bit tightly coupled here.  For example, I don't think your API should know about the store.

As far as I can see, the clean way out here is to break apart your code a bit, so things are a little loosly coupled.

If that's not an option (time, complexity, other priorities) -- no problem, I'd recommend you going down the route of mocking.  I use `mockery` for file-based mocking.  `sinon` would work well if you're able to pass in your `store` dependency to your action creators (or wherever they're called).

Question, you're using `redux-thunk` right?  That's why you have API calls in your action creators?

**Comment by ashik94vc** [comment]
Yup, I was pretty much reluctant to even call the store in the API. I had no other option as the only way to access the data stored in redux-store was to call the store again in the api. Yeah, I am using `redux-thunk`. I haven't tried with creating a mock store.

**Comment by skellock** [comment]
So, this side-effect management is where `redux-saga` shines.  It decouples things beautifully.  There's a bit of learning curve, so don't feel obligated to switch, just have a look sometime.

So using `mockery` might be the way forward here.

**Comment by ashik94vc** [comment]
Okay. So quick question. Should I mock api or my action creators wrapper. ?

**Comment by ashik94vc** [comment]
Fine, solved it. Didn't use mockery though. Created a manual jest mock and replaced the mock where the store is created. Thanks for all the leads.

**Comment by skellock** [comment]
Sweet!

**Comment by newswim** [comment]
@ashik94vc, do you mind sharing that mock script? I'm running into the same issue

**Comment by ashik94vc** [comment]
@newswim You'll find the mock script below. Just create a ___mocks___ folder and create a file with the same name as the file where you create the store and add this. It should take care.

```javascript
import configureMockStore from 'redux-mock-store';
import thunk from 'redux-thunk';

const mockStore = configureMockStore([thunk]);

const store = mockStore({login: {
    domain: 'api.example.com',
    username: 'admin',
    token: 'mock_token'
}});
export default store;
```
