### ISSUE TITLE
Failed to show window 1.9.0

### ISSUE THREAD

**Issue by GantMan** [infinitered/reactotron#398]
![image](https://cloud.githubusercontent.com/assets/997157/25136325/53a3760c-241a-11e7-9633-9882bd8799a3.png)

### Steps to recreate:
1. open reactotron on mac
2. Click `x` at top left
![image](https://cloud.githubusercontent.com/assets/997157/25136396/7b140e9a-241a-11e7-8f9e-cd4773183bb6.png)
3. Click Reactotron icon at bottom (should that still be there?)
![image](https://cloud.githubusercontent.com/assets/997157/25136447/98e10ffe-241a-11e7-8c47-9a9a93fb3c99.png)
4. Try to show reactotron by clicking the one option inside view
![image](https://cloud.githubusercontent.com/assets/997157/25136483/ae400b98-241a-11e7-97f7-747f0aac8912.png)

**Comment by skellock** [comment]
The app running but window gone is a common idiom of mac apps.  One I don't agree with =).  Even Apple themselves are a bit confused nowadays. (e.g. AppStore autocloses).

I'd be happy to remove this.

The toggle full screen is a straight up bug.  It has a handle to the window which is gone.

**Comment by GantMan** [comment]
just need a way to bring window back to existing, or have it actually close.

**Comment by skellock** [comment]
Right.  I'm saying I agree.  😆

**Comment by GantMan** [comment]
lol, I'm an idiot when I'm in a meeting. I came off strange, but yes, I was thinking I'll take either way.

Idea 1:  Keep it the way it is, but have a way to bring the window back.
Idea 2: Kill it with fire on close!

**Comment by skellock** [comment]
In my opinion, close the last window, kill the the app.  This isn't a document-based app.

https://github.com/infinitered/reactotron/blob/master/packages/reactotron-app/main.development.js#L41 would become `app.quit()`.

**Comment by GantMan** [comment]
Can I do the PR!?  Even though I have no idea how to run/test it?  Also, you'll have to wait for me to have stable internet in Amsterdam

**Comment by skellock** [comment]
Already in the process of knocking this one out.  You can grab a more complicated one though when you come home.

**Comment by skellock** [comment]
(only because i'm cleaning up a bunch of other crap in that file)

**Comment by skellock** [comment]
Fixed by #403
