### ISSUE TITLE
useReactNative is not a function

### ISSUE THREAD

**Issue by seanmadi** [infinitered/reactotron#402]
I am getting the following error when using the few lines from the quick start for React native. Any idea what I may be doing wrong?

![image](https://cloud.githubusercontent.com/assets/576752/25181019/1ab820f8-24de-11e7-804d-3d32e5198fa7.png)

```import Reactotron from 'reactotron-react-native'

Reactotron
  .configure() // controls connection & communication settings
  .useReactNative() // add all built-in react native plugins
  .connect() // let's connect!```

**Comment by skellock** [comment]
Oops.  That'll be in the next version I'll release.  I shouldn't have committed that doc change to master just yet.

You'll want something closer to this (until 1.10 comes ships).

```js

import Reactotron, {
  trackGlobalErrors,
  openInEditor,
  overlay,
  asyncStorage,
  networking
} from 'reactotron-react-native'

  Reactotron
    .configure({
      name: 'React Native Demo'
    })
  .use(trackGlobalErrors())
  .use(openInEditor())
  .use(overlay())
  .use(asyncStorage())
  .use(networking())
  .connect()
```

**Comment by seanmadi** [comment]
That worked. Thanks for being so fast!

**Comment by skellock** [comment]
I answer quick to the bugs that are most embarrassing.
