### ISSUE TITLE
Sending saga effect tree to reactotron is very slow.

### ISSUE THREAD

**Issue by gillessed** [infinitered/reactotron#416]
We just upgrade reactotron-redux-saga to 1.10.0 and we noticed a huge performance decrease, where sagas were taking multiple seconds to run, where they normally take microseconds. It looks like the culprit is #376. Could you add a flag to disable that feature or something along those lines?

**Comment by kevinvangelder** [comment]
Ouch, good point. Shipping the entire state tree is likely going to be expensive in most cases so it should probably be an opt-in feature.

**Comment by skellock** [comment]
Hey @gillessed, sorry for problems here.

I tested the shipping of the entire tree and it didn't seem too bad (read: i had a contrived test and not real-world data).

We can add a way to configure this for sure.

Is it that you have a lot of data flowing thru the sagas?  I've recently overhauled the serialization and I wanted to rule that out as being the problem.

I suspect what you're saying is true though.

**Comment by rpmonteiro** [comment]
Same problem here. A lot of API requests go through the sagas, so a lot of data is flowing. One of those was usually taking 200ms, but with the sagaMonitor on, it takes around 10 seconds.. eh eh

**Comment by rmevans9** [comment]
I will be getting a PR in either today or tomorrow to remove the sending of the saga state tree. The use case that it was put in for is going to be thought about some more to figure out a better way to do the shipping of the information.

**Comment by skellock** [comment]
We just shipped [1.11](https://github.com/infinitered/reactotron/releases/tag/v1.11.0) tonight which should help.  Please re-open if this doesn't help.

**Comment by rpmonteiro** [comment]
It's working great now! Thanks a lot for your effort! 😃 👍
