### ISSUE TITLE
App throws error with empty `console.tron.display()`

### ISSUE THREAD

**Issue by codeithuman** [infinitered/reactotron#418]
I found that leaving `console.tron.display()` in my code causes the app to throw an error. However `console.tron.display({})` does not throw an error. 

I left `console.tron.display()` in a saga, which made it take a few minutes to find. Just thought I'd mention it here as a nice to have.

**Comment by skellock** [comment]
Oops!  Thank you @codeithuman .

https://github.com/infinitered/reactotron/blob/master/packages/reactotron-core-client/src/index.js#L160

I'm destructuring in the function arguments.  Clever code strikes again.

:(
