### ISSUE TITLE
Have you any plans to implement theming?

### ISSUE THREAD

**Issue by danilovich** [infinitered/reactotron#423]
Have you any plans to implement theming? At least the light theme? It would be very cool!

**Comment by skellock** [comment]
I did [build parts of it](https://github.com/infinitered/reactotron/blob/master/packages/reactotron-app/App/Theme/Colors.js#L39-L47), but never released it fully.

I could do a light theme sure.  It's pretty heavy looking isn't it?  :rofl: 

![image](https://cloud.githubusercontent.com/assets/68273/25856690/c73220f6-34a4-11e7-8b05-f0fe8dcc3fde.png)

We'll be doing a GUI update shortly, so I'll keep that in mind.  In the meantime, lemme see what I can do to enable these things without adding too much customizations.

**Comment by osricwong** [comment]
hi, @skellock 
if i'm using Windows x64 version and v1.6.8, how could i change the theme ?
because i change it into
`const defaultTheme = 'greenscreen'`
and restart the program, its theme still not change :sweat_smile:

**Comment by skellock** [comment]
You would have to rebuild the app, unless you are changing it in the compiled source some how. :)

**Comment by skellock** [comment]
Closing for now. When we implement 2.0 I’ll make sure we have a light theme.

**Comment by ManhVuAmela** [comment]
@skellock Can I change the theme in the config.json file, I want to use the light theme?
