### ISSUE TITLE
console.tron "tip" is error-prone

### ISSUE THREAD

**Issue by danikenan** [infinitered/reactotron#425]
Your "tip" recommends declaring
```console.tron = Reactotron```

Then calling
```console.tron.log('Sweet Freedom!')```

But we (and I think so should everybody) do not import nor configure Reactotron in non `__DEV__` environments. This means that `console.tron` is not available at all (and/or `Reactotron`). 

In this case the result of calling 

```console.tron.log('RED BOX')``` is a red box, certainly not 'Sweet Freedom!'

**Comment by skellock** [comment]
Mocking an interface to console.tron can help here, but I recommend not leaving log statement in.

I'm with you in wanting to leave it out in production builds though.

**Comment by danikenan** [comment]
Leaving `console.log` might not be 'nice', but leaving `console.tron`causes a crash.

Also, even when using transformers like `babel-plugin-console-log`, you do not get automatic support for `console.tron.*` removal. At best you need to use a configurable plugin and configure it manually.

I think the least you need to do is to mention this right next to the 'tip'.

**Comment by skellock** [comment]
Thanks.  And ya, you're right.  I will update the docs.

I wonder if `babel-plugin-transform-remove-console` would help here?  I'll give that a shot.

**Comment by skellock** [comment]
Thanks for the good conversation.  Moving this over to  https://github.com/infinitered/reactotron/issues/433 to try to get a solution in place.
