### ISSUE TITLE
use Reactotron in debug mode，UI can't response when run 5 mins

### ISSUE THREAD

**Issue by wx1985113** [infinitered/reactotron#426]
it's a common issue in the debug mode,when i use setInterval to invoke a redux request,just like:
setInterval(() => {
      this.props.requestUserPoints('matchId', 'lat', 'lng')
    }, 1000)
then in the sagas ：
export function* requestUserPoints(api, action) {
   console.log('requestUserPoints')
}
i do nothing in the function* requestUserPoints, after 5 minutes,App‘s UI can't response any touch event，
but it's ok when i install a release App package。
then ,i disable the Reactotron in the DebugConfig.js:
useReactotron: false
it's ok!
i want you to fix this issue anyway！

**Comment by skellock** [comment]
Thanks for the report.  You're invoking a saga every second which is sending information round trip to Reactotron.

Sounds like there's a memory leak of some sort that is causing Reactotron to lockup over time.

I'll see if I can reproduce things on my end.

**Comment by skellock** [comment]
Haven't been able to reproduce this.  More details are welcome here.
