### ISSUE TITLE
Log 0 (Zero) results in ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by Fenwil** [infinitered/reactotron#428]
If you do `console.tron.log(0)` will log `¯\_(ツ)_/¯`

And that's not what I want. Is there a way to modify this behavior ?

But I'm more than sure that it does that to any `falsy value`

Thanks!

**Comment by RyszardRzepa** [comment]
same me, it logs to console, only strings

**Comment by skellock** [comment]
Ya it sucks... falsy is getting owned by `JSON.stringify`.  Getting the serialization just right has been a challenge.

It's a balance between correctness (both values and circular reference unwrapping) and performance.  

Serialization happens [here](https://github.com/infinitered/reactotron/blob/master/packages/reactotron-core-client/src/serialize.js) and [here](https://github.com/infinitered/reactotron/blob/master/packages/reactotron-core-client/src/index.js#L145).

You can also opt out of the extra "safe" serialization checks by saying `{ safeRecursion: false }` in the `configure()` call to Reactotron (probably in your `ReactotronConfig.js`.

I'm going to be taking a closer look at some 3rd party libraries for serialization once we remove `socket.io` in version 2.

Sorry for the issue!

**Comment by skellock** [comment]
Should be fixed in [the latest 1.11](https://github.com/infinitered/reactotron/releases/tag/v1.11.0) release.

Give that a go if you don't mind!  Feel free to re-open if i'm lying to you.

**Comment by Fenwil** [comment]
Thanks @skellock , here's a screenshot:

![screen shot 2017-05-24 at 10 53 15](https://cloud.githubusercontent.com/assets/2475912/26406643/45d31c32-406f-11e7-8341-cb75dbb95e93.png)

**Comment by skellock** [comment]
@Fenwil : Ugh you're right, I missed this case.

As a workaround for now, `console.tron.log({ zero })`

I need to remove the fallbacks [from here](https://github.com/infinitered/reactotron/blob/master/packages/reactotron-core-client/src/plugins/logger.js#L10).  

I'll get a patch up shortly.  Thx man.

**Comment by Fenwil** [comment]
You're welcome, thank you!

**Comment by skellock** [comment]
Fix is now live in 1.11.1.  That's a lot of 1's.
