### ISSUE TITLE
Breaks AsyncStorage's interface

### ISSUE THREAD

**Issue by thebigredgeek** [infinitered/reactotron#430]
It appears that adding Reactron causes AsyncStorage `removeItem` and `setItem` to return `null` rather than returning a `Promise`.  This was incredibly difficult to track down.

https://github.com/infinitered/reactotron/blob/754dfdaa51fba5d00faa204adc7b1f6564112e4b/packages/reactotron-react-native/src/plugins/async-storage.js#L72

**Comment by skellock** [comment]
Good find!  Did you fix it on your end?  Is it just matter for returning that value?

Thx!

**Comment by thebigredgeek** [comment]
No I haven't.  I think it's just a missing return

**Comment by rmevans9** [comment]
Crap sorry about that - the docs all say it returns nothing so I just skipped over the return on it.

ref: http://facebook.github.io/react-native/releases/0.44/docs/asyncstorage.html#asyncstorage

**Comment by thebigredgeek** [comment]
` Each method in the API returns a Promise object.` ;)

**Comment by rmevans9** [comment]
Well that's confusing given that the API definition below indicates null ha. This is a simple fix, I'll see about fixing this us probably Monday

**Comment by thebigredgeek** [comment]
Well, if you use `await`, the variable that is assigned to is the result of the resolving Promise returned from the function (or, if not a Promise, the immediately returned value).  I think in the `getItem` example below the above line, the variable is `null` because the Promise resolves to `null` because no value was found in `AsyncStorage`

**Comment by rmevans9** [comment]
https://github.com/infinitered/reactotron/pull/434 should resolve this
