### ISSUE TITLE
Production builds in React Native

### ISSUE THREAD

**Issue by skellock** [infinitered/reactotron#433]
Seems to be a topic with a lot of questions around this, so I'd love to track this here.

### Problem

What do we do with Reactotron and production builds in React Native?

Currently we're recommending people install as a `devDependency`.  If you then use `import Reactotron from 'reactotron-react-native'`, with only the production dependencies, it breaks.

This is complicated a bit due to how require statements work in React Native's packager.  This environment is not webpack, cjs, or node.  This is haste.  So the normal tricks like using if statements and `require` are not available.  Haste preprocesses your JS files with an AST looking for `require` calls and doesn't take into account dead code paths like `if (0)`.

So what do we do?

### Solution: Make it a `dependency`

Move it to a `dependency` and never call `connect()`.

* 👍  You can test in production!
* 💩  An extra 150KB of dependencies that aren't used.  Blech.
* 💩  If you ship with `connect()` on, Apple will not let you in the AppStore.

### Solution: Comment it out

Use `//` to comment out Reactotron.

* 💩  Manual step.
* 💩  Doesn't play well with CI.
* 💩  If you write scripts to strip this, well, you have to do work. Let's not cause work for people.

### Solution: Babel Transforms

This seems like it should be the right way.

* 👍  Use these things ([this](https://github.com/uditalias/babel-plugin-remove-imports) | [this](https://github.com/dleitee/babel-plugin-transform-remove-import) | [this](https://github.com/babel/babili/tree/master/packages/babel-plugin-transform-remove-console)) or similar to transform out the code!
* 💩  I've never done something like this before.  Halp!

Anyone else have comments or suggestions?

**Comment by grundmanise** [comment]
@skellock Using [this ](https://github.com/uditalias/babel-plugin-remove-imports) with wrapping  `reactotron` code inside `if (__DEV__)` seems legit, but I would like to hear other opinions too. Will `react-native/packager` remove dead code, e.g. if (false) {} statements in production?

**Comment by skellock** [comment]
No, not as I understand it.  It just won't execute it.  So runtime-safe, but not compile-time safe (if that makes any sense).  We'd still need to have `reactotron-react-native` and friends as a `dependency`.

**Comment by grundmanise** [comment]
It seems that it should eliminate dead code: https://github.com/facebook/react-native/issues/462

**Comment by skellock** [comment]
If this works, then things just got much easier.  =)

**Comment by jamonholmgren** [comment]
Yes, I like the dead code elimination thing much better.

**Comment by grundmanise** [comment]
Has anyone tried it already?

**Comment by skellock** [comment]
I haven't yet.

**Comment by skellock** [comment]
Ok, so I took a run at this tonight.

I think it's just a matter of trying to identify all the scenarios of people using Reactotron and then strip them out.  The goal is to have people not change anything about their codebase and let this plugin do the heavy lifting.

https://github.com/infinitered/babel-plugin-ignite-ignore-reactotron

I started with an `ignite`-based plugin because it's a great test-bed and I've never created a babel plugin before.

Feedback welcome.

**Comment by grundmanise** [comment]
@skellock Thanks! Will definitely try your plugin at some point. But now I am using this shell script to remove all `Reactotron` references from my code:

```
rm ./src/utils/reactotronConfig.js
find ./src -type f -name "*.js" -exec sed -i '' -e "s/console.tron.log/console.log/g;s/import Reactotron from 'reactotron-react-native';//g;s/return Reactotron.createStore(rootReducer, initialState, applyMiddleware(thunk));//g" '{}' \;
find . -maxdepth 1 -type f -name "index.*.js" -exec sed -i '' -e "s/import '.\\/src\\/utils\\/reactotronConfig';//g" '{}' \; 
```

1. detelete `reactotronConfig.js`
2. change all `console.tron.log` to `console.log` (later I'll use babel "transform-remove-console" to delete all `console.log`)
3. detelete `import Reactotron from 'reactotron-react-native';`
4. detelete `return Reactotron.createStore(rootReducer, initialState, applyMiddleware(thunk));`
5. detelete `import './src/utils/reactotronConfig';`

Maybe it is not the best script, but it does it's job for me :)

**Comment by kevinjalbert** [comment]
This is what I'm using (planning to at least, as I haven't gotten around to doing a full test):

```
# src/state/config.js
/* eslint-disable import/no-extraneous-dependencies */
/* eslint-disable import/no-mutable-exports */
/* eslint-disable global-require */

import { compose as reduxCompose, createStore as reduxCreatStore } from 'redux';

let Reactotron = null;
let reactotronRedux = null;
let composeWithDevTools = null;

if (!__DEV__) {
  require('reactotron-react-native');
  Reactotron = require('reactotron-react-native').default;
  reactotronRedux = require('reactotron-redux').reactotronRedux;
  composeWithDevTools = require('remote-redux-devtools').composeWithDevTools;
}

let compose = reduxCompose;
let createStore = reduxCreatStore;

console.log('outside DEV');
if (!__DEV__) {
  console.log('inside DEV');
  Reactotron.configure()
    .useReactNative()
    .use(reactotronRedux())
    .connect();

  compose = composeWithDevTools;
  createStore = Reactotron.createStore;
}

export { compose, createStore };
```

Then in my `src/state/store.js` I can simply use:

```
import { createStore, compose } from './config';
```

Which should pull the correct set of `compose` and `createStore`.

**Comment by jamonholmgren** [comment]
Ooh, that's a good idea @kevinjalbert !

**Comment by fabriziomoscon** [comment]
Thank you @kevinjalbert for your code snippet!
But I think you meant `if (__DEV__) {}` not `if (!__DEV__) {}` or am I missing something?
I am using 
```
"reactotron-react-native": "^1.12.1",
"reactotron-redux": "^1.12.0"
```
and this configuration for me is the only way to solve #289  (`createStore is not a function`)

**Comment by kevinjalbert** [comment]
@fabriziomoscon good catch! Those extra `!` was for when I was testing it locally in development haha. I've updated the code snippet.

**Comment by ohtangza** [comment]
Minor issue, for `/* eslint-disable global-require */` part, I think only applying it on the necessary line with `// eslint-disalbe-line global-require` looks better for me.

**Comment by henrikra** [comment]
@skellock Can you check my PR for that babel plugin? :) I can post more PRs too :)

**Comment by skellock** [comment]
Merged in @henrikra . Thx.

**Comment by skellock** [comment]
I’m going to close this up now that we have a Babel transform.

**Comment by henrikra** [comment]
@skellock I think you should mention this babel plugin in the readme :D

**Comment by skellock** [comment]
I was holding off until people tried it.  Seems to be working well though.

**Comment by fahadhaq** [comment]
thanks @skellock. The plug in worked for.

**Comment by afilp** [comment]
Hi, so do I really need to do this?

```
if (__DEV__) {
    require('../configs/reactotronConfig.js');
}
```

Or this is OK (you strip it during build phase)?
```
import '../configs/reactotronConfig.js'
```

**Comment by henrikra** [comment]
Yes if you use `ignite-ignore-reactotron` babel plugin

**Comment by afilp** [comment]
@henrikra Thanks! By the way, where is this documented? May I assume that the app breaks if I kept it with just the import? (in 'release')

**Comment by skellock** [comment]
You can use `__DEV__` guards and the `react-native` packager will not include those files.  This is important because it's a dev dependency.

`babel-plugin-ignite-ignore-reactotron` is undocumented because it's kinda experimental.  I haven't heard from anyone if they're using it successfully or not.  It worked for my ignite-based projects tho.  =)

**Comment by henrikra** [comment]
@skellock We have used the babel plugin to remove reactotron from the code and our app is in the App store :) So I can vouche for it

**Comment by ivansnek** [comment]
@skellock currently `babel-plugin-ignite-ignore-reactotron` only works for Ignite based app? or is there any chance I can use it in a non Ignite based app?

**Comment by skellock** [comment]
It is possible.  Full disclosure, I did have some issues with it on a non-ignite project.  You'll find this out pretty quickly if you do a production build and it crashes immediately.  =)  But for ignite stuff it works well.

Also, if you just put `__DEV__` guards in front of everytime you use it, the `metro` bundler won't actually package up the `reactotron-*` dependencies.  =)

**Comment by henrikra** [comment]
We have non Ignite project and we are using that babel plugin and our app is in app store :)

**Comment by efleurine** [comment]
I confirm that plugin work fine for me too. @henrikra @ivansnek @skellock 

here my .babelrc
```
{
  "presets": ["react-native"],
  "plugins": ["transform-decorators-legacy"],
  "env": {
    "production": {
      "plugins": [
        "transform-remove-console",
        "ignite-ignore-reactotron"
      ]
    }
  }
}
```

**Comment by marcfielding1** [comment]
What I did just take make things is while I was testing my app was...(In ReactotronConfig.js)

```
if (Config.useReactotron) {

  // EXISTING CODE 

  // Totally hacky, but this allows you to not both importing reactotron-react-native
  // on every file.  This is just DEV mode, so no big deal.
  console.tron = Reactotron
} else { // ADDED AN ELSE
  
  console.tron = console.log
}

```

Voila, obviously later on I can go through and strip out the tron stuff when it's actually released!
