### ISSUE TITLE
How do I view the current Redux store?

### ISSUE THREAD

**Issue by marsonmao** [infinitered/reactotron#445]
When I take a snap shot of Redux store, there is a prompt to let me rename it, after that the entry is in the list, however I read nothing but the name of it, shouldn't it be expandable to view the details of the store or something? What I can do is the rename it again or delete it, what is going wrong?

And, my project is created by `ignite new` so everything is setup pretty good.

Please see the attached image for the UI.

Running on Windows 7 with downloaded portable version.

![tron](https://cloud.githubusercontent.com/assets/5304782/26488166/e2affbb2-4234-11e7-974e-f782a96ff2d5.PNG)

**Comment by marsonmao** [comment]
Oh I think I finally found how to use it...
One should subscribe the slice of store to view it; do this in the 2nd tab "Redux Subscriptions".
When adding subscription, enter empty string for viewing the entire store.
If one wants to view `store.foo` the add `foo` to the subscription.
Anyway...are these rules written in the document?

**Comment by GantMan** [comment]
I kind of like the idea of an icon with an eye on it, which will give you the ability to see what that store looks like.

I plan on doing a video of "How to use Reactotron" and I'll be sure to elaborate on this.

**Comment by skellock** [comment]
Ya, I think we can make the UI a bit better for sure.

Thanks for the feedback.  It helps hearing where people get confused.

**Comment by marsonmao** [comment]
I see, or should I edit the doc and send a PR? I can provide some screenshots and instructions. I mean [this one](https://github.com/infinitered/reactotron/blob/master/docs/plugin-redux.md).

**Comment by kevinvangelder** [comment]
If you're just looking for the current state, you can see that by adding subscriptions under the Redux Subscriptions tab.
