### ISSUE TITLE
State Diff

### ISSUE THREAD

**Issue by jemmyphan** [infinitered/reactotron#446]
does reactotron have an ability to diff state after reducer triggered? 
<img width="263" alt="screen shot 2017-05-29 at 12 05 02 pm" src="https://cloud.githubusercontent.com/assets/7644274/26537155/25ec3970-4467-11e7-980e-02d6711f30f8.png">

**Comment by skellock** [comment]
Not as nice looking as that.

When you add a subscription to an object (press `command + n` then type the key path and press `enter`), anytime that it changes, it'll show you a delta in a `SUBSCRIPTIONS` message on the Timeline.
