### ISSUE TITLE
Save Redux Subscriptions for next session

### ISSUE THREAD

**Issue by sherwinWatson** [infinitered/reactotron#449]
<img width="721" alt="screen shot 2017-05-30 at 1 13 44 pm" src="https://cloud.githubusercontent.com/assets/18283056/26570599/a57bf476-453b-11e7-9392-e4639dc5f3c0.png">

Does reactotron could in any way save and load list of subscriptions that have been added?

**Comment by skellock** [comment]
It doesn't. Good suggestion. Kinda ties in with #421.

**Comment by rdewolff** [comment]
I'd love to have this as well!

**Comment by skellock** [comment]
Closing and moving to #421
