### ISSUE TITLE
Relay integration

### ISSUE THREAD

**Issue by Fandekasp** [infinitered/reactotron#451]
Hi,

I used reactotron a year ago with redux, and liked it quite a lot. Now, I'm starting a project with Relay and was wondering how difficult would it be to add Relay integration to Reactotron.

Can you consider adding this feature?
Cordially

**Comment by skellock** [comment]
I haven't tried relay. I'm not sure how it works.

Are you looking to track the requests to/from the server?

**Comment by Fandekasp** [comment]
I just got started as well. I was trying to install tools to make requests and state changes more transparent (to easily see what components got reloaded after a prop change, what mutations are completed etc). 
If you haven't tried relay, can't be helped. Maybe I'll be able to contribute at some point if it makes sense and if I find the time...

**Comment by skellock** [comment]
Going to close this up for now.  PRs would be welcome for sure!
