### ISSUE TITLE
I have no idea how to print my Redux Store 

### ISSUE THREAD

**Issue by hsavit1** [infinitered/reactotron#456]
How can i see my Redux store / state?  the guide really isn't clear on this. I can't see it in my Reactotron Timeline. All I see are ACTIONs and API RESPONSEs

**Comment by hsavit1** [comment]
There is something in the gif on the main README that looks like you're able to bring up some state tree. How do I do this? ME SO CONFUSED

**Comment by hsavit1** [comment]
This image 

https://github.com/infinitered/reactotron/blob/master/docs/images/quick-start-react-native/react-demo-native-reactotron.jpg

**Comment by skellock** [comment]
Command-F to bring up the find dialog.  tab to toggle between keys & values.  enter to search.

Or Command-N to track changes.

**Comment by hsavit1** [comment]
Awesome! You should for sure add this to the top of the Docs page
