### ISSUE TITLE
Warning with timer on React Native

### ISSUE THREAD

**Issue by Fenwil** [infinitered/reactotron#458]
I'm having this warning coming up when using `reactotron` on React Native but I'm not quiet sure if is because of it.

![screen shot 2017-06-14 at 10 41 14](https://user-images.githubusercontent.com/2475912/27135262-75ce8720-50ee-11e7-9e43-b9813457b434.png)

**Comment by skellock** [comment]
Grab the latest [reactotron app](https://github.com/infinitered/reactotron/releases/tag/v1.11.2).  Does it go away?

This is a new warning they added in React Native on Android.  We got caught by it because the websocket library we're using (socket.io) is using long running timers.  =)

**Comment by Fenwil** [comment]
Great. Thanks @skellock I was using the `reactotron` desktop version `1.10.0` (old). But it seems that homebrew never let me know that there was an update running `brew update/upgrade` I had to run `brew reinstalll reactotron`.

<img width="1096" alt="screen shot 2017-06-14 at 10 52 15" src="https://user-images.githubusercontent.com/2475912/27135690-8f0e7bf4-50ef-11e7-9ab3-4e543dd42131.png">

Great! I'm not having any more the warning. Thanks again 😄

**Comment by skellock** [comment]
Sweet!

**Comment by raynor85** [comment]
Please guys update the link in the documentation, as it is still pointing at the old app which still have the issue (at least the macOs version).
https://github.com/infinitered/reactotron/blob/master/docs/installing.md
