### ISSUE TITLE
CLI App line lengths wrong

### ISSUE THREAD

**Issue by sambanks** [infinitered/reactotron#465]
Hi There

I've just started using this tool and it is amazing! One issue I am having though, is that the border lines of the boxes don't stay straight. I have attached a picture.

I am using Ubuntu 17.04 and this happens in any terminal I install
I am using the default version (reactotron-cli@1.7.0) installed by npm

Thanks
Sam
![screenshot from 2017-06-25 15-58-52](https://user-images.githubusercontent.com/3905846/27513997-996c95e4-59bf-11e7-904f-84ead9e52873.png)

**Comment by skellock** [comment]
Hi Sam,

We’ve moved away from the cli and are using the desktop app now. There’s just so much more we can do to visualize the information.  I will admit the CLI version was cool and that decision was hard.

It looks as if the icons are messing with the line rendering. That lightbulb is a Unicode character made up of 2 code points which the blessed JS library is measuring the string length longer than what your CLI is rendering.  Womp womp.

We have a Linux version available for the desktop app.  Give that a go.

Hope you’re having a good weekend.

**Comment by sambanks** [comment]
Thanks for letting me know Steve

I actually tried the desktop one first and found the cli much more useful, being a mouse dodging vim/tmux junkie.
