### ISSUE TITLE
Timeline+Snapshot Import/Export

### ISSUE THREAD

**Issue by kevinvangelder** [infinitered/reactotron#469]
It would be nice if Reactotron could support import/export of both the timeline and current Redux store.

**Comment by skellock** [comment]
## Exporting the timeline

Currently when we receive a message, it goes into a queue.  We could also direct these to go to a structure log file quite easily as these are JSON messages.

## Exporting the redux store

We have much of the mechanisms in place for this already.  We can subscribe to the root of the store and it'll receive the whole thing.  We'd just have to decide on a JSON format (just the wrapper) and the UI for saving this file.

## Importing the timeline

Some kind of dialog to choose the file, and then we can load them up into the queues.  Fairly straight forward to implement.  The only gotcha I can think of is:  the internals assume you're connected.  So for example, let's say 1 log entry was an action.  There are buttons on that action that allow you to replay.  If you're not connected, then hilarity will ensue.

So perhaps we need the notion of "read-only" or "offline" mode to prevent these calls.

## Importing the redux store

I think this would make a lot of sense to store on the redux tab.  This would allow you to see that state.  We'd need a button to press to load the external state.

## Other thoughts

Almost sounds like we need an alternative mode.  Playback.  Replay.  Readonly.  Something like that.

I'd like to hear more about the use cases.  Are we talking about a dev recording a bug?  In this case, they're running reactotron themselves... maybe they can click a button to go into "replay capture mode" where they go step by step thru the process of identifying a bug.... then come back and hit "done".   

This becomes "incident" file (better name needed) where they can ship to another person.

Can we chat more in person?
