### ISSUE TITLE
Reactotron App Plugin Proposal

### ISSUE THREAD

**Issue by rmevans9** [infinitered/reactotron#479]
# Reactotron App Plugin Discussion

There are a few ways that I can think of for introducing plugins into the Reactotron app so I wanted to start documenting them while I am thinking through them. Please ask any questions, provide feedback, rip apart my thoughts as you see fit.

## Things to consider before even going down this path

- This would be specific to the Reactotron app. This could cause issues for any 3rd party integrations (ref: https://github.com/infinitered/reactotron/issues/455)

## Things that might need to change

- Plugins will need to have entry points into the app (more detailed below)
- We will need to work out how to make the styling of the app work with the plugins that provide UI so the app looks seamless.
- Ideally we will show/hide plugins based upon what connected clients use.
- I think that almost everything should be pulled out to a plugin except for the timeline. This would mean pulling out all of the React Native specific things, Redux, Redux Saga, etc. Ultimately this could make the core app much more approachable for possible contributors

## Plugin Entrypoints

- Filtering out commands in `SessionStore` - https://github.com/infinitered/reactotron/blob/master/packages/reactotron-app/App/Stores/SessionStore.js#L39
- Add an icon onto the nav bar & putting the screen in place when the nav bar has that icon selected - https://github.com/infinitered/reactotron/blob/master/packages/reactotron-app/App/Foundation/Sidebar.js#L47
- Add command components for visual display of commands on the timeline - https://github.com/infinitered/reactotron/blob/master/packages/reactotron-app/App/Commands/index.js#L18
- Add commands to the filter dialog - https://github.com/infinitered/reactotron/blob/master/packages/reactotron-app/App/Dialogs/FilterTimelineDialog.js#L13
- (maybe) key binds and putting key binds and showing them in the help screen - https://github.com/infinitered/reactotron/blob/master/packages/reactotron-app/App/Dialogs/HelpDialog.js#L109 && https://github.com/infinitered/reactotron/blob/master/packages/reactotron-app/App/Stores/UiStore.js#L59

## Possible complications while implementing

- If we allow plugins to hook into key binds we could end up with conflicting key binds.
- Same thing goes for command types - plugins could, in theory, conflict with each other.
- Added complexity to Reactotron setup - You now have to install the app, install any plugins into the Reactotron app that you want/need, install Reactotron client into your application, wire up all plugins you want. This does technically add only one more step but that will likely impact some users decisions on using Reactotron. NOTE: Future ideas could overcome this pain point. I will avoid bringing them into this discussion for now as this is meant to see what it would take to make plugins feasible before trying to make the process of installing them easier.

## Proposed Plan

- [ ] Setup basic system for loading plugins from an array of directories
- [ ] Remove logic for a specific function in Reactotron and start building a plugin with the same functionality. NOTE: Need to decide which function would be best for the test bed for the plugin system - Redux, Redux Saga or the React Native specific features?
- [ ] During development of the function being pulled out of the core Reactotron functionality iterate on a structure for plugins to find the best API for plugins and begin implementing it in Reactotron
- [ ] Stretch Goal - During development convert Reactotron app over to TypeScript with good typing (and ship a Plugin API Typing)

**Comment by rmevans9** [comment]
The above was written very quickly - I will spend some time cleaning this up today/tomorrow.

**Comment by skellock** [comment]
Holy crap just reading now.

**Comment by rmevans9** [comment]
Updated to add some complications that I can think of while thinking through the plugin implementation.

**Comment by rmevans9** [comment]
Added a basic plan to start with for implementation.

**Comment by skellock** [comment]
Looks like we're going to get a chance to do this after all @rmevans9 .  Just needed 400 days to let it cook.
