### ISSUE TITLE
Unable to resolve module `ramda`

### ISSUE THREAD

**Issue by SoundBlaster** [infinitered/reactotron#482]
```
error: bundling failed: "Unable to resolve module ramda from mobileapp/node_modules/reactotron-react-native/dist/index.js
```
Installed modules:
- "react-test-renderer": "16.0.0-alpha.12"
- "reactotron-react-native": "^1.12.1"
- "reactotron-redux": "^1.12.0"
- "reactotron-redux-saga": "^1.12.0"

As a solution I install the `ramda` manually

**Comment by skellock** [comment]
Using npm >=5.0 & <5.2 by any chance?  There was a bug that removed some dependencies.

**Comment by blackrat** [comment]
I have the same failed resolve issue with the 'PizzaApp' sample (included everything on the examples down to installing i18n), although I'm getting it from CreateStore.js and don't have reactotron included.

Using npm 5.3.0 and package.json contains "ramda": "^0.24.1"
(Paths left truncated to remove absolute root)
```
error: bundling: UnableToResolveError: Unable to resolve module `Ramda` from `PizzaApp/App/Redux/CreateStore.js`: Module does not exist in the module map or in these directories:
  PizzaApp/node_modules
```

**Comment by skellock** [comment]
That's strange.  Is that the actual error?  With capital R for `Ramda`?

**Comment by blackrat** [comment]
Yes. That's the actual spelling. Shall I take this one to the other project rather than cluttering reactotron? I only mentioned it here since I thought that it might be relevant.

**Comment by skellock** [comment]
Was this from ignite @blackrat ?

**Comment by skellock** [comment]
Feel free to reopen if you have more questions.

**Comment by blackrat** [comment]
Yes. Sorry about the slow reply. It was from ignite. I think I've re-raised it there.
