### ISSUE TITLE
[v2] Lint from the top level of the repo fails

### ISSUE THREAD

**Issue by rmevans9** [infinitered/reactotron#485]
It looks like the TypeScript changes caused a failure when running lint. It complains about not being able to find module 'babel-eslint' (which makes sense since we don't use babel any more....). Needs investigation into plan to resolve.

**Comment by rmevans9** [comment]
After about 30 seconds of looking into why its because of StandardJS. It does not support TypeScript which means we have to move to TSLint or similar. @skellock opinions on a TSLinter to integrate?

**Comment by skellock** [comment]
I’m using this on a client project. So far so good.

```json
{
  "extends": ["tslint-react-recommended"],
  "rules": {
    "ordered-imports": [false],
    "quotemark": [true, "single", "jsx-single", "avoid-escape"],
    "semicolon": [true, "never"],
    "member-access": [false],
    "member-ordering": [false],
    "trailing-comma": [true, { "singleline": "never" }]
  }
}
```

And in dev deps:

```json
    "tslint": "5.5.0",
    "tslint-eslint-rules": "4.1.1",
    "tslint-react": "3.0.0",
    "tslint-react-recommended": "1.0.9",
```

I like it. I’m open to anything though. The only things I really care about is that it works well with`prettier` and doesn’t have the devils punctuation: the semi-colon.

**Comment by rmevans9** [comment]
![screen shot 2017-07-28 at 9 44 07 pm](https://user-images.githubusercontent.com/14151327/28741128-e8689b56-73dd-11e7-9031-9ca4583e06e9.png)

I have integrated based upon the rules you suggest and there are some stylistic changes it wants like no space before a functions ( and such. Are you cool with these?

Working on `prettier` now

**Comment by skellock** [comment]
Yes sir.

**Comment by skellock** [comment]
Linting is working now.  I added a prettier file to the root. I’ll do a sweep with prettier in the morning.
