### ISSUE TITLE
View saved states within Reactotron

### ISSUE THREAD

**Issue by rmevans9** [infinitered/reactotron#486]
I marked this as maybe v2 as I am not sure we want to invest time in building out the UI for this since the app is going to go through some major changes. Currently when you take a snapshot of your redux store you can't view what the statetree of that snapshot actually is. It might make sense to allow for digging into the statetree from within Reactotron of the snapshots you have taken.

Idea curtesy of adronitis on the IR slack.

**Comment by skellock** [comment]
That's a great suggestion.
