### ISSUE TITLE
Can't connect reactotron to real android device

### ISSUE THREAD

**Issue by ferminmoli** [infinitered/reactotron#487]
Hi,

I can connect reactotron to my real android device.

I added the following lines on index.android.js

`import Reactotron from 'reactotron-react-native'

Reactotron
		.configure() // controls connection & communication settings
		.useReactNative() // add all built-in react native plugins
        .connect() // let's connect!`

**Comment by KrishnanAnil** [comment]
Have you done 
adb reverse tcp:9090 tcp: 9090

**Comment by lucasbento** [comment]
I think we can close this issue.

**Comment by ticketapp** [comment]
> Have you done
> adb reverse tcp:9090 tcp: 9090

=> It works (without the spaces between the second tcp: and 9000) adb reverse tcp:9090 tcp:9090
