### ISSUE TITLE
Add a link to babel plugin in Tips and Tricks

### ISSUE THREAD

**Issue by JonnyLinja** [infinitered/reactotron#489]
Specifically, the babel plugin that strips Reactotron from the codebase in production!

**Comment by skellock** [comment]
https://github.com/infinitered/babel-plugin-ignite-ignore-reactotron

Lemme know if you try it.

**Comment by rmevans9** [comment]
Closing this for now because we haven't really been pushing the babel plugin. If we start to then we will revisit.
