### ISSUE TITLE
Feature Request: Show stats on number of actions of each type

### ISSUE THREAD

**Issue by varungupta85** [infinitered/reactotron#491]
I use Reactotron with my react-native app to check the state of redux store and the various actions that my app is dispatching. In order to measure app performance and to just know that I haven't accidentally added some code that is dispatching too many actions, it would really help if I can see the number of actions of each type that my app has dispatched till now. It is almost impossible to count it from the desktop app and the output is not present in a text file using which I could have found the number of times, the action type string is present.

**Comment by skellock** [comment]
I don't feel like that metric is a good fit for Reactotron.  

It'd be pretty straight forward to integrate this with Reactotron though.

Create a new reducer called `ActionTracker`.  It's state could be `counters = {}`.

Whenever the reducer fires (it'll fire for *every* action), update the state to become `counter[action.type] = (counter[action.type] || 0) + 1`.

Then you can subscribe to your action tracker and watch the numbers go up in real time.
