### ISSUE TITLE
Expanding logs for console.tron.log()

### ISSUE THREAD

**Issue by RyszardRzepa** [infinitered/reactotron#492]
Can I expand logs from console.tron.log() in the same fashion as it is in "Action" Timeline?
By clicking on "Action" I can inspect object but when I log console.tron.log(`logs for cart: 
${this.props.cart}`)
I am getting just a feedback that I have arrays of objects, and no possibility to inspect them.
Is there a way to inspect objects using console.tron.log() with "``" to write a string to name a logs?

![screen shot 2017-08-02 at 14 02 25](https://user-images.githubusercontent.com/13038459/28872917-8139528e-778b-11e7-9f9d-516b16d5be4f.png)

**Comment by rmevans9** [comment]
How are you passing the data to `console.tron.log`?

**Comment by RyszardRzepa** [comment]
console.tron.log(`${this.props.cart}`)

**Comment by RyszardRzepa** [comment]
with "``"

**Comment by RyszardRzepa** [comment]
Ok, so I can just pass the this.props.cart and inpsect the object, but I would like to use "``" to write a string to know what I am logging.

**Comment by skellock** [comment]
A couple of options (sorry for butting in @rmevans9 -- you're probably typing something right now too ).

```js
console.tron.log({ cart: this.props.cart })
console.tron.display({ name: 'CART', value: this.props.cart, preview: 'omg whats inside?' })
```

**Comment by rmevans9** [comment]
I was indeed... gotta work on those typing skills to get faster at my responses lol.
