### ISSUE TITLE
Logs displayed out of order

### ISSUE THREAD

**Issue by kevinvangelder** [infinitered/reactotron#497]
If multiple logs are sent within the same second they are often, if not always, reverse-sorted within that second (oldest at top instead of bottom). Additionally, in at least one situation an entire second worth of logs was displayed after 3-4 subsequent seconds of logs (15, 17, 18, 19, 16 [top]).

In light of this information, does it make sense to, either always or optionally, display logs in order of the timestamp at which it was dispatched versus the order they were received?

**Comment by skellock** [comment]
Would it be possible to put together a repo or at least a gif maybe of it in action?

I'm trying to think where this could happen.

**Comment by skellock** [comment]
If you have any more details, please feel free to reopen.
