### ISSUE TITLE
Out of box React Native debug connection issue

### ISSUE THREAD

**Issue by jasonkuhrt** [infinitered/reactotron#498]
I have a fairly out-of-box `CRNA` app that isn't working with the reactotron quick start instructions provided for react native. As you can see in the screenshot(s) below there is seemingly an initial connection working but then it crashes a few moments later.

Initially:

![image](https://user-images.githubusercontent.com/284476/29127032-e5b8264c-7ced-11e7-989f-a8ecb9b1ac74.png)

Then:

![image](https://user-images.githubusercontent.com/284476/29127023-e0a74570-7ced-11e7-9d8c-75c47c6a9700.png)

```
❯ create-react-native-app --version
create-react-native-app version: 1.0.0
```

I'm new to the many tools at play here so don't know what other information would be valuable to have.

**Comment by skellock** [comment]
I've yet to use `create-react-native-app`, but i'll give that a go and see if i can reproduce it.

What if you were to not call the `connect()` statement on Reactotron.  Same thing?

**Comment by jasonkuhrt** [comment]
@skellock I discovered the issue is not related to `reactotron`. The issue is related to `enable debugging` which for some reason started to have connection issues with the remote chrome debugger. Sorry for the noise!

**Comment by skellock** [comment]
That's not noise at all.  

Ya I wish we could have these two things play nice together.  I'm not what's causing the issue to be honest.  

Some projects it's fine, some it's not.  I just paired with a co-worker and it was fine with him and he was using both.  

`angry-man-shaking-fist-at-a-cloud.jpg`

**Comment by rmevans9** [comment]
I use both on two projects without issue after I get it up and running. Typically when I start up for the day and launch the simulator I get a crash or two right after the packager starts but once I clear them its smooth sailing even with turning on/off remote debugging

**Comment by jasonkuhrt** [comment]
This project is amazing but I kind of wish we could roll its features into the chrome debugger for react native. I'm curious how you make the workflow with two tools smooth. And then there are the IDE options like nuclide and vscode too.

**Comment by kevinvangelder** [comment]
@jasonkuhrt What do you need from Chrome Debugger that you can't get from Reactotron? I only ever launch Chrome Debugger to do breakpoints (usually trying to work out RN or RNW bugs).

**Comment by jasonkuhrt** [comment]
@kevinvangelder I'll see as I go along here, but your question gives me some expectations then! Maybe not much!
