### ISSUE TITLE
Use 'prop-types' instead of React.proptypes

### ISSUE THREAD

**Issue by nhducit** [infinitered/reactotron#499]
If you are busy, I would like to help send PR

**Comment by skellock** [comment]
It should be gone from the all the client-side libraries.

Are you talking about the ones in the App?

**Comment by ohtangza** [comment]
I think he is talking about Reactoron App.

**Comment by skellock** [comment]
I think you’re right.

**Comment by M-ZubairAhmed** [comment]
shall I take up this issue?

**Comment by skellock** [comment]
Time to shine @M-ZubairAhmed !

**Comment by nhducit** [comment]
@skellock Sorry, I forgot this issue. Please go a head @M-ZubairAhmed

**Comment by M-ZubairAhmed** [comment]
Thank you @skellock and @nhducit , i have started replacing in `reactotron-app`

**Comment by skellock** [comment]
Holler if you get stuck.  it can be a bit of a bear to start contributing on this project.  :(

**Comment by M-ZubairAhmed** [comment]
Thank you @skellock, i actually like how the app is written,
i have submitted the [PR](https://github.com/infinitered/reactotron/pull/517). Please check and let me know

**Comment by skellock** [comment]
Thank you @M-ZubairAhmed !  You rock!
