### ISSUE TITLE
Copy API request as CURL

### ISSUE THREAD

**Issue by Andreyco** [infinitered/reactotron#500]
It would be great to have possibility to copy network request as CURL.

**Comment by skellock** [comment]
Was going to close this, but holy crap, 20 people want it. Haha.

**Comment by skellock** [comment]
And 3 people have hearts. Which means, 17 of you thumb people are zombies.

**Comment by skellock** [comment]
https://www.npmjs.com/package/curl-cmd via @rmevans9 in our Slack channel.

**Comment by Andreyco** [comment]
Hey... Thanks for keeping this poor issue alive! :D It might happen I find a time and dig into this!

**Comment by robinheinze** [comment]
Going to give this a shot today. If I can't get it finished, I'll at least post any helpful knowledge I gleaned during my attempt.

**Comment by skellock** [comment]
@robinheinze i had a quick look at this today as well (coincidence!).  That library uses some `node` things... so we might just have to roll our own (doesn't seem that difficult tho).

**Comment by indapublic** [comment]
It would be excellent!

**Comment by rmevans9** [comment]
This is released.

**Comment by AugustoAleGon** [comment]
The new release is the best!
