### ISSUE TITLE
Copy/Export from Reactotron

### ISSUE THREAD

**Issue by nonameolsson** [infinitered/reactotron#501]
I think that it would be very good to be able to export/copy from Reactotron to paste in to `.csv` or `.xls`.  

Here is a screenshot of some props.
![screen shot 2017-08-14 at 18 47 22](https://user-images.githubusercontent.com/1493018/29296608-0ce60b08-8121-11e7-9222-bd3fec9a5410.png)

I would like to copy the output and paste it in Excel to be able to extract all the keys, but not the values. Now I need to manually copy and paste each key.

I tried with `console.tron.log(Object.keys(vehicle))` but it results in almost the same output, having to do the same job again. 

![screen shot 2017-08-14 at 18 50 18](https://user-images.githubusercontent.com/1493018/29296682-76341dfc-8121-11e7-84db-e55756392e0e.png)

Is there some other way to achieve what I'm  need?

**Comment by rmevans9** [comment]
What is your need for copying all of these out? Where are they coming from? I assume they are not hard coded in the app since you want to pull them out of `reactotron`.

**Comment by skellock** [comment]
What does the copy button at the top of each message give you? Does it get butchered?

**Comment by nonameolsson** [comment]
@rmevans9 That's a good question, I see that I didn't explain it well :) The data source is a REST-api. I save the result to Redux. Now I wanted to add more flow-definitions in my project, i.e. the data you see in the screenshot. 
I just wanted to in a fast way have a list of all the keys in the object. I ended up copying and pasting them one by one into my flow file. Now it's done, but I still have more data to add to my flow definitions, and I would not to have to do it manually.

@skellock Good idea, but it gives me all the data, not just the keys.

**Comment by skellock** [comment]
Copy should give you the keys too.  That's a bug.

**Comment by nonameolsson** [comment]
@skellock Sorry, I wasn't clear enough.

> @skellock Good idea, but it gives me all the data, not just the keys.

I meant that it gives both keys and data. I just wanted the keys.

**Comment by skellock** [comment]
oh.... haha.. sorry ya... that's what it is supposed to do.

i totally get what you're asking now.

**Comment by rmevans9** [comment]
If you have all the JSON you could do some tricks with an editor like sublime or vscode to clean up the unwanted data.

**Comment by nonameolsson** [comment]
@rmevans9 that is true! But if you think this is a feature that others would use, maybe it could be added to the awesome 🎉   Reactotron?

**Comment by skellock** [comment]
I think this might be a bit too specific case.  You can use a util like `jq` or a editor extension to transform json.
