### ISSUE TITLE
Setup for Reactotron App

### ISSUE THREAD

**Issue by DiMoNTD** [infinitered/reactotron#502]
Hi. Thank you for great tool, but...

I needed to configure the host and port on which the WebSocket server will be launched, but I could not find a similar option. I would like to be able to make the minimum settings for the Reactotoron application. Thank you!

Why I need it? Because I develop react-native application for android based OS for third-party device that has truncated functional (and there no way to `adb shell` or `adb reverse tcp`), so I can only start local webserver with socketio on my PC and only after that RN app can connect to it from that device. For example, such problem was with `redux-devtools`, so I've installed `remote-redux-devtools`, installed `remotedev` for it, started the `remotedev` server and after that I could connect it with my application and `remote-redux-devtools`.

**Comment by skellock** [comment]
Just so I'm clear, this device only has access to a blessed port?  Like port 80 or something?

Also are you on macos, windows, or linux?

**Comment by DiMoNTD** [comment]
@skellock 
> Just so I'm clear, this device only has access to a blessed port? Like port 80 or something?

That device has access only to local network (via WiFi).
I can't use localhost, like (127.0.0.1), but I can use my local network (with WiFi, for example `192.168.0.52` with any port like `8000`). My PC and device must be in one WiFi network.

> Also are you on macos, windows, or linux?

I use Windows 10

**Comment by skellock** [comment]
Oh, so, it sounds what you're looking for is:

`Reactotron.configure({ port: 8000, server: '192.168.0.52' })` in your codebase while you're developing then.

**Comment by DiMoNTD** [comment]
@skellock I know about this feature, but instead of `server` I wrote `host`

```
  Reactotron
    .configure({
      name: 'Ignite App',
      host: '192.168.0.52'
    })
    .useReactNative()
    .use(reduxPlugin({ onRestore: Immutable }))
    .use(sagaPlugin())
    .connect();
```

From the sources `reactotron-react-native`
```
var DEFAULTS = {
...
  host: getHost('localhost'),
  port: 9090
...
};
```

but it did not work

I will try with `server`, when go back to work :)

**Comment by DiMoNTD** [comment]
@skellock 
But anyway, how it can help? Reactotron app will up WS Server at `localhost:9090`, but RN app will try connect to `192.1680.52:9090` and there will no be anything, as I can think

**Comment by skellock** [comment]
Oops, sorry you're right it's `host` not `server`.  Ha!

So the app will always launch a http server with web sockets on your machine on port `9090`.  However it listens on **all** interfaces.

If your device is on the same network interface, it should be able to connect.

This is what I have to do when running on an Android < 5 device that doesn't support `adb reverse`.

Give it a shot when you're back in the office.  Lemme know.

**Comment by DiMoNTD** [comment]
@skellock 
Could you clarify, when I start Reactotron app, it starts Web Server with websockets on `localhost:9090`?
So if I go to `localhost:9090` with browser, I should see the webserver host?

Because I ran the Reactotron app and address `localhost:9090` is still unable in browser.

**Comment by skellock** [comment]
I don’t think you’d see anything in the web browser. The port should be open but only to bring through the web sockets traffic.  I don’t think I have even tried that so I’m kinda curious.

The reactotron app listens on all interfaces on your computer on port 9090.  The device running react native should then connect to the ip of the computer on port 9090.

Can you paste your configure call?

**Comment by skellock** [comment]
Closing.  Feel free to reopen if you have more questions.
