### ISSUE TITLE
No HiDPI screen support on Windows?

### ISSUE THREAD

**Issue by jankalfus** [infinitered/reactotron#503]
It looks like there's no support for hi-resolution screens on Windows? This is what the app looks like:
<img width="477" alt="electotron" src="https://user-images.githubusercontent.com/12714276/29629016-ab86a75a-8837-11e7-91ad-f1341fbd7143.png">

Workaround is to go to `Properties -> Compatibility`, check `Override high DPI scaling behavior. Scaling performed by:` and select `System`. However, the app is then all blurry (but hey, at least it's usable).

Are there any plans for HiDPI screens support?

**Comment by skellock** [comment]
I’d love to. Just not sure how.  I don’t own one to test.  This is is a standard electron app so i’ll Take a look around to see how others do it.

**Comment by kevinvangelder** [comment]
Looks like we just need to make a manifest file change? `<dpiAware>true/pm</dpiAware>`

https://github.com/electron/electron/pull/8786

**Comment by jankalfus** [comment]
I can definitely test a potential fix. I never used electron to create apps, so if you guys could please make the change in the manifest, I'll be glad to test it.

**Comment by skellock** [comment]
I’m not sure where this manifest file is and I do write electron apps. 😳

When I do find it, I’ll take you up on that offer tho!

**Comment by skellock** [comment]
We're transitioning away from electron. Thanks for the issue. 🙏
