### ISSUE TITLE
How to implement overlay into your code?

### ISSUE THREAD

**Issue by harrycondron** [infinitered/reactotron#504]
Having an issue following the documentation on how to use the reactotron overlay feature...just wondering if someone could point me in the right direction as i'm new to react-native and reactotron. Thanks! 

Edit: I tried to follow the documentation as best I could but I keep getting an error saying "Cannot read property 'overlay' of undefined"

**Comment by skellock** [comment]
Check out [this example](https://github.com/infinitered/reactotron/blob/master/packages/demo-react-native/App/Containers/RootContainer.js#L201).

**Comment by harrycondron** [comment]
where are you importing overlay? i put that line of code in and i'm still getting the same error

**Comment by skellock** [comment]
It comes along with the [Reactotron object](https://github.com/infinitered/reactotron/blob/master/packages/demo-react-native/App/Config/ReactotronConfig.js#L31) that is placed on `console`.

You get `overlay` from using [`useReactNative`](https://github.com/infinitered/reactotron/blob/master/packages/demo-react-native/App/Config/ReactotronConfig.js#L17).

**Comment by skellock** [comment]
Closing up.  Feel free to reopen if you have more questions.

**Comment by EdmundasR** [comment]
Hello, It's unclear how to enable overay from the docs as code samples are partial and old example repo files are 404

if I do in App.tsx

// import reactotron for dev mode only
if (__DEV__) {
  // eslint-disable-next-line global-require
  Reactotron = require('./ReactotronConfig');
}


Reactotron.overlay is undefined

please fix the docs with more clear code snippets or provide same examole repo.
