### ISSUE TITLE
Use logging functions cross platfrom.

### ISSUE THREAD

**Issue by jmacioszek** [infinitered/reactotron#505]
I came across a problem where I have library that is used on both platforms, mobile and web. I need to log some data from it to Reactotron. 

However, because conditional require is not supported by RN that means I need to install both Reactotron libraries (reactotron-react-js and reactotron-react-native) to get that working. 

Is there any workaround for that case?

**Comment by skellock** [comment]
You’ll have to bring in both.  One for each platform. Lemme know if you run into any issues with that setup.  I know of one project that is doing that successfully.

**Comment by skellock** [comment]
Lemme know if we can be of more assistance.
