### ISSUE TITLE
NativePerformance.now is undefined

### ISSUE THREAD

**Issue by wilr** [infinitered/reactotron#507]
![screen shot 2017-09-04 at 12 20 53 pm](https://user-images.githubusercontent.com/101629/30007828-874089d2-916b-11e7-9535-e3cb18132875.png)

React Native 0.47. Wonder if I'm missing a polyfill for window.performance? I can fix manually by wrapping the function in a typeof. Happy to submit a PR

```
// try to find the browser-based performance timer
var nativePerformance = typeof window !== 'undefined' && window && (window.performance || window.msPerformance || window.webkitPerformance);

// if we do find it, let's setup to call it
var nativePerformanceNow = function nativePerformanceNow() {
+  if (typeof nativePerformance.now === "function") {
    return nativePerformance.now();
+ } else {
+   return Date.now();
+ }
};
```

**Comment by rmevans9** [comment]
What version of Reactotron are you running?

**Comment by wilr** [comment]
Ah yep, thought my constraint was latest 1.12 but it was locked to prior to `2823863103ea4bef677c14183aa829f8d4cf714e`

**Comment by rmevans9** [comment]
Glad that was an easy one to fix up
