### ISSUE TITLE
Publish Latest versions

### ISSUE THREAD

**Issue by TheRusskiy** [infinitered/reactotron#508]
Please publish your latest build to homebrew / make downloadable electron artifact.
Thank you guys!

**Comment by skellock** [comment]
Ahh I overlooked that.   Thx.  It looks like there’s only a few minor things though. Mostly client-side changes lately.

**Comment by rmevans9** [comment]
@skellock have you published the latest version yet? Just checking to see if we can close this one up.

**Comment by skellock** [comment]
Yes sir.
