### ISSUE TITLE
losting initialProps when using console.tron.overlay

### ISSUE THREAD

**Issue by luanpablo-luizalabs** [infinitered/reactotron#509]
When using (in `App/Containers/App.js`)

```
export default DebugConfig.useReactotron
  ? console.tron.overlay(App)
  : App
```

☝️  generated from ignite 2.0

The following props, which are populated by the `MainActivity` (another app calls it with some params in the intent), comes empty :(

```
class App extends Component {
  constructor (props) {
    super(props)
    let data = JSON.parse(props.data)
  }
}
```

The App above is the one registered in the `index.android.js` like below:

`AppRegistry.registerComponent('AppName', () => App)`

When I changed the App export to simply do that:

`export default App`

It works, the initialProps is filled.

Any workaround to keep working with the overlay?

Thanks a lot.

**Comment by skellock** [comment]
Oops.  Ya, that's a bug for sure.   We need to [pass thru the props](https://github.com/infinitered/reactotron/blob/master/packages/reactotron-react-native/src/plugins/overlay.js#L27) on the wrapped component.

**Comment by skellock** [comment]
Ok @luanpablo-luizalabs, `reactotron-react-native@1.12.3` should contain this fix now.

Lemme know if doesn't.  Thanks for the report!

**Comment by luanpablo-luizalabs** [comment]
Thanks a lot. It's fixed. 👍
