### ISSUE TITLE
Using Reactotron.log without import

### ISSUE THREAD

**Issue by henrikra** [infinitered/reactotron#514]
Reactotron is so awesome when debugging! My only complaint is that when I want to add `Reactotron.log` I always have to add also `import Reactotron from 'reactotron-react-native';`. Normally with `console.log` I just add it to where ever I want and it works. Do you guys bypass this in some way?

Only solution I have got so far is to assign `Reactotron.log` to `console.log` like this
`console.log = Reactotron.log;` So now when I write `console.log` it logs the data to Reactotron :)

**Comment by rmevans9** [comment]
`Reactotron.log` does not have the same API as `console.log` so beware of that. With that said you have a few options:

1. Similar to how they do in `ignite` assign your `reactotron` instance to `console.tron` eg:  `console.tron = reactotron` then you could simply do `console.tron.log('yay!')`

2. Write an adapter for `Reactotron.display`. Here is the one I use for better or worse:

```
const oldConsoleLog = console.log;

    /* eslint-disable */
    console.log = (...args) => {
        oldConsoleLog(...args);

        Reactotron.display({
            name: 'CONSOLE.LOG',
            value: args,
            preview: args.length > 0 && typeof args[0] === 'string' ? args[0] : null,
        });
    };
    /* eslint-enable */
```

**Comment by skellock** [comment]
@rmevans9 that's an interesting solution!

**Comment by henrikra** [comment]
Actually I just made one too! Now function `debug` is available globally. Or is there any advantage injecting those things to `console` object?
```js
debug = (title, data) =>
  Reactotron.display({
    name: title,
    value: data,
    preview: JSON.stringify(data).substr(0, 50),
  });
```
usage:
```js
debug('title here', {this: 'is', example: 'data'})
```
Looks like this in Reactotron:
![image](https://user-images.githubusercontent.com/12229968/30215752-9ba88a0e-94b9-11e7-80a1-54a8c7c68c96.png)
![image](https://user-images.githubusercontent.com/12229968/30215759-9fc2fd7c-94b9-11e7-8827-da6fedee1ed6.png)

**Comment by skellock** [comment]
Not really no.  Just preference I guess.  `console` seems to be a place devs pile on stuff, so I thought, oh well, let's do that too.  =)

**Comment by skellock** [comment]
Also, i've been using Reactotron for a while now, and it never occurred to make little helper like this.  Thx guys!

**Comment by henrikra** [comment]
Good to hear @skellock Btw I think `display` function's default behaviour should be that when `preview` is provided use that as preview. But it is not provided just `JSON.stringify` the data so you can easily see preview of the data just like in browser's console :)

**Comment by skellock** [comment]
I'll consider making that an option in Reactotron 2.  Thanks!
