### ISSUE TITLE
Yarn Workspaces vs Lerna

### ISSUE THREAD

**Issue by rmevans9** [infinitered/reactotron#519]
Which one makes more sense? Which works better? Which makes more sense? Investigate!

https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/

**Comment by skellock** [comment]
I'd be up for whatever you recommend.

**Comment by skellock** [comment]
I’m happy with lerna but feel free to reopen if you feel like yarn workspaces is a better fit.

**Comment by skellock** [comment]
@rmevans9 is a prophet.
