### ISSUE TITLE
Add Prettier Support

### ISSUE THREAD

**Issue by ericadamski** [infinitered/reactotron#523]
I suggest adding a prettier config and pre-commit hook to make formatting the code simple! 
- https://github.com/prettier/prettier
- https://github.com/prettier/prettier#pre-commit-hook

**Comment by rmevans9** [comment]
We are actually beginning to incorporate this with some work I am doing on the app. I think we should certainly do this to the rest of the packages too.

**Comment by ericadamski** [comment]
@rmevans9 is there a config I can add to the refactoring of the components? I can also do the pre-commit hook for the `reactotron-app` package if you would like

**Comment by skellock** [comment]
#534 has this in place.

**Comment by skellock** [comment]
Oops sorry. Will keep this open for the prettier, lint-staged, husky triple threat.

**Comment by skellock** [comment]
I think I'm stepping on your toes here @ericadamski, so I'm going to hijack this issue.

**Comment by ericadamski** [comment]
@skellock no worries! I am having a hard time re-merge master anyway ;) enjoy!

**Comment by skellock** [comment]
i think we're pretty close here tho!

Ya, we had a flurry of PRs yesterday to make this repo sane again.  =)

**Comment by ericadamski** [comment]
@skellock that is great!
