### ISSUE TITLE
console.tron.display image nothing happen

### ISSUE THREAD

**Issue by amorenew** [infinitered/reactotron#524]
Hi
I used image like docs
https://github.com/infinitered/reactotron/blob/master/docs/tips.md
console.tron.display({
  name: 'Tacos',
  value: {a: 1, b: [1,2,3]},
  preview: 'when you click here, it might surprise you!',
  important: true,
  image: 'http://placekitten.com/g/400/400'
})
but the image didn't appear in the timeline

**Comment by skellock** [comment]
Can you try a different image URL?

Did any log statement appear?

What happens if you call .image()?

Is this with the latest version?

**Comment by amorenew** [comment]
Can you try a different image URL?
>> not working
Did any log statement appear?
>>yes
What happens if you call .image()?
>>how I can .image()
Is this with the latest version?
>>yes

**Comment by skellock** [comment]
It accepts an object like this:

```js
{
  "uri": "http://placekitten.com/g/400/400",
  "preview": "placekitten.com!",
  "filename": "cat.jpg",
  "width": 400,
  "height": 400,
  "caption": "D'awwwwwww",
}
```

**Comment by skellock** [comment]
Also http://placekitten.com/400/401 works.

The image seems flakey nowadays. 🚨

**Comment by amorenew** [comment]
![untitled](https://user-images.githubusercontent.com/2842459/31338275-2aee738a-ad07-11e7-98fa-39d638884f48.png)

yes, it's working but what about display?

**Comment by amorenew** [comment]
it's working as object not only image: 'http://placekitten.com/g/400/400'
image:{
        "uri": "http://placekitten.com/g/400/400",
        "preview": "placekitten.com!",
        "filename": "cat.jpg",
        "width": 400,
        "height": 400,
        "caption": "D'awwwwwww",
      }

**Comment by amorenew** [comment]
helper class you can put in tips and tricks too

```
import Reactotron from 'reactotron-react-native'

export default function Log(name, value, preview, important = true, image) {
    if (!value) {
        value = name;
        name = 'DEBUG';
        previe=value;
        image=''
    }

    if (!preview) {
        // preview = JSON.stringify(value);
         preview = 'Values';
    }
    console.log(name);
    console.log(value);
    console.log(preview);
    console.log(important);
    console.log(image);
    (__DEV__)
        ? Reactotron.display({name: name, value: value, preview: preview, important: true, image: image})
        : console.log(name)
}
```

**Comment by amorenew** [comment]
"preview": "placekitten.com!",
        "filename": "cat.jpg",
        "width": 100,
        "height": 100,
        "caption": "D'awwwwwww",
not in log so I removed it even if url is wrong and width or height is useless
only uri is required and working  { "uri": "http://placekitten.com/g/400/4088888880"}
