### ISSUE TITLE
Duplicate Logs

### ISSUE THREAD

**Issue by amorenew** [infinitered/reactotron#525]
I wonder do I make something wrong or duplicate logs is normal 
in AsyncStorage and Redux Reducer
![ScreenShot](https://user-images.githubusercontent.com/2842459/31387451-2887b9d6-add3-11e7-8d3b-ce9e7df24167.png)

**Comment by amorenew** [comment]
my reducer 
Note **Log** is Reactotron.display
```
export default function languageReducer(state = {
    language: {
        id: 1,
        code: 'EN'
    }
}, action) {
    Log(TAG,'Language Reducer');
    switch (action.type) {
        case types.CHANGE_LANGUAGE:
            Log(TAG,'Action: ' + action.language);
            Log(TAG,'Action Type: ' + action.type);
            Log(TAG,{
                ...state,
                language: action.language
            });
            return {
                ...state,
                language: action.language
            };
            break;
        default:
            return state;
            break;
    }
}
```

**Comment by skellock** [comment]
Hmm... I haven't experienced this.

Keep in mind that log statement will fire for things the reducer doesn't track.  You have it before your `action.type` switch.

**Comment by amorenew** [comment]
As No one else has this behavior I will close the issue
