### ISSUE TITLE
Upgrade Deps

### ISSUE THREAD

**Issue by rmevans9** [infinitered/reactotron#536]
This issue is to track deps that are out of date that we should work on updating. I will be PRing the updates.

- [x] Webpack (two major versions behind) #537 
- [x] Webpack hot/dev middleware #537
- [x] Webpack loaders #537
 - babel-loader
 - css-loader
 - file-loader
 - url-loader
 - json-loader
 - style-loader
- [x] Electron
- [x] Babel + all plugins/presets (will work on listing them all out) NOTE: Might skip since we are moving quickly toward removing babel
- [x] Express
- [ ] React
- [ ] React DOM
- [ ] All React third party libs (will work on listing them all out) 
- [ ] MobX
- [x] "Others" (will work on listing them all out) 

Sidenote: Should probably look at some of the automatic dep trackers like: https://www.dependencies.io/ or similar

**Comment by rmevans9** [comment]
NOTE: I had to install a fork of `react-modal-dialog` because the original is not maintained and doesn't support react 16.

**Comment by rmevans9** [comment]
NOTE: React, React DOM (along with third party libs) and MobX actually breaks the app when you upgrade. Leaving them off for now. I think we should work to cleanup the app (and get to TS) then work at getting the upgrades complete.

**Comment by skellock** [comment]
The `modal` dependency is holding us back too.  It uses an old `jss`.  I'd like to remove that. (or update it to the latest).  SweetAlert2 is pretty good too.  I'm up for replacing that.

**Comment by skellock** [comment]
I'd like to rework how `mobx` is used too.

**Comment by rmevans9** [comment]
I think a rework in `mobx` would be wise once we land the PR to get it out of the dep list for `reactotron-core-server` (PR #542). The `react-modal-dialog` was a dep that gave trouble with a `react` 16 upgrade. Looking at it the code is pretty light so I am sure we can figure something out (even if it is just pulling the code in and updating locally for now)

**Comment by skellock** [comment]
#542 is in. Thanks!

#543 continues this journey. Once this lands, then `reactotron-app` and those `mobx` shenanigans are up for grabs.

**Comment by rmevans9** [comment]
Closing this since the original intent is complete.
