### ISSUE TITLE
Get MobX out of reactotron-core-server

### ISSUE THREAD

**Issue by rmevans9** [infinitered/reactotron#539]
This should be more of an event emitter based package. Unsure if we want to do an actual event emitter or more of a callback setup similar to how we already have onConnect and onDisconnect

**Comment by rmevans9** [comment]
Looking through the current codebase we already have an `onCommand` which is called but the code actually relies on the core-server also adding the command to the commands observable. So we might already be most of the way there

**Comment by rmevans9** [comment]
Tentative Plan:

- Move `commands.ts` from `reactotron-core-server` to `reactotron-app/App/Lib` (maybe not the right dir?)
- Move `types.ts` from 'reactotron-core-server` to `reactotron-app/App/Lib` (for now?)
- Remove references to `commands.ts` from `index.ts` in `reactotron-core-server`
- Add a `type` of `clear` handler to `commands.ts` or somewhere else... not in `reactotron-core-server` (this is to handle line 150-151 of `index.ts` in `reactotron-core-server`
- Update `SessionStore` in `reactotron-app` to use the new `commands.ts`
- Wire up `onCommand` in `SessionStore` to call `addCommand` in `commands.ts`
- Remove `mobx` dep from `reactotron-core-server`

**Comment by skellock** [comment]
love it! i'll have some time later tonight to pitch in if you need me.

**Comment by skellock** [comment]
btw: i recommend `mitt` as an event emitter.  i've had good experiences with it and it's cross platform.  It powers our `Overlay`.

**Comment by rmevans9** [comment]
@skellock first crack at a PR landing. I got this working with minimal effort. I have not added any type of event emitter yet, just hooked into the onCommand that was already there. Going to PR and then lets chat tonight.

**Comment by rmevans9** [comment]
We should also evaluate the following things currently handled in `reactotron-core-server`:

- [ ] Handling certain command types (`state.values.change`, `state.backup.response`, others?)
- [ ] Looks like it does something with subscriptions (are these redux subscriptions? if so they need to go)
- [ ] Helper functions (`stateKeysRequest`, `stateValuesRequest`, `stateActionDispatch`, `stateValuesSendSubscriptions`, `stateValuesSubscribe`, `stateValuesUnsubscribe`, `stateValuesClearSubscriptions`, `stateBackupRequest`, `stateRestoreBackup`, `openInEditor`)

IMO `reactotron-core-server` should be responsible for exactly this:
- Handle WS and connections from clients. Passing all messages up the chain
- Allow an interface for generic sending of messages (to replace the helper functions mentioned above)
- Cleaning up of formatting things done on `reactotron-core-client` (the handling of NaN, null, etc)

**Comment by skellock** [comment]
He did it!
