### ISSUE TITLE
Cask is outdated it seems

### ISSUE THREAD

**Issue by Anahkiasen** [infinitered/reactotron#548]
It installs 1.11.2 but latest is 1.12.3 from what I can see

**Comment by skellock** [comment]
You've got the latest.  And yes, you're right, 1.12.3 is what the releases is.

I used `lerna` to power this repo's structure, and they have 2 types of versioning.  The default is a "shared" version number.  Think of it like a highwater mark.  Whenever any of the 7 packages change, it takes a new version number.  

It doesn't quite fit this project right and I'll be switching for version 2.0 so everything goes to a independent version number.

Sorry for the confusion!
