### ISSUE TITLE
Show AsyncStorage as a tree

### ISSUE THREAD

**Issue by ShMcK** [infinitered/reactotron#552]
It would be helpful if the AsyncStorage plugin had an option to display the data as an expandable JSON tree, rather than a large JSON.stringified output.

There may be use cases where data stored in AsyncStorage isn't JSON, so I don't imagine this should be a default.

As an example:

```js
Reactotron
.asyncStorage({
  display: 'json'
})
```

**Comment by skellock** [comment]
This is a really good idea.  I could use this today.  Would you be up for taking that feature on?

**Comment by ShMcK** [comment]
If there's agreement on the config settings, I can take a look at it in the near future.

**Comment by JulienMalige** [comment]
It looks already fixed :
<img width="792" alt="image" src="https://user-images.githubusercontent.com/3756105/46908001-0b467180-cf1c-11e8-94fa-a5836b6778c3.png">

**Comment by krunal-citymall** [comment]
> If there's agreement on the config settings, I can take a look at it in the near future.



> It looks already fixed : <img alt="image" width="792" src="https://user-images.githubusercontent.com/3756105/46908001-0b467180-cf1c-11e8-94fa-a5836b6778c3.png">

what is your configuration, I am getting it in stringify'd manner
