### ISSUE TITLE
Reactotron is not sync on Windows

### ISSUE THREAD

**Issue by AugustoAleGon** [infinitered/reactotron#553]
I am trying to debug with Reactotron on Windows, but currently I do have a problem right now. I already set all the configuration in my ReactotronConfig.js file. But it is not display anything in the Reactotron screen. I already gave permission to have access on the firewall.
I would like
![image](https://user-images.githubusercontent.com/14319083/32659301-171011e0-c5ec-11e7-8195-fcbacc127359.png)
 to know what Do I need to do?

**Comment by skellock** [comment]
What kind of setup are you running?  A simulator?  A device?  Same network?  Android?  Did you run `adb reverse tcp:9090 tcp:9090` to open Android's port forwarding?

**Comment by AugustoAleGon** [comment]
I was using this config: 
`mport Reactotron from 'reactotron-react-native'
import { reactotronRedux as reduxPlugin } from 'reactotron-redux'
import sagaPlugin from 'reactotron-redux-saga'

console.disableYellowBox = true

// First, set some configuration settings on how to connect to the app
Reactotron.configure({
  name: 'Demo App'
  // host: '10.0.1.1',
  // port: 9091
})

Reactotron.useReactNative({
  asyncStorage: { ignore: ['secret'] }
})

// add some more plugins for redux & redux-saga
Reactotron.use(reduxPlugin())

// if we're running in DEV mode, then let's connect!
if (__DEV__) {
  Reactotron.connect()
  Reactotron.clear()
}

console.tron = Reactotron`

I am running on Android Device. Yes on the same network it is connected for usb. I didn't know that I had to run 'adb reverse tcp:9090 tcp:9090`. Do I have to enable on Window for that port 9090?
Can you give a sbrief step by step setting? I will appreaciate it.

Thanks for taking your time to answer me.

**Comment by chlela** [comment]
Running `adb reverse tcp:9090 tcp:9090` solved the issue on my windows machine.  Thanks @skellock

**Comment by faizalshap** [comment]
Please mention this in the docs :)
It might have saved my 30-40mins

**Comment by skellock** [comment]
@faizalshap we do have this in the tips, but is there somewhere else it makes sense to have?

**Comment by chlela** [comment]
@faizalshap mentioned in troubleshooting section too https://github.com/infinitered/reactotron/blob/master/docs/troubleshooting.md

**Comment by skellock** [comment]
@chlela We're switching up in v3 to not using electron anymore, but a web site. This means we'll be able to ship reactotron completely as devDependencies.  I appreciate the offer!
