### ISSUE TITLE
Feature Request: Configure precision of timestamp in timeline

### ISSUE THREAD

**Issue by suark** [infinitered/reactotron#563]
In the timeline I am seeing timestamps in hh:mm:ss but it would help a ton if we could make it more accurate.

This is also relevant because in the docs it says "perform quick performance benchmarks", but when I search more, I can't find any way to really get times when trying to benchmark things, other than the timestamps that display on the left side in the time line

Perhaps I'm missing a feature but I'm looking though lots of the code and all the docs.

**Comment by skellock** [comment]
If you've got an `async` function you're testing, try dropping something like this in:

```js
  const bench = Reactotron.benchmark('a')
  await delay(50)
  bench.step('b')
  await delay(50)
  bench.stop('c')
```

**Comment by suark** [comment]
@skellock Thanks for the tip! It would be great it something about using `Reactotron.benchmark` was added to some of the quickstart guides. Take care!

**Comment by skellock** [comment]
Very good point!  Thx!
