### ISSUE TITLE
stopTimer is not a function

### ISSUE THREAD

**Issue by digitaldavenyc** [infinitered/reactotron#564]
Just loaded up reactotron for the first time and getting an error `stopTimer is not a function`. Error happens eventually on every reload of react native

<img width="370" alt="screen shot 2017-12-12 at 9 53 21 pm" src="https://user-images.githubusercontent.com/243799/33919512-0785b1b2-df87-11e7-9bcc-71e4c1341a2f.png">

**Comment by skellock** [comment]
Strange.  Can you give me some more hints to how you project is set up?  

Is the index.js that it bombs on inside react native?
