### ISSUE TITLE
Copy subscription path to clipboard

### ISSUE THREAD

**Issue by artem-russkikh** [infinitered/reactotron#575]
Can't copy previously added subscriptions paths.

Reactotron 1.14.0

**Comment by skellock** [comment]
Thanks for the issue.

What do you mean by copy?  Do you mean copy to the clipboard?  Or are you looking for a way to save your subscription paths between launches of Reactotron maybe?

**Comment by artem-russkikh** [comment]
I mean by copy - copy to the clipboard.

Yeah, persisting subcriptions between Reactotron launches - is a good point for another issue!

Happy upcoming New Year! 🎄

**Comment by skellock** [comment]
Gotcha. That can happen!

Happy new year to you too! 🍾
