### ISSUE TITLE
release android app crash 

### ISSUE THREAD

**Issue by GuillotJessica** [infinitered/reactotron#577]
Hi ,
I use reactotron with ignite and native base boiler plate,
my app on release crash with the following error :

> com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'console.tron.log'), stack:
> <unknown>@1587:456
> navigate@688:256
> _handlePageChanged@724:582
> _jumpToIndex@726:6216
> _handleOnPress@735:1540
> onPress@731:8660
> a@345:540
> callTimers@345:2771
> value@340:3188
> <unknown>@340:921
> value@340:2616
> value@340:893
> 
> 	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
> 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
> 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
> 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
> 	at android.os.Handler.handleCallback(Handler.java:754)
> 	at android.os.Handler.dispatchMessage(Handler.java:95)
> 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
> 	at android.os.Looper.loop(Looper.java:163)
> 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
> 	at java.lang.Thread.run(Thread.java:760)
all mine are commented, and the crash occurs once I click on a button, first load is fine
the 2 left I have are on ScreenTrackingMiddleware.js

**Comment by skellock** [comment]
You'll want to make sure you aren't using Reactotron for your release builds.

Make sure you wrap any calls with

```js
if (__DEV__) {
  console.tron.log('hello')
}
```

**Comment by GuillotJessica** [comment]
thx for the reply !
it is not used in screenTracking,
in CreateStore,
in Reactotron.config,
but in StartupSaga
 btw

**Comment by skellock** [comment]
> undefined is not an object (evaluating 'console.tron.log'), stack:

See that part of the stack trace?  It's calling `console.tron.log`.  This is totally fine in dev mode, but when you've bundled your app for production, you'll need to make sure you don't call reactotron at all.

There's a few ways to do this, but the easiest is to make sure where you have a `console.tron.log` statement, that it's wrapped inside code that looks like this:

```js
if (__DEV__) {
  ... reactotron things here
}
```

That if statement will never be executed in production.  🎉

**Comment by GuillotJessica** [comment]
Thx,
I got the if, but it would be a lot easier to have it said in one of the
many readme instead of having a crash app on unsigned (of course) release
try
the if dev is great though

2017-12-28 16:09 GMT+01:00 Steve Kellock <notifications@github.com>:

**Comment by mufaawan** [comment]
For a very large project, solution found here.
https://stackoverflow.com/a/51947619/5343704
