### ISSUE TITLE
Save subcription keys between Reactotron launches

### ISSUE THREAD

**Issue by artem-russkikh** [infinitered/reactotron#579]
It would be useful if I could save subscription paths between launches of Reactotron

**Comment by skellock** [comment]
It’s a good idea for sure.

One of the things we will have to work out is how we keep multiple apps separate.

I wouldn’t want to see App 1’s settings while working on App 2.

**Comment by skellock** [comment]
Tracking in #421

**Comment by artem-russkikh** [comment]
@skellock note that "State snapshots" not equals "Subcriptions paths"

**Comment by skellock** [comment]
Oh noes... you're right. Sorry!  🙇
