### ISSUE TITLE
MobX

### ISSUE THREAD

**Issue by aksonov** [infinitered/reactotron#58]
They have devtools already, but it doesn't support react native... https://github.com/mobxjs/mobx-react-devtools

**Comment by skellock** [comment]
Absolutely.  Stay tuned.

**Comment by Lakston** [comment]
That would be awesome, I'm not sure I have the skills to help with this but if you break it down into small tasks I might be able to help

**Comment by rlski** [comment]
Just as @Lakston I'd love to help in my range of skills. I'm using MobX with RN quite a lot and having a way to log the state and actions like Reactotron does would be awesome. Just let us know !

**Comment by zevmo** [comment]
+1

**Comment by MovingGifts** [comment]
@skellock Any update on MobX integration as opposed to Redux?

**Comment by skellock** [comment]
Not yet.  It's not quite the same approach as Redux as you can have observables anywhere.

You can roll a bit of it yourself by using their `spy()` or even `autorun` with our `log()` or `display()` features.

**Comment by MovingGifts** [comment]
Thank you for the quick response :) Yeah it is a very different approach with observables, but I wouldn't know how to integrate it and I was hoping it was baked into reactotron :)

**Comment by MichelDiz** [comment]
News about it? I have not found anything yet that support MobX in React-Native like mobx-remotedev.

just ref: https://github.com/zalmoxisus/mobx-remotedev/

**Comment by skellock** [comment]
Well, we made it as far as mobx-state-tree. Happy to accept PRs on mobx if anyone is up to it.
