### ISSUE TITLE
Reactotron how to start it?

### ISSUE THREAD

**Issue by AugustoAleGon** [infinitered/reactotron#580]
I already made all the setting in my OS.
I am currently working on a Mac. Basically I am running this following commands:

`react-native start`
`react-native run-android`

And in the main screen of Reactotron there is not sign of any activity.

Any miss configuration?

this is my reactotron config:
```
import Config from '../Config/DebugConfig'
import Immutable from 'seamless-immutable'
import Reactotron from 'reactotron-react-native'
import { reactotronRedux as reduxPlugin } from 'reactotron-redux'
import sagaPlugin from 'reactotron-redux-saga'
// import apisaucePlugin from 'reactotron-apisauce'

if (Config.useReactotron) {
  // https://github.com/infinitered/reactotron for more options!
  Reactotron
    .configure({ name: 'myAppName',
      socketIoProperties: {
        reconnection: true,
        reconnectionDelay: 2000,
        reconnectionDelayMax: 5000,
        reconnectionAttempts: 5
      }
    })
    .useReactNative()
    .use(reduxPlugin({ onRestore: Immutable }))
    .use(sagaPlugin())
    .connect()

  // Let's clear Reactotron on every time we load the app
  Reactotron.clear()

  // Totally hacky, but this allows you to not both importing reactotron-react-native
  // on every file.  This is just DEV mode, so no big deal.
  console.tron = Reactotron
}
```

**Comment by rmevans9** [comment]
That looks correct to me. Are you sure this code is executing? Is `Config.useReactotron` truthy?

**Comment by AugustoAleGon** [comment]
Yes I am executing the code. Yes it is imported the Config.useReactotron.

But I don't have any connection yet.

**Comment by AugustoAleGon** [comment]
I am using an Android real devices. I was checking the IOS emulator and everything is working sweet. But I don't see any information about how to start in a real Android device.

**Comment by skellock** [comment]
Don't forget to run `adb reverse tcp:9090 tcp:9090` to open up a reverse tunnel from your device back to your host machine.

**Comment by AugustoAleGon** [comment]
ohh Let me check that. So to be clear first I should start:
`adb reverse tcp:9090 tcp:9090`
Then I just run:
`react-native run-android`
in that way?

**Comment by skellock** [comment]
Hopefully you're all sorted.  Lemme know if you're not.

**Comment by AugustoAleGon** [comment]
Great help!

**Comment by vipinagrahari** [comment]
Please add this to Quick start documentation as well.
