### ISSUE TITLE
Typo in plugin-overlay.md (importat)

### ISSUE THREAD

**Issue by siciarek** [infinitered/reactotron#594]
Hi,

There is a typo in the documentation, on the page https://github.com/infinitered/reactotron/blob/master/docs/plugin-overlay.md

You have:
const MyAppWithBenefits = console.tron.overlay(MyApp)

But should be:
const MyAppWithBenefits = Reactotron.overlay(MyApp)

**Comment by skellock** [comment]
Thanks for the report!
