### ISSUE TITLE
Can't connect to the app from Genymotion 

### ISSUE THREAD

**Issue by Hunsu** [infinitered/reactotron#595]
I have seen issues about the app not working in Android and expo. I have tried all the suggested solution but none worked in my case.
The issues I found:
https://github.com/infinitered/reactotron/issues/174
https://github.com/infinitered/reactotron/issues/162
https://github.com/infinitered/reactotron/issues/50

I'm using:
exp: 47.4.4
Genymotion: 2.11.0

**Comment by skellock** [comment]
Bummer.  What are you seeing?  Just not able to establish a connection?

**Comment by Hunsu** [comment]
Yes the app does not establish a connection.  Just to be sure I start the react native packager then expo and finally reactotron. I also tried running reactotron first. How can I debug where it is blocking?

**Comment by Hunsu** [comment]
I tried to debug my issue and find out that reactotron uses the host 'packager.wz-sp9.hunsuexp.xkcd.exp.direct' and that does not work. The host option is ignored in my case. So I added the line in the configure function:

    this.options.host = 'ip of my machine';

and it worked.

**Comment by skellock** [comment]
Sweet!

**Comment by Hunsu** [comment]
The line I added is in the reactotron-core-client package so I think the issue is not resolved.

**Comment by nEdAy** [comment]
Try forwarding that port with adb.

adb reverse tcp:9090 tcp:9090

**Comment by skellock** [comment]
Feel free to open a new issue if you're stuck.  It should be working properly.   It's usually an `adb reverse` tunneling issue.  As in, you've not run it.

**Comment by Hunsu** [comment]
It wasn't working because I was running expo using a tunnel (which is the default). It was fixed when I ran expo using `exp start --localhost`. Maybe add this to the documentation.

**Comment by skellock** [comment]
Nice.  Would you mind adding that for us?
