### ISSUE TITLE
reactotron.log() accepts more one argument

### ISSUE THREAD

**Issue by ArmandoAssuncao** [infinitered/reactotron#596]
Hi,

the `reactotron.log` could accept more than one argument, such as `console.log` make.
the typedef of `console.log` is:
`log(message?: any, ...optionalParams: any[]): void;`

the `.warn` and `.error` could make the same too.

what do you think?

**Comment by slhawkins** [comment]
I would like this as well. When I initially used reactotron.log I assumed it would behave similarly to console.log. It didn't take long before I found this to be incorrect. The problem I see with changing this is that log currently accepts two arguments, the message and a flag that marks the message as important:

```
      log: (message, important = false) =>
        reactotron.send("log", { level: "debug", message },  #!!important),
```

Anyone using `important` would be a bit surprised if this changed. 

For anyone that wants this in the meantime though, I use a custom log function via a plugin I insert at runtime. It's nothing special - only a slight modification from the current log function and it doesn't duplicate console.log exactly by any stretch. However, it works for my purposes...

```
const loggerPlugin = () => reactotron => {
  return {
    features: {
      log: (...args) => {
        reactotron.send('log', { level: 'debug', message: args }, false)
      },
    },
  }
}
```

This is applied like any other plugin:

```
Reactotron.configure({ name: 'Ignite App' })
    .use(loggerPlugin())
    .connect()
```

**Comment by skellock** [comment]
Ya, i screwed up on the interface of the function for sure.  I should have modeled it after `console.log`.   We'll make this the new default in 2.0.  Perhaps introduce a `logImportant()` or `omglog()` if someone wants it to be flagged as important in the UI.

Thanks for the example plugin. I like it.

**Comment by skellock** [comment]
This is now the default interface in `2.0.0-beta.1`.  

`console.tron.log(1, 2, 3, 'omg', 'yay', { a: 1 } )`

Thanks!
