### ISSUE TITLE
How do I start the app on a custom port?

### ISSUE THREAD

**Issue by NullVoxPopuli** [infinitered/reactotron#597]
I know there is the configure block for my react-app. but what about the debug app? I have my server running on 9090, and need to change the reactotron port. :-\

**Comment by skellock** [comment]
That's on the list of features we need to add to the app.

If you're up to it, grab the source code and run the app from `packages/reactotron-app` on the `v.1x` branch.

If your server could change ports, that'd be the easy way out.  :trollface:

**Comment by skellock** [comment]
We're going to roll this into #721 . Thanks!
