### ISSUE TITLE
version 2.0.0-alpha of reactotron-react-js (or native) does not work with reactotron v1.15.0

### ISSUE THREAD

**Issue by kevinverelst** [infinitered/reactotron#603]
When installing reactotron, npm defaults to the latest release: v2.0.0-alpha.1.
The reactotron app you can download is v.1.15.0 and is not compatible with the alpha build.

Just spend 4 hours searching why reactotron could not connect to my react-native application.
I figured it out by creating a default react js project where I got a WebSocket error in the console saying the connection is refused before handshaking.

**Comment by skellock** [comment]
Ok, that's moved back now.  `2.x` lives on the `next` dist-tag.  `1.x` is on `latest` (the default that you get when you `npm install`.

Sorry about this.  :(

**Comment by pisangGoreng** [comment]
Hi.. Im having the same issue, how to solve this? Thanks

**Comment by skellock** [comment]
@pisangGoreng would you mind opening a new issue with some details of the error you're seeing?  Thx!
