### ISSUE TITLE
No connection from Android phone over Wifi - [checked all previous issues]

### ISSUE THREAD

**Issue by AliaMYH** [infinitered/reactotron#608]
Hi Guys, 

I still can't get it to connect over WiFi. I'm using an android phone to run my app on, and I've configured the following: 

```
Reactotron
  .configure({ host: '192.168.1.9' }) // controls connection & communication settings
  .useReactNative() // add all built-in react native plugins
  .connect() // let's connect!

```

I've run : `adb reverse tcp:9090 tcp:9090` also. 

I've tried adding this to configure: this.options.host = 'ip of my machine'; still doesn't work.

I'm not sure what the issue is. It's the correct IP, and the phone and the laptop are on the same wifi.
I've imported ReactotronConfig into my App.js also. Tried it in index.js still doesn't work.

I'm using a Mac, if that makes any difference. Turned off remote debugging because it said to do so in troubleshooting, still no connection.

**Comment by AliaMYH** [comment]
@skellock Sorry to tag you directly, but I can't figure out what the problem is. I've tried almost everything. Do you have any insight?

**Comment by AliaMYH** [comment]
I downloaded it using brew, it's 1.x release. Should it be the 2.0 ?

This is my dependency in package.js : "reactotron-react-native": "^2.0.0-alpha.1"

**Comment by skellock** [comment]
I haven't released the 2.0 app on brew just yet.  I'd recommend staying on `1.x` for now. =)

**Comment by AliaMYH** [comment]
But then do I change my "reactotron-react-native" to the 1.x package? Is that where the connection issue is coming from?

**Comment by skellock** [comment]
Correct.  I think `1.15.0` is the latest `1.x` version.

In `1.x` we used `socket.io` to communicate.  In `2.x` we dropped down to plain-ol `websockets`.

So you can't use the the `2.x` lib to talk to the `1.x` app.  They have to be on the same major version.

From where you are now, if you [grabbed the latest binary](https://github.com/infinitered/reactotron/releases/download/v2.0.0-alpha.1/Reactotron.app.zip), i'd expect it to work.

**Comment by AliaMYH** [comment]
Ok, last question, sorry. I don't know how to change my package dependency .. how do I get the 1.x version?

**Comment by AliaMYH** [comment]
I ran the nom command again, and it works now!! Connection finally! Thank you

**Comment by skellock** [comment]
I just updated the `dist` tag on `reactotron-react-native` to reset it.

Sorry about this hiccup.  It was totally my fault.

**Comment by peacechen** [comment]
Just heads up that `reactotron-redux` is currently at `2.0.0-alpha.1` in case that release also needs to be reverted.
