### ISSUE TITLE
Thank you so much,

### ISSUE THREAD

**Issue by Holybrian** [infinitered/reactotron#615]
For my bachelor final i have to write a whole project from data access, to backend, to web and mobile. Now eventhough i thought my api calls were correct after editing the Cors i had no idea if my token was actually ever stored in my localstorage or asyncstorage correctly.

Your app has saved me tons of hours stack tracing back to see what's going on. 

Thank you so much for an amazing app that i will surely be using for the rest of my professional carrier.

**Comment by skellock** [comment]
Yay! You're most welcome!  Thanks for the kind words!
