### ISSUE TITLE
Can't connect reactotron to real android device by wifi

### ISSUE THREAD

**Issue by armanbabai** [infinitered/reactotron#622]
hi everyone
i try connect to reactotron on wifi but not show anythings.
i tried:

```
import Reactotron from 'reactotron-react-native';
Reactotron
  .configure({
        enabled: true,
  host: '192.168.1.100',  // server ip
  port: 9090
  }) // controls connection & communication settings
  .useReactNative() // add all built-in react native plugins
  .connect() // let's connect!
```

but not worked.

**Comment by skellock** [comment]
Are you running in dev mode?  Are you able to see the react native packager ok?

**Comment by armanbabai** [comment]
@skellock yes enabled dev mod and packager it's ok .

**Comment by skellock** [comment]
What version of `reactotron-react-native` do you have?  What version of the Reactotron App do you have?

**Comment by armanbabai** [comment]
@skellock latest version.

**Comment by skellock** [comment]
React Native 0.54 by any chance?

**Comment by hungdev** [comment]
i get same issue.

**Comment by rmevans9** [comment]
@armanbabai are you still having this issue?

**Comment by micchyboy** [comment]
I'm having the same issue on android studio emulator.

 I'm using react-native 0.55.1. Currently running on API 27 but haven't tried on older versions. I'm not having a connection in Reactotron App.

.configure({
      host: '192.168.254.105', //my current wifi local ip in mac
      port: 9090,
      name: 'Ignite App' 
    })

Any advise sir?

**Comment by skellock** [comment]
What version of the app & libraries do you have installed?

**Comment by hungdev** [comment]
@micchyboy this is my config:

import Reactotron from 'reactotron-react-native'

```
Reactotron
  .configure({ host: '192.168.152.109' }) // controls connection & communication settings
  //.configure() // controls connection & communication settings
  .useReactNative() // add all built-in react native plugins
  .connect() // let's connect!
````

**Comment by apperside** [comment]
I made it work by running `adb reverse tcp:9090 tcp:9090`
