### ISSUE TITLE
GUI style

### ISSUE THREAD

**Issue by msageryd** [infinitered/reactotron#624]
This seems like an awesome tool. I've just installed it and it has already helped me enlighten some problem areas in my app.

It would be really great if there where some style settings for the GUI (I'm on OSX). To my eyes there is too low contrast in the GUI. Especially the grey on black text in the timeline.

It would also be great if the line height could be reduced in the timeline. To me there is way to much whitespace in the list. It looks nice, but for functionality I'd rather have a more compressed list.

**Comment by skellock** [comment]
For theming, a lot of that in place already.  Just not exposed or configurable.

Check out this:

https://github.com/infinitered/reactotron/issues/423#issuecomment-300189059

I could put a drop down box where you could pick from one of the presets.  Didn't seem to be much interest, so I didn't put that time in to expose it.

For whitespace, perhaps I can bring back to the electron +/- zoom levels?  Maybe that would solve the problem without a lot of code.

**Comment by msageryd** [comment]
The +/- was the first thing I tried. It would be awesome to have. I'm on a 32" monitor, so I tend to scale most everything down a notch.

I like dark themes, though. But my eyes need a bit more contrast to feel good.
