### ISSUE TITLE
Types missing for Reactotron.createStore(rootReducer, compose(middleware))

### ISSUE THREAD

**Issue by henrikra** [infinitered/reactotron#636]
createStore is missing TypeScript types https://github.com/infinitered/reactotron/blob/f184b5dc621b213c79efd71805e26a668da901f9/docs/plugin-redux.md#configuring

I am getting TS error when importing `import Reactotron from 'reactotron-react-native';` and using `Reactotron.createStore(reducers, applyMiddleware(sagaMiddleware))`

**Comment by Here21** [comment]
+1

**Comment by skellock** [comment]
Closing in favour of 591.  Just so there's one spot for this.  I really want plugins to be typed as well!
