### ISSUE TITLE
Update Reactotron homebrew cask

### ISSUE THREAD

**Issue by konstantin-mohin** [infinitered/reactotron#648]
Could you please update it, since we still have an old 1.14.0 version.
 
Thanks for your good work!

**Comment by skellock** [comment]
That's the latest version.

2.0 is coming in shortly.  We're just fixing some last minute issues.  

I promise I'll push up to `brew` once that's finished.

You'll have to download from [the releases](https://github.com/infinitered/reactotron/releases) this in the meantime if you're using 2.0.

Sorry about that!

Stay tuned!
