### ISSUE TITLE
Ajax Response Weird 

### ISSUE THREAD

**Issue by idcmsbeta** [infinitered/reactotron#654]
![reactotronweird](https://user-images.githubusercontent.com/38270090/39670724-57f8cddc-513d-11e8-969d-f38fe36ca0a6.png)

Reactotron version :1.15.0
React Native Version :0.553
Reactoron client(js) version : ^1.14.0
** latest reactotron client 2.0 also dont work.. Empty.
platform:mac

** I don't change any code, previously i can see ajax request. I have update all bower also.

**Comment by skellock** [comment]
Reactotron 2 requires the `reactotron-react-native@next` version because it hasn’t been released yet.

Apparently react-native’s new blob support has changed some stuff. I haven’t seen this in action yet though.

What does the yellow box say?

What does your fetch call look like?

**Comment by idcmsbeta** [comment]
i'm not sure i'm updating anything.. but it kinda disappear now.   

Apparently react-native’s new blob support has changed some stuff ?
  Sorry. I'm kinda not understand. It is react-native introduce new thing again ? I really scare if the create new thing each patches without proper note.

my fetch 
 ```
async function post(url, params, fileUrl) {
    let securityToken = await AsyncStorage.getItem('securityToken');
    let data = new FormData();
    Object.keys(params).forEach((key) => {
        if (params[key] instanceof Date) {
            data.append(key, value.toISOString())
        } else {
            data.append(key, String(params[key]))
        }
    });
    const fetchOptions = {
        method: 'POST',
        headers: {
            'Accept': 'application/json',
            'securityToken': securityToken ? securityToken : '',
            'UserAgent': os
        },
        body: data,
        timeout: 6 * 1000
    };
    return fetch(url, fetchOptions)
        .then(checkStatus)
        .then(parseJSON)
}
```
 A full gist at [https://gist.github.com/idcmsbeta/3d055bbd1f4c9c765dfbd4946961f5c0](url)

**Comment by skellock** [comment]
Ya, blob support landed recently (0.53? 0.54?) and with it, changes to the network stack. 

I’ll. Have to take a closer look at posts with for data and figure out what changed and how to fix it.

Thx for the code.  That makes it much easier.

**Comment by rmevans9** [comment]
Blob support landed in beta 4. Please let us know if this is still an issue!

**Comment by idcmsbeta** [comment]
i will check up later . I will give the respond 👍

**Comment by ecerroni** [comment]
I confirm it know works as supposed.

![working](https://user-images.githubusercontent.com/11174327/41191813-59f9d90a-6bf5-11e8-96bb-6f28fc1b41c9.png)

**Comment by gorvinsky** [comment]
I'm still having this issue in reactotron-react-native@1.14.0

Testing on real Android device and develop on Windows.

![capture](https://user-images.githubusercontent.com/22973155/42496221-ef7d0432-8457-11e8-8cba-ae95eb527247.PNG)

**Comment by ecerroni** [comment]
@gorvinsky 

Indeed you need at least reactotron-react-native@2.0.0-beta.4 to make it work.

**Comment by gorvinsky** [comment]
@ecerroni After installing reactotron-react-native@2.0.0-beta.4 without modifying the codes, now it can't detect any activity at all.

**Comment by ecerroni** [comment]
@gorvinsky 

Right, I forgot to say that the new v2 beta desktop client is needed as well. You can download it here:
https://github.com/infinitered/reactotron/releases

**Comment by gorvinsky** [comment]
It's working now Thanks a lot @ecerroni
