### ISSUE TITLE
Redux-observable (epics) integration

### ISSUE THREAD

**Issue by tonyxiao** [infinitered/reactotron#670]
Given reactotron integrations with saga, do people have any thoughts on integrating with redux-observable?

**Comment by skellock** [comment]
I’ve never used it before but if you need help building a plugin, I can help!

**Comment by danielidt** [comment]
i was curious about it too but i havent used redux-observable yet, that being said i assumed plugging into redux would be enough to show state changes. what additional features would plugging into redux observable bring?

**Comment by skellock** [comment]
Closing as this is something we won't be building here... would def support anyone building this plugin tho!

**Comment by brettdh** [comment]
I'm interested in working on this, but I'd like to check here first to see if any of y'all have started already.

**Comment by rmevans9** [comment]
I don't think anyone has @brettdh. All you! A worthwhile note is that we are moving some of the code around to different repos but I can help out working through that once you have stuff worked out.

Thanks!

**Comment by vitto-moz** [comment]
It seems redux-observables epic's end actions are not tracked in a timeline
action "LOGIN" which has been dispatched from a component is visible
and "LOGIN_SUCCESS" which is out action from a "loginEpic" is not visible in a timeline
