### ISSUE TITLE
Can't connect app running on device (iOS)

### ISSUE THREAD

**Issue by imdadahad** [infinitered/reactotron#671]
I followed the instructions to get my host machine's ip (from ifconfig) and then adding this into the reactotron config but it doesn't seem to work.

```
Reactotron.configure({ host: "192.168.0.12"})
Reactotron.connect()
```

**Comment by rmevans9** [comment]
Can you also confirm the version of the `reactotron-app` you are running?

**Comment by siggy-h** [comment]
Ahhhh! adding -> Reactotron.configure({ host: "xx.xx.xx.xx"})
Fixed my issue, not able to connect running with android simulator. thanks!
