### ISSUE TITLE
Upgrade app to Electron 2

### ISSUE THREAD

**Issue by skellock** [infinitered/reactotron#684]
We're still on 1.8.6.  Let's upgrade to 2.0 and see if there's any problems.

**Comment by skellock** [comment]
oh snap... electron 3 is now in beta 1.

**Comment by morenoh149** [comment]
want to wait for electron 3?

**Comment by skellock** [comment]
I'm in no rush. 🤷‍♂️
Unless someone really wants to do it.  🥂

**Comment by skellock** [comment]
Closed in favour of #782  😈
