### ISSUE TITLE
Custom commands should send to 1 device

### ISSUE THREAD

**Issue by skellock** [infinitered/reactotron#687]
Currently if I send a custom command, it gets sent to every device.

Let's change that to only send to the active device.

This is in 2.0.0-beta.5.

**Comment by rmevans9** [comment]
Things that are needed to make this fix a reality:

https://github.com/infinitered/reactotron/blob/master/packages/reactotron-core-server/src/reactotron-core-server.ts#L273 - Update to be able to send to a specific `clientId` as well all clients as it does now.

https://github.com/infinitered/reactotron/blob/master/packages/reactotron-core-server/src/reactotron-core-server.ts#L327 - Update to pass through a `clientId` if passed into it.

https://github.com/infinitered/reactotron/blob/master/packages/reactotron-app/App/Stores/UiStore.js#L369 - Pass the `SessionStore` `selectedConnection` `clientId` (note: `SessionStore` owns the reference to `UiStore` so we may need to pass the `selectedConnection` in via the caller which is here: https://github.com/infinitered/reactotron/blob/master/packages/reactotron-app/App/Stores/UiStore.js#L225 but that might still not provide access to it. Will need to investigate)
