### ISSUE TITLE
Clearing console clears all devices

### ISSUE THREAD

**Issue by skellock** [infinitered/reactotron#689]
<img width="81" alt="image" src="https://user-images.githubusercontent.com/68273/41164503-5187826e-6b09-11e8-949d-125eae8ab2f0.png">

When i click the trash can here, it'll clear every connected device.

It'd be nice if it'd just clear the active device.

**Comment by rmevans9** [comment]
https://github.com/infinitered/reactotron/blob/master/packages/reactotron-app/App/Stores/UiStore.js#L340 This needs to be something more like this: 

https://github.com/infinitered/reactotron/blob/master/packages/reactotron-app/App/Stores/SessionStore.js#L191
