### ISSUE TITLE
cant connect it with expo

### ISSUE THREAD

**Issue by Kida007** [infinitered/reactotron#690]
I have been using **Expo** and a **physical device**, tried to Implement Reactotron, followed the guide still cant achieve any result. the reactotron mac app shows no connections ! even tried all similar issues solutions .

 so First I tried :
Reactotron App : v1.14.0
reactotron-react-native: v1.14.0

also, I tried : 
Reactotron App : v2.0.0-beta.5
reactotron-react-native: v2.0.0-beta.5

Implementation this in App.js  which is the rootmost Component : 
`
Reactotron.configure({ port:19000, host:'192.168.0.106'}).useReactNative().connect()
`
Also tried Implementing this in componentWillMount Section . 

But there is no response in The Reactotron App.

**Comment by rmevans9** [comment]
The port that the app listens to is 9090. Can you try and point it at that port?

**Comment by Kida007** [comment]
`Reactotron.configure({ port:9090, host:'192.168.0.106'}).useReactNative().connect() `

tried this! sadly no success .

**Comment by Kida007** [comment]
hah I solved it ,  I removed the **host**   from configure  function and port forwarded adb .

so it looks like :
`Reactotron.configure({ port:9090}).useReactNative().connect()
`
and 

`adb reverse tcp:9090 tcp:9090 (also tried earlier though)
`
The problem was , even after port forwarding and providing correct local machine IP , it was not able To connect To the machine. By default it is taking localhost which is equivalent , but it is working !

Great Tool though :)

**Comment by rmevans9** [comment]
Glad you got this worked out. Closing since you got it solved.
