### ISSUE TITLE
How to use storybookSwitcher?

### ISSUE THREAD

**Issue by r0st1kuzh** [infinitered/reactotron#692]
Do I need to launch storybook? or Packager?
When I run 'npm run storybook' it does not react on switching in Reactotron.

**Comment by rmevans9** [comment]
You can find the documentation that we have (could probably be better...) here: https://github.com/infinitered/reactotron/blob/master/docs/plugin-storybook.md

One thing not mentioned in there currently is that `storybook` actually provides a switch (`--skip-packager`) to not run the packager which you will typically want to do. So once the code changes are in the flow would be to start up the RN packager like normal, start storybook with the `--skip-packager` flag and then use the toggle within `reactotron`

If you need further assistance please let us know either here or hop on the community slack (link in readme)
