### ISSUE TITLE
Make Subscriptions Failsafe?

### ISSUE THREAD

**Issue by kevinvangelder** [infinitered/reactotron#7]
Subscribing incorrectly can crash the app.

**Comment by lucasfeliciano** [comment]
More info about this would be good so people can try to fix it.

**Comment by kevinvangelder** [comment]
Subscribing to a non-existent portion of the state tree causes otherwise healthy apps to crash. I'm not yet very familiar with the code, but I suspect this could be remedied by surrounding the subscriptions on the client side with a try/catch.
