### ISSUE TITLE
Possible Unhandled Promise Rejection with sagaPlugin enabled

### ISSUE THREAD

**Issue by rikur** [infinitered/reactotron#702]
Ok this is tricky to track down.. whenever I enable sagaPlugin, I get YellowBox warning about unhandled promise rejection. However, it seems like it somehow bubbles up from an React-Native invariant violation handling.. and the error message itself is pretty cryptic:

```TypeError: Cannot read property 'UNKNOWN' of undefined```

If I disable sagaPlugin setup, the YellowBox warning is gone.

**Comment by rikur** [comment]
Oh! This thing works without Remote Debugging. Magic!

Now I have a slightly less globbered error message:
<img width="645" alt="screen shot 2018-06-15 at 8 10 28 am" src="https://user-images.githubusercontent.com/4004/41467265-ce7b7176-7073-11e8-9f27-7dc0d09633d6.png">

**Comment by rikur** [comment]
```
    "reactotron-react-native": "^1.14.0",
    "reactotron-redux": "^1.13.0",
    "reactotron-redux-saga": "^1.13.0",
```

BTW this Reactotron is amazing. Going to give v2 a try tomorrow.

**Comment by rikur** [comment]
Yeah that seems to fix it. Thanks!

**Comment by gillessed** [comment]
The way this error appeared for me is to pass a non-generator callback to one of the `takeEvery` family of effects that returns `undefined`.

If you find places in code where you might do that, you have have it return `Promise.resolve()` or something along those lines, you can get rid of the error.

Not having to do this in the first place would be far superior, but this is a possible workaround.
