### ISSUE TITLE
Increase contrast on font

### ISSUE THREAD

**Issue by matjemeisje** [infinitered/reactotron#719]
Please increase the contrast on the font, or add an option to switch to a light theme. I know you've commented somewhere else that you did not implement it because of low interest. But I would think that saving even one person's eyes makes it worth the effort. And as my eyes are definitely suffering from your imho poor design choice I must employ you: please, please, PLEASE do something about this.

**Comment by skellock** [comment]
>  your imho poor design choice

I can't possible guess what you'll like.  Can you make a PR with a theme you're happy with?

**Comment by skellock** [comment]
@rmevans9 suggested that we could read the colors from a config file... so we're going to put #721 in place to make this easier for everyone.

**Comment by rdewolff** [comment]
While working early morning in the dark, I must say that I have a similar issue. The contrast of the between the background and the fonts color is not big.

Maybe adding a simple option to set the the four main colors would do it?
Allowing to change :
- background color
- menu color
- font color
- highlighted font color

Maybe a simple textarea with HEX separated with values would do it?

Just my 2 cents :)

Cheers!

**Comment by marklanhamhc** [comment]
Would also be useful to choose your own font, like a monospaced font.
