### ISSUE TITLE
Error: Unknown named module:'NativeModules' RN 0.56.0

### ISSUE THREAD

**Issue by szenciattila** [infinitered/reactotron#724]
Update to React Native 0.56.0 causes following error:

![screenshot_2018-07-05-19-05-18](https://user-images.githubusercontent.com/32485179/42338049-de945918-8088-11e8-9610-73e99c02f677.png)

**Comment by FLGMwt** [comment]
Error seems to be coming from rn-host-detect.

I'm locally patching rn-host-detect with a closed PR version of the repo that was an attempted fix of what looks like a similar issue: https://github.com/MaxToyberman/rn-host-detect/blob/35a45bb8424f748f16cc9da0402df144ce11385f/index.js

I won't pretend I know what's going on, but it works for me 🙃.

**Comment by skellock** [comment]
Thanks for heads up! i havent tried 0.56.0 just yet. The first few days of .0 releases are the most fun.

**Comment by FLGMwt** [comment]
Np! Sorry I was lazy and didn't file an issue when I saw it in rc-4.

**Comment by rmevans9** [comment]
Confirmed that putting in the suggested patch fixes the issue. Thanks for that lead @FLGMwt. I am going to look at options for how to solve this in a nice way without depending on a random commit in a github fork.

**Comment by FLGMwt** [comment]
FYI, it looks like this has been fixed in rn-host-detect: https://github.com/jhen0409/rn-host-detect/pull/5. Maybe we can update that to latest (1.1.4) and give it a shot?

**Comment by SparkleFaerieCoder** [comment]
Anyone have any luck with the latest version? I tried giving the update a shot. It keeps bombing in iOS when I'm not debugging.

**Comment by skellock** [comment]
This should be fixed in 2.0 via #730. Are y'all running `reactotron-react-native@2`?

**Comment by ianoshorty** [comment]
Just in case someone else runs into this issue even after upgrading to v2.0 (full release) as I did, dont forget to run the "god clean" command:

```
rm -rf $TMPDIR/react-* && rm -rf $TMPDIR/haste-map-react-native-packager-* && rm -rf $TMPDIR/metro-bundler-cache-* && watchman watch-del-all && rm -rf ios/build && rm -rf node_modules/ && npm cache clean --force && npm i && npm start -- --reset-cache
```

**Comment by redbluenat** [comment]
I just update reactotron-react-native to 2.0.0 and works 👍
