### ISSUE TITLE
State snapshot button not working

### ISSUE THREAD

**Issue by skellock** [infinitered/reactotron#726]
If you press the download state button it doesn't work.

But if you press Command + S it does.

🤦‍♂️ 

sorry

**Comment by AdrianMrn** [comment]
Just encountered this one again btw

**Comment by rmevans9** [comment]
There is a fix already from a few weeks ago but I didn't end up getting it released because the CI build failed. Attempting again.

**Comment by rmevans9** [comment]
version 2.6.1 resolves this issue.
