### ISSUE TITLE
Module 'rn-host-detect' does not exist in Haste module map

### ISSUE THREAD

**Issue by andreaskarantzas** [infinitered/reactotron#739]
![simulator screen shot - iphone 8 plus - 2018-07-10 at 10 18 59](https://user-images.githubusercontent.com/16306047/42499480-2ee83c3c-842f-11e8-9503-7e76f2d456ae.png)

React-native-version: 0.56.0
Reactotron-version: 2.0.0-beta.11

Started with version beta.10 but got the error 'unknown named module: NativeModules' so I checked the issues and the commits and saw that there should be a commit-fix in version beta.11 but then this occurs.

**Comment by hungdev** [comment]
i get same issue.

**Comment by skellock** [comment]
Hmm... this should be resolved in `2.0.0-beta.11`.  I wonder if `metro` is caching this?

Try following the steps in the red screen.  

I suspect that there's a metro collision on that `rh-host-detect` file.  It's showing up in two places and pulling in the wrong one.

**Comment by ikhsanalatsary** [comment]
Worked for me as @skellock mentioned

**Comment by skellock** [comment]
Ya... `metro` doesn't work quite the same way as the other js bundlers do... 😭 😭 😭 🤷‍♂️ 😭 😭

**Comment by hungdev** [comment]
i ran:
watchman watch-del-all
after that, I delete node_modules, then run npm i
then run npm start -- --reset-cache
but it still error:
<img width="391" alt="screen shot 2018-07-14 at 1 14 02 pm" src="https://user-images.githubusercontent.com/12009276/42721608-de9bc9ec-8767-11e8-8795-78372f859cd8.png">

**Comment by skellock** [comment]
What version of reactotron-react-native are you using?

**Comment by hungdev** [comment]
Oh, i updated to newest version. it fine. Thank you so much. Please close this issues.

**Comment by skellock** [comment]
Sweet!
