### ISSUE TITLE
support multiple args in log()

### ISSUE THREAD

**Issue by morenoh149** [infinitered/reactotron#740]
vanilla console.log has the function signature `console.log([data][, ...args])`
meaning you can use it like
```es
const count = 5;
console.log('count:', count);
// Prints: count: 5
```

Currently Reactotron only prints the first item.
```es
const count = 5;
Reactotron.log('count:', count);
// Prints: count: 
```
Make Reactotron.log conform. Yes I'm aware you can use an object https://github.com/infinitered/reactotron/blob/master/docs/quick-start-react-native.md#hello-world

fwiw I've been doing `Reactotron.log({'count': count});`.

**Comment by skellock** [comment]
This was one of the changes we made in Reactotron 2.  🎉
