### ISSUE TITLE
C++ exception in 'nativeFlushQueueImmediate,Malformed calls from JS: field sizes are different.

### ISSUE THREAD

**Issue by TheIdhem** [infinitered/reactotron#742]
hey there,
i'm new in working with reactotron,
i've done what ever you put on the tutorial of the reactotron but i've got this error and i don't have any idea about this.please help me
thanks

here is the ReactotronConfig.js file:

import Reactotron from "reactotron-react-native";
Reactotron.configure() // controls connection & communication settings
  .useReactNative() // add all built-in react native plugins
  .connect(); // let's connect!

I import this in index.js because of the react-native in version  "^0.55.4":
import "./app/helpers/ReactotronConfig";

![screen shot 2018-07-11 at 12 43 48 pm](https://user-images.githubusercontent.com/31737620/42559147-8a642ede-8508-11e8-8f57-ebf429f4102a.png)

**Comment by CapitanRedBeard** [comment]
I don't have an answer but I'm getting the same error (Not related to reactotron) however I am using websockets and feel this error might be related to that.

**Comment by skellock** [comment]
You'll see this if the react-native js version doesn't match the native version.

So, it might be worth running the dependency gauntlet ...

```sh
rm -rf node_modules
rm -rf ios/build
yarn
cd android
./gradlew clean
cd ..
```
:cold_sweat:

**Comment by skellock** [comment]
Any luck re-installing dependencies?

I find that when you upgrade `react-native`, there's sometimes (not always!) little bullies like this that jump out of the bushes and steal your lunch money.
