### ISSUE TITLE
Storybook and Overlay

### ISSUE THREAD

**Issue by Aletagro** [infinitered/reactotron#743]
I want to ask
There are two plugins: Storybook and Overlay
Do they work together? Can I use the overlay functionality in my storybook?
Separately, they work fine for me, but together they do not

**Comment by skellock** [comment]
Ya, I don't think I've ever tried them together. 

I guess, it should be able to work, you'd just have to make sure that the Overlay is a parent element of the storybook.

Can you paste some of your code in here and show me what your setup looks like?

**Comment by Aletagro** [comment]
Thank you so much! This solved my problem
