### ISSUE TITLE
Reverse the log order

### ISSUE THREAD

**Issue by tjbenton** [infinitered/reactotron#755]
Currently the log order is in reversed order from the way it it's written and it's very confusing to see it in reverse order especially when debugging complicated things.

It would be nice for this to be changed to match other consoles, or at least have a option for this.

![screen shot 2018-07-20 at 11 02 28 am](https://user-images.githubusercontent.com/4776422/43009730-6e8b1ea6-8c0c-11e8-9480-9cbd052ee29c.jpg)

in the chrome console this is what you get, and it's what I expected with Reactotron 

![screen shot 2018-07-20 at 1 11 58 pm](https://user-images.githubusercontent.com/4776422/43015821-a67a8434-8c1e-11e8-8219-3732a7834862.jpg)

**Comment by anmead** [comment]
This would be great 👍

**Comment by rmevans9** [comment]
https://github.com/infinitered/reactotron/blob/master/packages/reactotron-app/App/Lib/commands.js#L32

This is where the reversing happens. I would suggest that we would want some sort of toggle for this (maybe in the config file @skellock has been playing around with). Once the config is in place I am sure a PR would be accepted!

**Comment by skellock** [comment]
There's a bunch of things hinging on that config file.  I just need to sit down and create it.  It'll take an hour.  (lol, still haven't learned my lesson about saying 💩 like that)

**Comment by JulienMalige** [comment]
Can be closed :) @rmevans9 @skellock

**Comment by rmevans9** [comment]
This has been released. Thanks!
