### ISSUE TITLE
Line tracing on logging

### ISSUE THREAD

**Issue by alfie-ab** [infinitered/reactotron#760]
Hi, first of all thanks for a great library.

Is there a simple way to add line tracing to the console.logs? At the moment the only workaround I've found is customising the config file to throw an error each time console.log is called which adds a line trace, but then gets confusing when an actual error is thrown. Is there a better way to add line tracing?

**Comment by skellock** [comment]
🍾  thanks for the kind words!

No.  That isn't possible right now.  But, we can make it possible... 

Are you using `react-native` or `react`?

**Comment by alfie-ab** [comment]
Ah perfect! 

We're using react-native (version 0.55.0)

**Comment by skellock** [comment]
Tracking in #292
