### ISSUE TITLE
Typescript Map value is not displayed in State

### ISSUE THREAD

**Issue by sregg** [infinitered/reactotron#761]
Hi 👋,

I'm using Reactotron with a React-Native project.
Everything works like a charm except for one of my store properties that's a TS Map.
The value in the State tab is not showing at all, even though I can debug it and see its value properly.

![image](https://user-images.githubusercontent.com/1479283/43103714-0c5bf33e-8e9d-11e8-9a32-a028967d0aaf.png)

Here's my questionnaire state:

```
export default interface IQuestionnaireState {
  loading: boolean;
  errorMessage: string | null;
  questions: IOnboardingQuestion[];
  savingAnswer: boolean;
  saveAnswerErrorMessage: string | null;
  // Map<question id, answer id>
  selectedAnswers: Map<string, string>;
}
```

Not sure if this is a TS issue or Reactotron one...
Feel free to close if not relevant at all...

**Comment by skellock** [comment]
Is it `selectedAnswers`?  It shows up empty even though you know you have data within it?

Typescript disappears in runtime, so I don't think it's a typescript issue.

es6 maps work fine... i just tested this:

```js
      const x = new Map<string, string>()
      x['hello'] = 'world'
      console.tron.log({ yo: x })
```
And it logs properly.

![image](https://user-images.githubusercontent.com/68273/43105728-e99d26fe-8ea3-11e8-9fd2-38c614b22163.png)

I notice this is in your subscriptions... are you using `mobx-state-tree` or `redux` or something else?

**Comment by sregg** [comment]
I'm using redux

**Comment by skellock** [comment]
Can you post some more code?  Maybe your reducer?  

Are you sure you're saving stuff in that map?   If you were to log out the length of the map, is it > 0?

**Comment by sregg** [comment]
I tried with a simple

```
const x = new Map<string, string>();
x.set('hello', 'world');
Reactotron.log({ yo: x });
```

and get this log in Reactotron:

![image](https://user-images.githubusercontent.com/1479283/43106028-05d628a6-8ea5-11e8-8660-9161e38c7425.png)

**Comment by sregg** [comment]
If I do this:

```
const map = new Map<string, string>([['hello', 'world']]);
Reactotron.log({ map });
const hello = map.get('hello');
Reactotron.log({ hello });
```

I get this:

![image](https://user-images.githubusercontent.com/1479283/43106611-5e16abf6-8ea7-11e8-832a-9b1cf4056436.png)

But if I use the regular `console.log()`:

```
const map = new Map<string, string>([['hello', 'world']]);
console.log({ map });
const hello = map.get('hello');
console.log({ hello });
```

I see the object:

![image](https://user-images.githubusercontent.com/1479283/43106631-84f43b62-8ea7-11e8-9c91-8ba41aac43e1.png)

**Comment by skellock** [comment]
Ya something is off here for sure. The [way we serialize](https://github.com/infinitered/reactotron/blob/master/packages/reactotron-core-client/src/serialize.ts#L50) doesn't seem to take into account maps properly when using set.

Thanks for the detective work. I appreciate that.

**Comment by rmevans9** [comment]
This is _kinda_ fixed in the latest version of `reactotron-core-client` (and thus `reactotron-react-native` and `reactotron-react-js`). I say kinda because it ships each map item as an array with the first item being the key and the second being the value. There might be a good argument for trying to detect a map better but I am calling this "good enough" for now.

**Comment by doublejosh** [comment]
I've had the same problem in core React. Map changes saved in state don't trigger re-renders like primitive data. Had to look like this...

```
const [myList, setMyList] = useState<Map<string, MyThing>>(new Map())

const updateMap = (k: string, v: Thing) => {
  setMyList(myList.set(k, v))
  forceUpdate()
}

const [, updateState] = React.useState<object>()
const forceUpdate = useCallback(() => updateState({}), [])
```
