### ISSUE TITLE
Update the react-native quick start guide

### ISSUE THREAD

**Issue by skellock** [infinitered/reactotron#763]
The [quick start guide](https://github.com/infinitered/reactotron/blob/master/docs/quick-start-react-native.md#configure-reactotron-with-your-project) has a section called "Advanced" which recommends people use the individual plugins.

I think we should delete that section and replace it with instructions on how to use the parameters of `.useReactNative()`.

For example you can disable parts entirely by specifying `false`:

```js
.useReactNative({
  asyncStorage: false
})
```

I find this way simpler rather than including multiple plugin functions.

**Comment by rodrigoelp** [comment]
Hello, last PR of the day... I promise!

I've edited the documentation based on our conversation #765
