### ISSUE TITLE
console.tron.display not working in Ignite Bowser

### ISSUE THREAD

**Issue by codeithuman** [infinitered/reactotron#768]
On the second screen of a newly Ignited Bowser app, not all logs are displayed when pressing the "Demo Reactotron" button. 

Based on the Ignite generated code found [here](https://github.com/infinitered/ignite-ir-boilerplate-bowser/blob/e22bb21824e05ff36d5ddc3b106fcd8ad4d6692e/boilerplate/src/views/example/second-example-screen/second-example-screen.tsx#L85), and after additional testing, it appears `console.tron.display()` is not working.

**Comment by skellock** [comment]
oh noes!  do you have any more details?  Was there an error?  I use `console.tron.display` every day.

![image](https://user-images.githubusercontent.com/68273/43288080-db164a90-90f4-11e8-8585-ae9d6fb791d7.png)

I wonder what's going wrong?

**Comment by skellock** [comment]
any news here @codeithuman ?
