### ISSUE TITLE
Creates new connection on every refresh

### ISSUE THREAD

**Issue by pekq** [infinitered/reactotron#770]
![image](https://user-images.githubusercontent.com/4521827/43533955-cde647de-95be-11e8-802f-4c26091d9d97.png)

I find the new multiple connection feature a pain to use as on every browser page refresh it creates a new connection. User must then manually switch to the newest connection from Reactotron. I wonder if this is intentional or bug?

Dependencies:
```
    "reactotron-apisauce": "2.0.0",
    "reactotron-react-js": "2.0.0",
    "reactotron-redux": "2.0.0",
    "reactotron-redux-saga": "2.0.0"
```

Setup:
```
import Config from './DebugConfig'
import Reactotron from 'reactotron-react-js'
import Immutable from 'seamless-immutable'
import { reactotronRedux as reduxPlugin } from 'reactotron-redux'
import tronsauce from 'reactotron-apisauce'
import sagaPlugin from 'reactotron-redux-saga'

if (Config.useReactotron) {
  Reactotron
    .configure({ name: '☠☠' })
    .use(reduxPlugin({ onRestore: state => Immutable(state) }))
    .use(sagaPlugin())
    .use(tronsauce())
    .connect()
    .clear()

  console.tron = Reactotron
} else {
  console.tron = {
    log: () => false,
    warn: () => false,
    error: () => false,
    display: () => false,
    image: () => false
  }
}
```

**Comment by skellock** [comment]
Nope that's a bug.  

We'll need to add [similar id storage](https://github.com/infinitered/reactotron/blob/6559243cbe0068533c9172ae434762e5eb8013e8/packages/reactotron-react-native/src/index.js#L46-L50) over in `reactotron-react-js`.

**Comment by Ventronik** [comment]
I am still having this problem. I reinstalled Reactotron, and updated my npm package.

Any advice?

**Comment by ruddell** [comment]
@Ventronik This was fixed an hour ago so it's not in a release yet.

**Comment by michal-th** [comment]
I suddenly started to have this issue with 2.17.0 , with React Native.

My setup:

`import Reactotron from "reactotron-react-native";
import { reactotronRedux } from "reactotron-redux";

const reactotron = Reactotron.configure({ name: "MyApp" })
  .useReactNative()
  .use(reactotronRedux())
  .connect();

export default reactotron;`

**Comment by jeancabral** [comment]
Thanks! Solve me problem

**Comment by pedrocarlos-ti** [comment]
If you don't want install or you don't use AsyncStorage in your application, you can use AsyncStorage instead.

`
import Reactotron from 'reactotron-react-native';
import { AsyncStorage } from 'react-native';

if (__DEV__) {
  const tron = Reactotron.configure({ host: '10.0.63.160' })
    .useReactNative()
    .setAsyncStorageHandler(AsyncStorage)
    .connect();

  tron.clear();

  console.tron = tron;
}
`
This works for me.

**Comment by pedrocarlos-ti** [comment]
If you don't want install or you don't use AsyncStorage in your application, you can use AsyncStorage instead.

```
import Reactotron from 'reactotron-react-native';
import { AsyncStorage } from 'react-native';

if (DEV) {
const tron = Reactotron.configure({ host: '10.0.63.160' })
.useReactNative()
.setAsyncStorageHandler(AsyncStorage)
.connect();

tron.clear();

console.tron = tron;
}```

This works for me.

**Comment by rmevans9** [comment]
This will only work until you upgrade to react-native 0.60.x or is it 0.61.x? AsyncStorage is gone from react-native in the latest version

**Comment by pedrocarlos-ti** [comment]
> This will only work until you upgrade to react-native 0.60.x or is it 0.61.x? AsyncStorage is gone from react-native in the latest version

I use with react-native version 0.61.1 and works fine.

**Comment by rmevans9** [comment]
Ah - I guess they haven't removed it yet. It will be going away at some point:

https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#deprecated-2

**Comment by anastely** [comment]
> > This will only work until you upgrade to react-native 0.60.x or is it 0.61.x? AsyncStorage is gone from react-native in the latest version
> 
> I use with react-native version 0.61.1 and works fine.

@pedrocarlos-ti If i want to see any logs in it after i open debug mode it appears on browser, not in reactotron! I can't see any logs just "Connection"
