### ISSUE TITLE
Add a component inspector

### ISSUE THREAD

**Issue by tjbenton** [infinitered/reactotron#775]
It would be really nice if you could inspect elements directly in reactotron like you can using  [react-devtools](https://www.npmjs.com/package/react-devtools). This way you can do all your debugging in one place instead of having to run a separate command and have it open in a separate window.

**Comment by skellock** [comment]
We're not quite setup for this kind of integration just yet unfortunately.  The react-devtools requires chrome support I believe.

We are, however, reworking our internals for a v3 and will keep this in mind.

Personally, I'd love to see this be a thing.
