### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by preko96** [infinitered/reactotron#781]
After updating to 2.1 I receiving a regeneratorRuntime error in reactotron-react-js/dist/index.js : getClientId() ---> regeneratorRuntime is not defined.

Not sure what can cause this as this not occurs at all time. (seems totally random)

**Comment by skellock** [comment]
Hmmm... 

We could change that from [async](https://github.com/infinitered/reactotron/blob/master/packages/reactotron-react-js/src/index.js#L39) to `return new Promise`.  

Might be easier to do that rather than mess around with babel.  😆

**Comment by skellock** [comment]
I was able to reproduce this.

Bump your version of `reactotron-react-js` to `2.1.1` in your project and give that another shot.  

Thanks for the report!

**Comment by cyveros** [comment]
@skellock I was able to reproduce this on `reactotron-react-native`@2.1.0 as well. Can you please post a fix for that repo as well?

**Comment by skellock** [comment]
@cyveros oh?  would you be able to open a new issue with some instructions (or a repo) showing the problem?  thx!
