### ISSUE TITLE
Adding a new plugin

### ISSUE THREAD

**Issue by danReynolds** [infinitered/reactotron#802]
Hello there! Our team is looking achieve a similar goal to what Reactotron already provides for things like Redux or mobX but for a different one of our libraries. We are exploring our own standalone electron app but are thinking about just making our own plugin(s)/tab in Reactotron for this use case since we see it has a plugin system. Looking at the ongoing work such as https://github.com/infinitered/reactotron/pull/796, would you say it is a good time to go for forking this project and adding a plugin with the possibility of it becoming a community plugin later given the current state of plugins for Reactotron?

Or is it likely the architecture is going to significantly change in regards to adding plugins and for now we hold off and use our own standalone application. I don't see much documentation in regards to adding plugins, especially with visual components like its own tab etc. Our goal would to have a visual interface for some of the functionality of the library and communicate back and forth with the app similar to the state tab that currently exists.

**Comment by rmevans9** [comment]
Hello @danReynolds! I am glad you guys are considering using Reactotron to help with your debugging needs. 

That PR you link is still very much in flux so we have not written any documentation for it yet as there are changes to how plugins are going to work coming (I know this to be true as I am currently working on those changes). The ability to add UI to reactotron is also something we have planned but not completed yet. I hope that within the next few weeks we will be in a place that we can start having at least some sort of documentation for the plugin system started. One of the goals of the plugin system I am hoping for is that they will be able to live outside of the current reactotron repository and be able to be simply installed along with the core reactotron app and have reactotron find the plugin and start using it.

That said one of the goals of V3 is to pivot away from an electron app and instead ship a node/express based web server that you can access via a browser that contains similar UI to what is available now. There are talks around how to still ship a standalone app (or show users how to create one that wraps the website) but we are not there yet. 

The main driving reason for dropping electron is just the weight and complexity it brings to the project. We have found over time that the code within reactotron has grown fairly complex and not very approachable from a possible contributors point of view. We are hoping with V3 we can change that and make it better all at the same time.

If you want to chat with either myself or @skellock about the plugin you guys are thinking about making feel free to hop on the Infinite Red community slack and find us in both `#reactotron` (general/support reactotron chat) and `#reactotron-dev` (chat specific to the development of reactotron)

**Comment by danReynolds** [comment]
Thanks, I'll follow up via the community slack.
