### ISSUE TITLE
CAN'T CONNECT ON ANDROID

### ISSUE THREAD

**Issue by karlmarxlopez** [infinitered/reactotron#803]
Can't connect it to android on mac os high sierra 10.13
I tried all the suggested solutions on the `troubleshooting` page, but none of them worked, hope I can use this great tool soon. 

### package.json
```javascript
{
  "name": "RnReduxTest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "axios-redux": "^1.0.4",
    "flow-typed": "^2.5.1",
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-saga": "^0.16.0",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "babel-jest": "23.4.2",
    "babel-preset-react-native": "^5",
    "flow-bin": "^0.79.1",
    "jest": "23.5.0",
    "react-test-renderer": "16.4.1",
    "reactotron-react-native": "^2.1.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
### Setup
```javascript
import Reactotron from 'reactotron-react-native';

export default function configure() {
     Reactotron.configure()
        .useReactNative()
        .connect();
}

// On index.js
...
import configure from './Config.js'
configure();

```

**Comment by rmevans9** [comment]
Have you tried running `adb reverse tcp:9090 tcp:9090`?

**Comment by karlmarxlopez** [comment]
Yes, I tried it running multiple times.

**Comment by skellock** [comment]
Try using:

```
Reactotron.configure({ host: "192.168.x.x" })
```

where `192.168.x.x` is your computer's machine.

**Comment by karlmarxlopez** [comment]
@skellock Yes, I added that already but it's still not working.

**Comment by skellock** [comment]
Are you running the right version of the Reactotron app?  Should be the 2.x version.

**Comment by karlmarxlopez** [comment]
@skellock I'm using `1.15.0`

**Comment by karlmarxlopez** [comment]
@skellock Closing this.

I've got it working by manually downloading the `v2` on the [releases](https://github.com/infinitered/reactotron/releases) because `brew` is providing the `1.15.0` version.

**Comment by skellock** [comment]
Woah!  it is?  This is news to me... I [submitted a PR](https://github.com/Homebrew/homebrew-cask/pull/51128) for 2.12.... In fact I submitted several PRs in the 2.x line.

I confirmed though, you're right.

```sh
❯ brew cask info reactotron

reactotron: 2.1.2
https://github.com/infinitered/reactotron
/usr/local/Caskroom/reactotron/1.15.0 (64B)
```

I'll look into this.  Thank you for the heads up.

**Comment by skellock** [comment]
Ohhh.... sorry, I know what's going on here... hehe..


```sh
brew update
brew cask uninstall reactotron
brew cask install reactotron

brew cask info reactotron
reactotron: 2.1.2
https://github.com/infinitered/reactotron
/usr/local/Caskroom/reactotron/2.1.2 (64B)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/reactotron.rb
```

Whew... you had me sweating there. 😅

**Comment by karlmarxlopez** [comment]
Oops sorry for the trouble @skellock 
I'm new to macOS & homebrew, I forgot to run `brew update` ✌️

**Comment by skellock** [comment]
No worries @karlmarxlopez .  I'm not new to homebrew and i still forgot to too.
