### ISSUE TITLE
Crashing App in Android

### ISSUE THREAD

**Issue by KidsAndTheHall** [infinitered/reactotron#805]
I run `adb reverse tcp:9090 tcp:9090` and start my app. It shows the device is connected then after about 5 seconds it loses connection and the app crashes. If I run the adb reverse command and have reactotron configured in the code, but don't have the reactotron application open the app doesn't crash. 

In the logs I see 

> Attempted to delete a signal while it is being emitted, likely because an object containing this signal is being deleted. A signal cannot be deleted while it is emitting.

Any ideas what might be causing this?

**Comment by skellock** [comment]
Hmm... I have yet to experience that one.

I googled that log message and a bunch of QT-related stuff came up.

Are you on Linux?

**Comment by skellock** [comment]
> Attempted to delete a signal while it is being emitted, likely because an object containing this signal is being deleted. A signal cannot be deleted while it is emitting.

Also... how brilliant is that log message, likely because the log containing this message is brilliant.  A log is brilliant that contains this message.

**Comment by KidsAndTheHall** [comment]
@skellock I'm on Mac running an Android API 28 x86 emulator. I was not having any issues with reactotron until a few days ago. I've tried a fresh install, new emulator and I'm still seeing the issue.

**Comment by KidsAndTheHall** [comment]
0.55.3 It's happening just after connecting. I don't think you'll be able to reproduce it, I think it's an issue with my environment, since no one around me seems to be having the issue. I was just hoping someone else has seen this issue before, since I am out of ideas on how to fix it.

**Comment by rmevans9** [comment]
Closing this for now due to inactivity. @KidsAndTheHall if you are still having this issue please feel free to reopen and I will try and address.
