### ISSUE TITLE
Light theme for desktop app

### ISSUE THREAD

**Issue by jigarmistry** [infinitered/reactotron#822]
Thanks for the great software tool. I have been using from last few months. Love it !!

I read issues regarding the light theme for Reactotron desktop app and I think this would be the best to have it as many developers ( like me ) do not like the dark theme. 

Is there any possibility we can get that in near future?

**Comment by skellock** [comment]
Yes.  We'll be supporting this in our 3.x branch.  🎉 

No ETA, but it's underway.
