### ISSUE TITLE
reactotron-redux @ 2.1.0 is missing typescript type def file when pulled from npm

### ISSUE THREAD

**Issue by aarondail** [infinitered/reactotron#826]
The reactotron-redux.d.ts file is present in the repo, but it is not included in the package.json "files" section so, I think, it is not included in the reactotron-redux package when published to npm.

After updating to 2.1.0 this is what I see in my project's node_modules
```
$ tree node_modules/reactotron-redux/
node_modules/reactotron-redux/
├── LICENSE
├── dist
│   └── index.js
└── package.json
```

I am happy to submit a PR if my reasoning sounds right.

**Comment by aarondail** [comment]
PR submitted

**Comment by skellock** [comment]
Merged!  Thanks @aarondail .
