### ISSUE TITLE
Show Version-Number in Reactotron

### ISSUE THREAD

**Issue by xstable** [infinitered/reactotron#859]
Would be nice to have some kind of `Help ⇒ Version Number` to see which Version of Reactotron I've currently using.

**Comment by afilp** [comment]
Hi, I do not see it, using the latest version (2.6.0):

![image](https://user-images.githubusercontent.com/7850073/51109136-f0c2b380-17fc-11e9-9941-494d8bddc78a.png)

**Comment by afilp** [comment]
Same with 2.6.1, I cannot see the version number.
