### ISSUE TITLE
Out of Memory if you try to log inside onLayout

### ISSUE THREAD

**Issue by scerelli** [infinitered/reactotron#866]
If you try to put a `Reactotron.log` or `console.tron.log` inside an onLayout function attached to a `View` the app stuck and goes out of memory.

It happens from any point of the app I'm working on, so I suppose is something related to Reactotron itself.

**Comment by rmevans9** [comment]
Are you passing the event to the log?

**Comment by scerelli** [comment]
no also a simple `console.log('test')` block the thread.

**Comment by rmevans9** [comment]
I will see if I can reproduce in the next few days and get this sorted out.

**Comment by rmevans9** [comment]
Hey @scerelli,

Sorry for taking so long to get back to you. I gave this a shot with this code and I didn't encounter any issues. Could you please try again?

```
{...}
<View onLayout={() => console.tron.log('test')}>
{... 
```

**Comment by rmevans9** [comment]
I am going to close this for now but if you find a solid way to replicate this issue please let me know and we can reopen. Thanks!
