### ISSUE TITLE
not running on Ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by microcipu** [infinitered/reactotron#872]
the app does not start on Ubuntu 18.04.1 LTS

are there some requirements?

sh Reactotron
Reactotron: 1: Reactotron: Syntax error: "(" unexpected

downloaded latest version from releases linux 64-bit

**Comment by microcipu** [comment]
I can confirm that it works with this 2 modules
the second one is libcanberra-gtk-module they should be added as requirement

**Comment by rmevans9** [comment]
I will have to figure out how to add these or if this is something we can make smoother. I haven't dealt with the Linux build much yet so it might take some time to sort out.

**Comment by rmevans9** [comment]
The applications build process has changed a bunch since this issue was created. Could anyone confirm if this is still an issue?

**Comment by rmevans9** [comment]
Closing this up. If this issue still exists please let me know and we can reopen
