### ISSUE TITLE
Add support for WSS (WebSocket Secure)

### ISSUE THREAD

**Issue by alexjebens** [infinitered/reactotron#874]
I would like to add support for WSS (WebSocket Secure) so that I can use reactotron when I am connecting from a page hosted on HTTPS for react-js.

When trying to connect from a site that is hosted using HTTPS I receive errors because the implementation in all browsers except Chrome prohibits me from connecting to a ws:// socket for security reasons.

**Comment by rmevans9** [comment]
This should be available now 👍
