### ISSUE TITLE
storybookSwitcher is not included in typing

### ISSUE THREAD

**Issue by cedriclv** [infinitered/reactotron#879]
When trying to use storybookSwitcher as defined in the docs for the react-native storybook plugin, the  typing does not provide any definition of the storybookSwitcher method under the Reactotron interface.

Looking at the documentation I would expect the interface to contain something along these lines:

reactotron-react-native.d.ts
```typescript
storybookSwitcher(`
   storybookComponent: React.Component
): (rootComponent: React.Component) => React.Component
```

**Comment by rmevans9** [comment]
We will need to get this added. Thanks for the report

**Comment by rmevans9** [comment]
This should be resolved. Please let me know if the latest version does not work for you!

**Comment by jorgemarrero** [comment]
Doesn't work for me with the bowser boilerplate.

https://github.com/infinitered/reactotron-react-native/blob/15a2f035a8784327b66f410d07ca4b27dcd1e012/src/reactotron-react-native.ts#L66

It should be something like @cedriclv says:
```
storybookSwitcher(storybookComponent: React.ReactNode
) => (rootComponent: React.ReactNode) => React.Component
```
