### ISSUE TITLE
Subscribe to complete state using * instead of empty key

### ISSUE THREAD

**Issue by thibmaek** [infinitered/reactotron#885]
Currently, if I want to subscribe to the complete store I have to follow this: https://github.com/infinitered/reactotron/issues/745 method.

Since the info in the dialog already uses a glob selector (`repo.*`) shouldn't it be that a top-level glob star (`*`) is used to monitor the complete state?

If you use an empty key and just hit enter, you can indeed monitor the complete store but double-clicking to remove won't work since there is no key in the lefthand side.

I could open a PR for this if desired, think https://github.com/infinitered/reactotron/blob/16748799825fc3edde93a4c72a9867f47b5cc8fa/packages/reactotron-redux/src/get-subscription-values.js is the place to put it?

![image](https://user-images.githubusercontent.com/6213695/49226835-f2205400-f3e7-11e8-8540-f5c16334ab53.png)

![image](https://user-images.githubusercontent.com/6213695/49226794-e0d74780-f3e7-11e8-9316-d772b1fa449c.png)

**Comment by thibmaek** [comment]
Hey https://github.com/infinitered/reactotron/pull/890 is open to get this going.

**Comment by Eyesonly88** [comment]
This is already possible with the latest release 2.6.0 (2.6.0.17)
