### ISSUE TITLE
Add app name on bottom tab where devices are listed

### ISSUE THREAD

**Issue by tokict** [infinitered/reactotron#899]
The list of conected devices could be improved a bit by adding an app name under the Platform and version in i.e ios. 

Right now I have 2 apps running and just see 2x iOS 12.1 but I cant determine which app is in which tab. Adding that info pulled from package.json would be great improvement for not much work maybe

<img width="654" alt="screen shot 2018-12-11 at 10 43 52" src="https://user-images.githubusercontent.com/3405336/49788306-b2cffc80-fd31-11e8-8949-a37c0cdab3bb.png">

**Comment by rmevans9** [comment]
I am not sure we would be able to pull the name from the `package.json` as in a `react-native` app you typically don't have direct access to files outside of the dev server. I do know that we could pull the name from the `reactotron` configuration if that would suit this need?

ref: https://github.com/infinitered/reactotron-core-client/blob/master/src/client-options.ts#L26

```
Reactotron.configure({ name: 'My Super Awesome App' }).connect()
```

**Comment by tokict** [comment]
Sure, that would do the job, and the name is usually there anyway as its a part of docs for setting up!

**Comment by GioLogist** [comment]
Still showing default `iOS` on the latest version. 

Curious, what other purpose does this serve? Couldn't find any docs on the `configure` method.

**Comment by tokict** [comment]
It only shows if you have 2 apps running on same device. I have android and ios running at the same time and it just shows platform name. Not sure why they didn't put it as default in all cases.

About configure.. when you configure the reactotron config file it there is a "name" param i the options object. It uses that for naming

**Comment by rmevans9** [comment]
It should show if those two apps have different names as well. It was left off if there is only one app name to try and conserve space if we can

**Comment by tokict** [comment]
That makes sense.
