### ISSUE TITLE
Android: Invariant Violation

### ISSUE THREAD

**Issue by Aletagro** [infinitered/reactotron#907]
Hi, I have such a problem with snapshot tests on android. I attach the log

`console.warn node_modules/react-native/Libraries/YellowBox/YellowBox.js:130
      Each ViewPager child must be a <View>. Was Component
    console.error node_modules/react-native/Libraries/YellowBox/YellowBox.js:130
      The above error occurred in the <ViewPagerAndroid> component:
          in ViewPagerAndroid (at src/index.js:652)
          in View
          in Component (at src/index.js:732)
          in _default (at ImageViewer.js:103)
          in View
          in Component (at createAnimatedComponent.js:153)
          in AnimatedComponent (at ImageViewer.js:102)
          in Modal
          in Component (at ImageViewer.js:98)
          in ImageViewer (at AddPhoto.js:173)
          in AddPhoto (at Setup.js:177)
          in Unknown (at ReviewScreen.js:171)
          in View
          in Component (at ScrollViewMock.js:31)
          in RCTScrollView
          in _class (at ScrollViewMock.js:29)
          in ScrollView (at ReviewScreen.js:120)
          in KeyboardAvoidingView (at ReviewScreen.js:119)
          in ReviewScreen (created by Connect(ReviewScreen))
          in Connect(ReviewScreen) (at Review.android.test.js:21)
          in Provider (at Review.android.test.js:20)

      Consider adding an error boundary to your tree to customize error handling behavior.
      Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
    console.warn node_modules/react-native/Libraries/YellowBox/YellowBox.js:130
      Each ViewPager child must be a <View>. Was Component
    console.error node_modules/react-native/Libraries/YellowBox/YellowBox.js:130
      The above error occurred in the <ViewPagerAndroid> component:
          in ViewPagerAndroid (at src/index.js:652)
          in View
          in Component (at src/index.js:732)
          in _default (at ImageViewer.js:103)
          in View
          in Component (at createAnimatedComponent.js:153)
          in AnimatedComponent (at ImageViewer.js:102)
          in Modal
          in Component (at ImageViewer.js:98)
          in ImageViewer (at AddPhoto.js:173)
          in AddPhoto (at Setup.js:177)
          in Unknown (at ReviewScreen.js:171)
          in View
          in Component (at ScrollViewMock.js:31)
          in RCTScrollView
          in _class (at ScrollViewMock.js:29)
          in ScrollView (at ReviewScreen.js:120)
          in KeyboardAvoidingView (at ReviewScreen.js:119)
          in ReviewScreen (created by Connect(ReviewScreen))
          in Connect(ReviewScreen) (at Review.android.test.js:41)
          in Provider (at Review.android.test.js:40)

      Consider adding an error boundary to your tree to customize error handling behavior.
      Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

  ● renders correctly ReviewScreen

    Invariant Violation: Element ref was specified as a string (viewPager) but no owner was set. This could happen for one of the
following reasons:
    1. You may be adding a ref to a function component
    2. You may be adding a ref to a component that was not created inside a component's render method
    3. You have multiple copies of React loaded
    See https://fb.me/react-refs-must-have-owner for more information.

      at invariant (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:55:19)
      at coerceRef (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5293:29)
      at reconcileSingleElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6004:27)
      at reconcileChildFibers (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6060:39)
      at reconcileChildren (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6429:32)
      at finishClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6756:9)
      at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6694:28)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7540:20)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10358:16)
      at workLoop (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10390:28)`

An empty array falls into a swiper in this test.
Is there any way to solve the problem?

**Comment by rmevans9** [comment]
Hey @Aletagro I am not sure what is going on here but it doesn't seem to be related to reactotron. If I am missing something please feel free to reopen but closing for now as I don't believe this is related to anything happening in `reactotron`
