### ISSUE TITLE
Markdown - timestamp not included (feature requests)

### ISSUE THREAD

**Issue by XenorPLxx** [infinitered/reactotron#912]
Hello!

Reactotron provides nice feature of exporting whole API calls to markdown, which I've noticed recently and started using heavily to communicate bugs to backend developers.

Would be great if those markdown exports also included local timestamp, as it'd allow backend developers to correlate my logs with theirs. It's especially important for timeout cases where I don't have any of their header identification in response (as I didn't get any :D).

Do you think it could be added in some new release?

**Comment by rmevans9** [comment]
This sounds simple enough. I am not sure when I will get to it but feel free to open a PR.

**Comment by De-ma** [comment]
Has anyone attempted this issue? I would like to work on this! 😊

**Comment by rmevans9** [comment]
@De-ma not to my knowledge. Please feel free to give it a go. You can find me on the IR community slack if you need any help (linked in the readme)

**Comment by markrickert** [comment]
Closing as completed in version `2.16.0` (quite a long time ago)
