### ISSUE TITLE
Error toggle side menu

### ISSUE THREAD

**Issue by dhanangpratama** [infinitered/reactotron#913]
<img width="513" alt="screen shot 2019-01-22 at 17 58 57" src="https://user-images.githubusercontent.com/6315693/51531294-9adeb300-1e6f-11e9-862e-7beef66da6a7.png">

I get above error when toggle side menu. Anyone get this error too?

**Comment by rmevans9** [comment]
That looks like a casualty to a largish overhaul to the electron setup that I did a few weeks back. I can look at it shortly but if anyone beats me to it I will gladly land a PR.
