### ISSUE TITLE
Disconnecting after a couple minutes

### ISSUE THREAD

**Issue by mikerodham** [infinitered/reactotron#916]
I'm using an external device (iPad Mini 2) to build my application on, I'm using Reactotron but I'm noticing after maybe 2-3 minutes of inactivity, the device will disconnect so I have to reload the app so it can re-make the call to Reactotron to re-hook. I'm developing a front-end system and a back-end system, so when I'm writing code for my back-end system It's kind of annoying have to reload my device because I've taken some time re-working some code. 

Why isn't the connection constant until I manually disconnect?

**Comment by mikerodham** [comment]
Ah good old apple. I suppose for now I could run a `setInterval` to run every 60 seconds which just makes a asyncstorage save, just to keep it updating for now.

**Comment by BusseBu** [comment]
The same for me. I'm using genymotion and reactotron keeps disconnecting from virtual device every minute if I'm not doing something with my app. And it's really hard to restart to make it working again.

**Comment by jamonholmgren** [comment]
Sounds like it's happening on both iOS and Android then?

**Comment by jamonholmgren** [comment]
Can you folks edit your comments to add what OS you're on and what version it is, please? Windows, macOS, Linux, and what version of each.

**Comment by rmevans9** [comment]
I actually personally had this occur earlier today on an iOS sim. I didn't have the time to investigate it properly at the time but I will be looking at it tonight to see if I can pin this down.

**Comment by rmevans9** [comment]
I have tracked down the issue and will be working to land a fix tonight.

**Comment by valeriehorgan** [comment]
Save your marriage from divorce and restore breakup today with the help of email: robinson.buckler@ yahoo. com
