### ISSUE TITLE
Reactotron.display trim String outputs unexpectedly

### ISSUE THREAD

**Issue by wxsms** [infinitered/reactotron#920]
reactotron version: 0.9.0

As a debug tool, maybe it should display informations AS IS. at least provide an option to do so. Sometimes it makes developers confuse.

**Comment by rmevans9** [comment]
Hey @wxsms!

Thats a bit old version of reactotron you have there. Would you mind updating when you have a sec? Also could you include an example of what you are sending and what you are seeing in the output to help me better understand what is going wrong here?

**Comment by rmevans9** [comment]
Closing this issue as I am not sure if this is actionable without further information. If you are still having issues please feel free to reopen with the requested info. Thanks!
