### ISSUE TITLE
Timeline history getting truncated

### ISSUE THREAD

**Issue by trevithj** [infinitered/reactotron#922]
We are on version 2.6.3.188 - connections now nice and stable, _thank_ you!
I notice that older events in the timeline are falling off the bottom of the list. Re-ordering or filtering doesn't make any difference, the oldest events are gone after a time.

Is this configurable? Our redux is busy, so we often need to reference those older events.

**Comment by rmevans9** [comment]
Hey @trevithj!

I am glad to hear that everything is running nice and stable. 

The maximum number of commands right now is 500. The only real reason for this is we wanted to avoid soaking up too much memory on users machines by storing more. As of right now it is not configurable. I would not be opposed to either upping this limit OR making it configurable in some way (maybe a settings screen where you can change it and this value is stored in local storage). You can find the current max commands here:

https://github.com/infinitered/reactotron/blob/master/src/Lib/commands.js#L5

**Comment by trevithj** [comment]
@rmevans9 Thanks for the clarity. I assume that we'd need to clone and rebuild the app in order to change that setting?
I'm trying to add an 'enhancement' label to this issue, but for some reason github won't let me. Could you oblige?

**Comment by rmevans9** [comment]
Yeah, you could do that but if it is a reasonable limit I would accept a PR to bump the number so that way you could continue using the published version.

**Comment by trevithj** [comment]
I'll ponder. The trouble is that in the testing phase we really need an _unreasonable_ limit. 😄 
Thanks for your help.

**Comment by rmevans9** [comment]
This is fair - Maybe we should set our sights on introducing a settings screen that lets you set this limit to any _unreasonable_ limit you want? This way you could have whatever limit you feel you need while not causing troubles for other users that don't need that same unreasonable limit.

**Comment by trevithj** [comment]
Another thought: what if the 500 limit only applied to _filtered_ events? That is, add an option to exclude unfiltered events from the history. The 500 limit seems like plenty in that case.
Just a thought.

**Comment by rmevans9** [comment]
When you say filtered events are you talking about filtered within the `reactotron` app? If so then that doesn't really buy us anything as we still have to keep track of the filtered out messages. If you are talking about the `except/filter` functionality built into `reactotron-redux` and `reactotron-mst` then those filtered messages should not be counting toward that limit.

ref:
https://github.com/infinitered/reactotron/blob/master/docs/plugin-redux.md#except
https://github.com/infinitered/reactotron/blob/master/docs/plugin-mst.md#filter

**Comment by trevithj** [comment]
Okay, the `except` option is a possible work-around. I envision making temporary/local changes to `reactotronConfig.js` to declutter the list for specific cases. Thank you, that should do us for now.

To clarify: there are two concepts of `filtering` here. One temporary excludes events from being displayed in a list, the other prevents events from ever reaching the list in the first place.
I think the Reactotron UI offers a nicer filter function than the `exclude` option. The idea was to use the UI filter but add the ability to toggle between the two sorts of filtering. This would save re-writing the config file.
But yes, it would mean some events never get logged.

**Comment by rmevans9** [comment]
@trevithj just out of interest what makes them a bit awkward to use? I would love to hear more about this so we can improve them.

**Comment by trevithj** [comment]
@rmevans9 I meant the UI. I have played with this today and can get an acceptable length of event history by editing the `reactotronConfig.js` to exclude noisy action types. Sometimes that meant defining a regex or a custom function.
The approach is simple enough, and very versatile. Having to edit a config file between test runs is the awkward bit. But it is a good work-around for our issue.
