### ISSUE TITLE
Save Window State on Quit/Reload

### ISSUE THREAD

**Issue by esthor** [infinitered/reactotron#929]
It would be great if the Reactotron window stayed the same size and even the same position when I close and reopen the app. Currently, every time I open the app, I need to resize and reposition it, which leads to a lot of wasted clicks and drags.

Without knowing the first thing about implementing this, I came across a few approaches:
**A specialized library for this task:**  https://github.com/mawie81/electron-window-state
**Another solution for storing the window state data**: https://github.com/sindresorhus/electron-store#readme
**Using the Electron docs for getting window size** (and the save to local storage?): https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetboundsbounds-animate

**Comment by rmevans9** [comment]
:wave: Hey @esthor!

I think this is a great idea. I know it would make a coworker of mine very happy to see this happen. I am looking at the solutions you found and will look to implement soon.

**Comment by rmevans9** [comment]
This is included in the beta release of reactotron if anyone wants to give it a shot before landing on master.

**Comment by esthor** [comment]
Awesome! 🎉 Seems to work just fine for me...I'll report any issues I find in the beta. Thanks for the quick solve!

**Comment by rmevans9** [comment]
This has been released (a few days ago, just forgot to close it)
