### ISSUE TITLE
Update onCustomCommand to take description + document it

### ISSUE THREAD

**Issue by rmevans9** [infinitered/reactotron#935]
We have a `onCustomCommand` function that allows users to build commands very easily. We should update the command call to take in a description too so we can build out a nice UI for them to be executed.

**Comment by kevinvangelder** [comment]
Not sure if this would be part of this or as a separate feature, but a community member requested the ability to pass params with/to their custom commands. With the `commandMiddleware` option you would need to do custom pattern matching to make it work, but maybe it would be more straightforward with the `onCustomCommand` method?

**Comment by rmevans9** [comment]
I like this idea. If we have the user define the params we could even use those as hints in the UI to build out a nice UI for them to send the commands with.

**Comment by markrickert** [comment]
The latest version of reactotron supports this feature. You can send params to commands and we show it in the reactotron app:

```ts
// Accept user input from Reactotron and navigate to that route:
Reactotron.onCustomCommand({
  command: "navigateTo",
  handler: (args) => {
    const { route } = args
    if (route) {
      Reactotron.log(`Navigating to: ${route}`)
      navigate(route)
    } else {
      Reactotron.log("Could not navigate. No route provided.")
    }
  },
  title: "Navigate To Screen",
  description: "Navigates to a screen by name.",
  args: [
    {
      name: "route",
      type: ArgType.String,
    },
  ],
})
```

![Screenshot 2024-01-23 at 6 20 06 PM](https://github.com/infinitered/reactotron/assets/139261/f4b9cc8a-a430-4f19-8c34-df51f9a2ecd8)
