### ISSUE TITLE
JSON view of values

### ISSUE THREAD

**Issue by xstable** [infinitered/reactotron#947]
Would be a nice feature if we could add a JSON-Formater to make the value of JSON-Data easily readable.

**Comment by rmevans9** [comment]
Hey @xstable!

We actually are formatting JSON when displaying them in a ton of places. Are you seeing a specific place where this isn't occurring? Can you provide a screenshot please?

**Comment by xstable** [comment]
It's the output of AsyncStorage. 
![image](https://user-images.githubusercontent.com/1778068/56013876-30f9db00-5cf3-11e9-9262-2754b689f1e8.png)

**Comment by rmevans9** [comment]
The issue I can see here Async Storage requires that the value be a string so you are likely running a `JSON.stringify` on that. When it reaches reactotron it doesn't know that what is in the string used to be JSON so it doesn't do anything to it. I guess there are a few ways that we could try and solve for this:

1. Just try and `JSON.parse` the value but make sure to try/catch it so it doesn't blow up if it isn't JSON that is in there. This would have the side effect that ALL Async Storage commands will try and be parsed which could be slow if there are a ton
2. Add a way to somehow declare the type. If we knew which ones were meant to be JSON then we could parse it at the right times
3. Add a toggle in the item to turn on "pretty JSON viewing" leaving it in the hands of the user of it to turn on when they see fit.

I am not sure I like any of those options much at this point in time.

**Comment by longnguyen2508** [comment]
I had the same issue. Did you figure out how to fix it?

**Comment by longnguyen2508** [comment]
Instead of view state changed in Timeline tab. You should change to the State tab and track the state you want.
![Screenshot 2023-12-06 at 16 08 46](https://github.com/infinitered/reactotron/assets/102789808/fc9f96af-1b09-4164-a1d2-6f487024c861)

**Comment by HubertRyanOfficial** [comment]
> Instead of view state changed in Timeline tab. You should change to the State tab and track the state you want. ![Screenshot 2023-12-06 at 16 08 46](https://private-user-images.githubusercontent.com/102789808/288321970-fc9f96af-1b09-4164-a1d2-6f487024c861.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MjYxMTEsIm5iZiI6MTcyOTgyNTgxMSwicGF0aCI6Ii8xMDI3ODk4MDgvMjg4MzIxOTcwLWZjOWY5NmFmLTFiMDktNDE2NC1hMWQyLTZmNDg3MDI0Yzg2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQwMzEwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODVmYTk1MWY4ODBhNjVjZjgwZWQxZGVhYmVhYjI5NzMxNjVkN2M0ZDA0MGUxMmQyMDdhYmRmOTJmYmM5OWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rsOhEumyzlpb0X28Bll9fXadjlXx2OseSqy7mC7_eU4)

Like how? When I press command + n the State tab asks a command? But what kind of command? The asyncstorage key?
