### ISSUE TITLE
Monitor firebase traffic

### ISSUE THREAD

**Issue by napalm272** [infinitered/reactotron#948]
Hi,
Thank you for this awesome tool. From Timeline I can see http requests and responses.  However, I'm not seeing any firebase traffic. Do I need some special setup to see it?

Thanks

**Comment by rmevans9** [comment]
Hey @napalm272 

I suspect what is happening here is firebase is sending their data on the native side. Reactotron is only able to monitor network requests initiated from the javascript side of the bridge.

**Comment by napalm272** [comment]
Ah that makes sense, I'm using react-native-firebase. Is there an alternative to monitor traffic on the native side?
Thanks

**Comment by rmevans9** [comment]
I do not know one off the top of my head.

Closing this as I don't forsee us being able to support this in reactotron.

**Comment by nonameolsson** [comment]
> Ah that makes sense, I'm using react-native-firebase. Is there an alternative to monitor traffic on the native side?
> Thanks

That is true. With `react-native-firebase` it uses the native side of the app. If you just need the basic features of Firebase, like Realtime Databse, Firestore, Authentication and Storage, then the Web SDK works.
