### ISSUE TITLE
Fail connection to Android

### ISSUE THREAD

**Issue by costerik** [infinitered/reactotron#950]
The connection to Android emulator doesn't work

**Comment by kristoferpelchat** [comment]
Same thing here! I followed https://github.com/infinitered/reactotron/blob/master/docs/quick-start-react-native.md and iOS is working great! Would love to be able to use Android too. Great tool!

**Comment by rmevans9** [comment]
Can you guys try to run this in a terminal:

`adb reverse tcp:9090 tcp:9090`

while a single Android emulator is running then reload the app and see if that solves it?

**Comment by willmorim** [comment]
Can you guys put in the documentation?

> adb reverse tcp:9090 tcp:9090

its work for me too

**Comment by rmevans9** [comment]
This has been brought up a few times. I think it would make sense to. If anyone wants to pop open a PR adding this where it makes sense I will gladly accept it. If not I should be able to eventually get to it.
