### ISSUE TITLE
port config guide

### ISSUE THREAD

**Issue by jerdie** [infinitered/reactotron#951]
Hi,

It says that we are now able to change the port in 2.10.0.  #946 states that you can find it in reactotron menu. However, I couldn't find any config settings in the menu. Are there any steps I need to do before I can use this config? It would be great if there is a guide for this. 

![image](https://user-images.githubusercontent.com/5143814/56109235-3caf0100-5f82-11e9-8cc9-b63c8afc82f7.png)

I'm using Windows 10 BTW.

**Comment by rmevans9** [comment]
Oh no! It looks like we might have a bug on windows here. There should certainly be menu items in there. I’ll have to dig into what is going wrong there.

**Comment by Fl4zher** [comment]
I've got the same problem on windows 10

**Comment by rmevans9** [comment]
Yeah, I identified the problem but haven't had time to resolve and test it.

Basically we build the mac menu: https://github.com/infinitered/reactotron/blob/master/src/menu.js#L44

We don't build a Win menu: https://github.com/infinitered/reactotron/blob/master/src/menu.js#L185

It should be as easy as putting the right menus in there but I don't get on windows much so any help resolving and testing this would be appreciated.

**Comment by carlospence** [comment]
Click on Preference on the File Menu on Windows starts up Visual Studio 2015 on version 2.15.0

**Comment by carlospence** [comment]
Changing the port on reactotron desktop app only does not work, I had to change the port also in the node_modules also. 
I tried adding  port parameter to the .configure method in the ReactotronConfig file, it didn't work.
I tried add port number to the host e.g '192.168.0.100:9099', it didn't work out.

Until I went to change the default port number reactotron-react-native module inside node_modules 
\node_modules\reactotron-react-native\dist\index.js

I believe there should be a better way to change the port options. 9090 is a very common port number used by developers. I use it in my several applications and there should be an easy way to configure and change default port number. That of the desktop app is working well.

**Comment by rmevans9** [comment]
It should be working to pass it in on configure. Can you please give me the versions of all the reactotron libs you are using please?

**Comment by Mootassame** [comment]
this steps working for me : 
1- open your cli and write this command:      adb reverse tcp:9090 tcp:9090 
2- add this to a file (e.g lib/Reactotron.js):
`import Reactotron, { asyncStorage } from 'reactotron-react-native';
Reactotron
    .configure() // controls connection & communication settings
    .useReactNative(asyncStorage()) // add all built-in react native plugins
    .connect();`

4- import the File in your app.js:
`    if (__DEV__) {
      import('../../lib/Reactotron').then(() => console.log('Reactotron Configured'));
    }`
