### ISSUE TITLE
Is the Except documentation outdated?

### ISSUE THREAD

**Issue by GYberkeley** [infinitered/reactotron#953]
It doesn't seem to work for me when I pass an array of strings to reactotronRedux. Any chance the docs are out of date?

**Comment by rmevans9** [comment]
That particular part of the plugin hasn't been changed recently but it could be. Could you provide the code you are trying that isn't working so we can work through it?

**Comment by thomasw** [comment]
`except` and `isActionImportant` are declared at https://github.com/infinitered/reactotron-redux/blob/87e07907112f5e0c61ad726ff453b859412be3a0/src/pluginConfig.ts#L5-L6

But, over here, they're ignored and not passed along when the plugin is instantiated as far as I can tell: 

https://github.com/infinitered/reactotron-redux/blob/87e07907112f5e0c61ad726ff453b859412be3a0/src/index.ts#L11-L15

The specfici documentation @GYberkeley was referring to is https://github.com/infinitered/reactotron/blob/master/docs/plugin-redux.md#except. The specific examples listed there do not currently work.

**Comment by rmevans9** [comment]
Seems this is a bug. I will see about resolving this soon.

**Comment by rmevans9** [comment]
This is fixed in the latest version of `reactotron-redux`
