### ISSUE TITLE
AsyncStorage needs to be imported from 'https://github.com/react-native-community/react-native-async-storage'

### ISSUE THREAD

**Issue by afilp** [infinitered/reactotron#996]
In the latest versions of react-native, there is a warning about asyncStorage:

Reactoton needs to import it from here from now on:
https://github.com/react-native-community/react-native-async-storage

**Comment by rmevans9** [comment]
https://github.com/infinitered/reactotron-react-native/pull/16

I have a pr that will solve this but there is talk of a possibility that metro will allow optional requires. If that happens the direction will change. I’m trying to hold off on anything until I know which way they are taking it.

**Comment by djMax** [comment]
Any update on this?

**Comment by rmevans9** [comment]
@djMax Yes, actually. Please find a PR I am playing around to solve for this here: https://github.com/infinitered/reactotron-react-native/pull/16

**Comment by mgpepe** [comment]
Also excited to get this to work!

**Comment by jiraiya103** [comment]
same issue, any solution or update ?

**Comment by hnrqsss** [comment]
Same problem here with RN 59.8

**Comment by nitaking** [comment]
I create PR

**Comment by jamonholmgren** [comment]
There's a new beta version out that addresses this. Please give it a shot: https://github.com/infinitered/reactotron-react-native/releases/tag/v4.0.0-beta.1%40beta

**Comment by markrickert** [comment]
Beta has been released and this has been addressed in recent versions.
